import * as fs from 'fs';
import * as path from 'path';
// Relative import: pulled in by ts-node scripts without path aliases.
import { FK_SPECS } from '../../../scripts/migrate/fk-specs';

/**
 * Remediation 5.3: drizzle/0025 must contain every FK_SPEC exactly — editing
 * one without the other fails here.
 */
describe('0025_cross_schema_fks stays in sync with fk-specs.ts', () => {
  const sql = fs.readFileSync(
    path.resolve(__dirname, '..', '..', '..', 'drizzle', '0025_cross_schema_fks.sql'),
    'utf8',
  );
  const normalize = (s: string): string => s.replace(/\s+/g, ' ').trim();

  it('contains every spec constraint with its exact definition', () => {
    for (const spec of FK_SPECS) {
      expect(sql).toContain(spec.name);
      const expectedAdd = `ADD CONSTRAINT ${spec.name} ${normalize(spec.definition)} NOT VALID`;
      expect(normalize(sql)).toContain(expectedAdd);
    }
  });

  it('is generated by the committed generator (header present)', () => {
    expect(sql).toContain('GENERATED by scripts/migrate/generate-0025.ts');
    expect(sql).toContain("SET LOCAL lock_timeout = '5s';");
  });

  it('does not reference constraints that fk-specs.ts does not define', () => {
    const names = new Set(FK_SPECS.map((s) => s.name));
    const referenced = [...sql.matchAll(/ADD CONSTRAINT (fk_[a-z_]+)/g)].map((m) => m[1]);
    for (const name of referenced) expect(names.has(name)).toBe(true);
  });
});
