import * as fs from 'fs';
import * as path from 'path';
// Relative import: pulled in by ts-node scripts without path aliases.
import { FK_SPECS, FK_SPECS_IN_0020 } from '../../../scripts/migrate/fk-specs';

/**
 * Remediation 5.3: drizzle/0025 must contain every FK_SPEC exactly — editing
 * one without the other fails here.
 */
describe('0025_cross_schema_fks stays in sync with fk-specs.ts', () => {
  const sql = fs.readFileSync(
    path.resolve(__dirname, '..', '..', '..', 'drizzle', '0025_cross_schema_fks.sql'),
    'utf8',
  );
  const normalize = (s: string): string => s.replace(/\s+/g, ' ').trim();

  it('contains every spec constraint with its exact definition', () => {
    for (const spec of FK_SPECS) {
      expect(sql).toContain(spec.name);
      const expectedAdd = `ADD CONSTRAINT ${spec.name} ${normalize(spec.definition)} NOT VALID`;
      expect(normalize(sql)).toContain(expectedAdd);
    }
  });

  it('is generated by the committed generator (header present)', () => {
    expect(sql).toContain('GENERATED by scripts/migrate/generate-0025.ts');
    expect(sql).toContain("SET LOCAL lock_timeout = '5s';");
  });

  it('does not reference constraints that fk-specs.ts does not define', () => {
    const names = new Set(FK_SPECS.map((s) => s.name));
    const referenced = [...sql.matchAll(/ADD CONSTRAINT (fk_[a-z_]+)/g)].map((m) => m[1]);
    for (const name of referenced) expect(names.has(name)).toBe(true);
  });

  it('0020 still carries the three FKs listed in FK_SPECS_IN_0020', () => {
    const sql0020 = normalize(
      fs.readFileSync(
        path.resolve(__dirname, '..', '..', '..', 'drizzle', '0020_fk_actions_and_missing_indexes.sql'),
        'utf8',
      ),
    );
    for (const spec of FK_SPECS_IN_0020) {
      expect(sql0020).toContain(`ADD CONSTRAINT ${spec.name} ${normalize(spec.definition)} NOT VALID`);
    }
  });
});

/**
 * Remediation 5.1: the *-fk.ts scripts are thin runners over fk-specs.ts. None may carry
 * its own copy of a definition, and together they must cover every spec exactly once.
 */
describe('scripts/migrate/*-fk.ts use fk-specs.ts as their only source', () => {
  const dir = path.resolve(__dirname, '..', '..', '..', 'scripts', 'migrate');
  const scripts = fs
    .readdirSync(dir)
    .filter((f) => /^2026-.*-fk\.ts$/.test(f) && f !== '2026-10-identity-fk.ts');

  it('finds the six runner scripts', () => {
    expect(scripts).toHaveLength(6);
  });

  it.each(scripts)('%s imports fk-specs and defines no constraint inline', (file) => {
    const src = fs.readFileSync(path.join(dir, file), 'utf8');
    expect(src).toContain("from './fk-specs'");
    expect(src).not.toMatch(/definition:\s/);
    expect(src).not.toMatch(/ADD CONSTRAINT/);
  });

  it('covers every spec in FK_SPECS and FK_SPECS_IN_0020 exactly once', () => {
    const referenced: string[] = [];
    for (const file of scripts) {
      const src = fs.readFileSync(path.join(dir, file), 'utf8');
      const call = src.match(/fkSpecs\(([^)]*)\)/s)?.[1] ?? '';
      referenced.push(...[...call.matchAll(/'(fk_[a-z_]+)'/g)].map((m) => m[1]));
    }
    const expected = [...FK_SPECS, ...FK_SPECS_IN_0020].map((s) => s.name).sort();
    expect([...referenced].sort()).toEqual(expected);
  });
});
