/**
 * CSS styles for rich widget components.
 * Injected into the embed snippet alongside the existing widget styles.
 */

export const WIDGET_RICH_STYLES: string = [
  '',
  '.ys-comp-wrap{margin:6px 0;animation:ys-msg-in .28s cubic-bezier(.34,1.2,.64,1);}',
  '.ys-msg-assistant .ys-comp-wrap{margin:0;animation:none;}',
  '.ys-msg-assistant .ys-comp-form,.ys-msg-assistant .ys-comp-chart{background:#f8fafc;}',
  '',
  '.ys-md-p{margin:2px 0;font-size:13.5px;line-height:1.6;}',
  '.ys-md-h1,.ys-md-h2,.ys-md-h3{font-weight:600;margin:8px 0 4px;line-height:1.3;}',
  '.ys-md-h1{font-size:16px;}',
  '.ys-md-h2{font-size:14.5px;}',
  '.ys-md-h3{font-size:13.5px;}',
  '.ys-md-link{color:#6366f1;text-decoration:none;}',
  '.ys-md-link:hover{text-decoration:underline;}',
  '.ys-md-inline-code{background:#f1f5f9;padding:1px 5px;border-radius:4px;font-size:12px;font-family:"SF Mono",SFMono-Regular,Consolas,"Liberation Mono",Menlo,monospace;color:#e11d48;}',
  '.ys-md-codeblock{background:#1e293b;color:#e2e8f0;padding:10px 12px;border-radius:8px;font-size:12px;line-height:1.5;overflow-x:auto;font-family:"SF Mono",SFMono-Regular,Consolas,"Liberation Mono",Menlo,monospace;max-height:300px;}',
  '.ys-md-ul{margin:4px 0;padding-left:18px;font-size:13.5px;line-height:1.6;}',
  '.ys-md-ul li{margin:2px 0;}',
  '',
  '.ys-comp-error{background:#fef2f2;color:#b91c1c;border:1px solid #fecaca;border-radius:10px;padding:10px 14px;font-size:12.5px;line-height:1.5;}',
  '.ys-comp-error-title{font-weight:600;margin-bottom:4px;}',
  '',
  '.ys-comp-code{background:#1e293b;border-radius:8px;overflow:hidden;font-size:12px;}',
  '.ys-comp-code-header{display:flex;align-items:center;justify-content:space-between;padding:6px 12px;background:rgba(255,255,255,.06);border-bottom:1px solid rgba(255,255,255,.1);}',
  '.ys-comp-code-lang{color:#94a3b8;font-size:11px;font-weight:500;text-transform:uppercase;letter-spacing:.03em;}',
  '.ys-comp-code-copy{background:rgba(255,255,255,.08);color:#cbd5e1;border:none;border-radius:4px;padding:2px 8px;font-size:10px;cursor:pointer;font-family:inherit;}',
  '.ys-comp-code-copy:hover{background:rgba(255,255,255,.15);}',
  '.ys-comp-code pre{margin:0;padding:10px 12px;overflow-x:auto;color:#e2e8f0;line-height:1.5;font-family:"SF Mono",SFMono-Regular,Consolas,"Liberation Mono",Menlo,monospace;}',
  '.ys-comp-code-filename{color:#94a3b8;font-size:11px;margin-left:8px;}',
  '',
  '.ys-comp-sources{margin:6px 0;font-size:12px;color:#4f46e5;}',
  '.ys-comp-sources-trigger{display:flex;align-items:center;gap:6px;background:none;border:none;padding:4px 0;cursor:pointer;font:inherit;font-weight:500;color:inherit;width:100%;max-width:100%;text-align:left;}',
  '.ys-comp-sources-trigger:hover{opacity:.85;}',
  '.ys-comp-sources-label{font-weight:500;margin:0;flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.ys-comp-sources-count{flex-shrink:0;font-size:10px;font-weight:600;line-height:1;padding:2px 6px;border-radius:999px;background:rgba(79,70,229,.12);color:#4f46e5;}',
  '.ys-comp-sources-trigger .ys-globe-icon,.ys-comp-sources-trigger .ys-chevron{width:14px;height:14px;flex-shrink:0;}',
  '.ys-comp-sources-trigger .ys-chevron{opacity:.7;transition:transform .2s ease;}',
  '.ys-comp-sources.ys-open .ys-chevron{transform:rotate(180deg);opacity:1;}',
  '.ys-comp-sources-panel{display:none;margin-top:8px;flex-direction:column;gap:4px;max-width:100%;max-height:200px;overflow-y:auto;padding-right:4px;}',
  '.ys-comp-sources-panel::-webkit-scrollbar{width:4px;}',
  '.ys-comp-sources-panel::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:4px;}',
  '.ys-comp-sources.ys-open .ys-comp-sources-panel{display:flex;}',
  '.ys-comp-source-item{display:flex;align-items:center;gap:6px;color:inherit;text-decoration:none;font-weight:500;font-size:11.5px;line-height:1.35;min-width:0;max-width:100%;padding:2px 0;}',
  '.ys-comp-source-item:hover{text-decoration:underline;}',
  '.ys-comp-source-item span{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.ys-book-icon{width:14px;height:14px;flex-shrink:0;opacity:.85;}',
  '',
  '.ys-comp-plan{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;}',
  '.ys-comp-plan-title{font-size:13px;font-weight:600;color:#1e293b;margin-bottom:8px;}',
  '.ys-comp-plan-steps{display:flex;flex-direction:column;gap:6px;}',
  '.ys-comp-plan-step{display:flex;align-items:flex-start;gap:8px;font-size:12.5px;color:#334155;line-height:1.4;}',
  '.ys-comp-plan-step-icon{width:18px;height:18px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:10px;margin-top:1px;}',
  '.ys-comp-plan-step-icon.ys-status-pending{background:#f1f5f9;color:#94a3b8;}',
  '.ys-comp-plan-step-icon.ys-status-in-progress{background:#dbeafe;color:#3b82f6;animation:ys-pulse 1.5s ease-in-out infinite;}',
  '.ys-comp-plan-step-icon.ys-status-completed{background:#dcfce7;color:#16a34a;}',
  '.ys-comp-plan-step-icon.ys-status-error{background:#fef2f2;color:#dc2626;}',
  '.ys-comp-plan-step-agent{font-size:11px;color:#94a3b8;margin-top:1px;}',
  '.ys-comp-plan-progress{font-size:11px;color:#64748b;margin-top:6px;}',
  '',
  '.ys-comp-task{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;}',
  '.ys-comp-task-title{font-size:13px;font-weight:600;color:#1e293b;margin-bottom:6px;}',
  '.ys-comp-task-items{display:flex;flex-direction:column;gap:4px;}',
  '.ys-comp-task-item{display:flex;align-items:center;gap:8px;font-size:12.5px;color:#334155;}',
  '.ys-comp-task-check{width:16px;height:16px;border-radius:4px;border:1.5px solid #cbd5e1;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:10px;}',
  '.ys-comp-task-check.ys-done{background:#16a34a;border-color:#16a34a;color:#fff;}',
  '',
  '.ys-comp-queue{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;}',
  '.ys-comp-queue-title{font-size:13px;font-weight:600;color:#1e293b;margin-bottom:6px;}',
  '.ys-comp-queue-items{display:flex;flex-direction:column;gap:4px;}',
  '.ys-comp-queue-item{display:flex;align-items:center;gap:8px;font-size:12.5px;color:#334155;}',
  '.ys-comp-queue-badge{font-size:10px;padding:2px 6px;border-radius:4px;font-weight:500;}',
  '.ys-comp-queue-badge.ys-pending{background:#f1f5f9;color:#64748b;}',
  '.ys-comp-queue-badge.ys-active{background:#dbeafe;color:#2563eb;}',
  '.ys-comp-queue-badge.ys-completed{background:#dcfce7;color:#16a34a;}',
  '',
  '.ys-comp-checkpoint{display:inline-flex;align-items:center;gap:6px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:6px;padding:4px 10px;font-size:12px;color:#166534;font-weight:500;}',
  '',
  '.ys-comp-reasoning{border:1px solid #e2e8f0;border-radius:10px;overflow:hidden;}',
  '.ys-comp-reasoning-toggle{display:flex;align-items:center;gap:6px;padding:8px 12px;font-size:12px;color:#64748b;cursor:pointer;background:#f8fafc;border:none;width:100%;font-family:inherit;text-align:left;}',
  '.ys-comp-reasoning-toggle:hover{background:#f1f5f9;}',
  '.ys-comp-reasoning-content{padding:8px 12px;font-size:12.5px;color:#475569;line-height:1.5;display:none;border-top:1px solid #e2e8f0;}',
  '.ys-comp-reasoning-content.ys-open{display:block;}',
  '',
  '.ys-comp-webpreview{border:1px solid #e2e8f0;border-radius:10px;overflow:hidden;background:#fff;}',
  '.ys-comp-webpreview-bar{display:flex;align-items:center;justify-content:space-between;padding:6px 10px;background:#f8fafc;border-bottom:1px solid #e2e8f0;}',
  '.ys-comp-webpreview-url{font-size:11px;color:#64748b;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1;}',
  '.ys-comp-webpreview-actions{display:flex;gap:6px;}',
  '.ys-comp-webpreview-btn{background:#f1f5f9;border:1px solid #e2e8f0;border-radius:4px;padding:2px 8px;font-size:10px;color:#475569;cursor:pointer;font-family:inherit;}',
  '.ys-comp-webpreview-btn:hover{background:#e2e8f0;}',
  '.ys-comp-webpreview-frame{width:100%;height:280px;border:none;}',
  '',
  '.ys-comp-sandbox{background:#1e293b;border-radius:8px;overflow:hidden;font-size:12px;}',
  '.ys-comp-sandbox-tabs{display:flex;border-bottom:1px solid rgba(255,255,255,.1);}',
  '.ys-comp-sandbox-tab{padding:6px 12px;font-size:11px;color:#94a3b8;cursor:pointer;background:transparent;border:none;font-family:inherit;border-bottom:2px solid transparent;}',
  '.ys-comp-sandbox-tab.ys-active{color:#e2e8f0;border-bottom-color:#6366f1;}',
  '.ys-comp-sandbox-content{padding:10px 12px;color:#e2e8f0;overflow-x:auto;max-height:200px;font-family:"SF Mono",SFMono-Regular,Consolas,"Liberation Mono",Menlo,monospace;line-height:1.5;white-space:pre-wrap;}',
  '',
  '.ys-comp-artifact{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:10px 12px;}',
  '.ys-comp-artifact-icon{width:36px;height:36px;border-radius:8px;background:#f1f5f9;display:flex;align-items:center;justify-content:center;font-size:16px;flex-shrink:0;}',
  '.ys-comp-artifact-info{flex:1;min-width:0;}',
  '.ys-comp-artifact-name{font-size:13px;font-weight:500;color:#1e293b;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '.ys-comp-artifact-type{font-size:11px;color:#64748b;}',
  '',
  '.ys-comp-citation{display:inline-flex;align-items:center;gap:4px;background:#f5f3ff;border:1px solid #ddd6fe;border-radius:4px;padding:1px 6px;font-size:11px;color:#7c3aed;font-weight:500;cursor:default;vertical-align:middle;}',
  '.ys-comp-citation-detail{margin-top:6px;background:#faf5ff;border:1px solid #e9d5ff;border-radius:8px;padding:8px 10px;font-size:11.5px;color:#6b21a8;line-height:1.5;max-width:300px;}',
  '.ys-comp-citations{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px;}',
  '.ys-comp-citation-link{display:inline-flex;align-items:center;gap:6px;color:#4f46e5;text-decoration:underline;font-weight:500;font-size:12px;line-height:1.35;max-width:100%;}',
  '.ys-comp-citation-link:hover{color:#4338ca;}',
  '.ys-comp-citation-link .ys-book-icon{width:14px;height:14px;flex-shrink:0;}',
  '.ys-comp-citation-link span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
  '',
  '.ys-comp-chart{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px;min-height:60px;}',
  '.ys-chart-title{font-size:13px;font-weight:600;color:#1e293b;margin-bottom:8px;}',
  '.ys-chart-wrap{width:100%;}',
  '.ys-chart-error{color:#94a3b8;font-size:12px;text-align:center;padding:20px;}',
  '',
  '.ys-comp-form{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px;}',
  '.ys-comp-form-title{font-size:13px;font-weight:600;color:#1e293b;margin-bottom:10px;}',
  '.ys-comp-form-options{display:flex;flex-direction:column;gap:8px;margin-bottom:10px;}',
  '.ys-comp-form-option{background:#f8fafc;border:1.5px solid #e2e8f0;border-radius:8px;padding:10px 12px;font-size:13px;color:#334155;text-align:left;cursor:pointer;font-family:inherit;transition:background .15s,border-color .15s;}',
  '.ys-comp-form-option:hover{background:#f1f5f9;border-color:#cbd5e1;}',
  '.ys-comp-form-option.ys-selected{background:#eef2ff;border-color:#6366f1;color:#4338ca;font-weight:500;}',
  '.ys-comp-form-submit{background:#6366f1;color:#fff;border:none;border-radius:8px;padding:8px 14px;font-size:12.5px;font-weight:500;cursor:pointer;font-family:inherit;}',
  '.ys-comp-form-submit:disabled{opacity:.45;cursor:not-allowed;}',
  '.ys-comp-form-submit:not(:disabled):hover{background:#4f46e5;}',
  '',
  '@media (prefers-color-scheme:dark){',
  '  .ys-comp-sources,.ys-comp-plan,.ys-comp-task,.ys-comp-queue,.ys-comp-artifact,.ys-comp-chart,.ys-comp-form{background:transparent;border-color:transparent;}',
  '  .ys-comp-sources{color:#818cf8;}',
  '  .ys-comp-sources-count{background:rgba(129,140,248,.15);color:#a5b4fc;}',
  '  .ys-comp-sources-panel::-webkit-scrollbar-thumb{background:#475569;}',
  '  .ys-comp-plan-title,.ys-comp-task-title,.ys-comp-queue-title,.ys-comp-artifact-name,.ys-comp-form-title{color:#e2e8f0;}',
  '  .ys-comp-plan-step,.ys-comp-task-item,.ys-comp-queue-item{color:#cbd5e1;}',
  '  .ys-comp-form-option{background:#0f172a;border-color:#334155;color:#cbd5e1;}',
  '  .ys-comp-form-option.ys-selected{background:#312e81;border-color:#6366f1;color:#e0e7ff;}',
  '  .ys-comp-reasoning-toggle{background:#1e293b;color:#94a3b8;}',
  '  .ys-comp-reasoning-content{color:#94a3b8;background:#0f172a;}',
  '  .ys-comp-webpreview-bar{background:#1e293b;border-color:#334155;}',
  '  .ys-comp-webpreview-btn{background:#334155;color:#cbd5e1;border-color:#475569;}',
  '  .ys-comp-artifact-icon{background:#334155;}',
  '  .ys-comp-artifact-type{color:#94a3b8;}',
  '  .ys-chart-title{color:#e2e8f0;}',
  '  .ys-comp-error{background:#1c1917;border-color:#44403c;color:#fca5a5;}',
  '  .ys-comp-checkpoint{background:#052e16;border-color:#166534;color:#86efac;}',
  '  .ys-comp-citation{background:#1e1b4b;border-color:#4c1d95;color:#c4b5fd;}',
  '  .ys-comp-citation-link{color:#818cf8;}',
  '  .ys-comp-citation-link:hover{color:#a5b4fc;}',
  '  .ys-md-inline-code{background:#334155;color:#fb7185;}',
  '  .ys-md-link{color:#818cf8;}',
  '}',
].join('\n');
