import type { WidgetThemePreset } from '../types';

export const WIDGET_THEME_PRESETS = [
  'yellowstorm-modern',
  'public-service-light',
  'pold-magenta',
  'neutral-blue',
  'high-contrast-light',
  'dark-modern',
] as const satisfies readonly WidgetThemePreset[];

export const WIDGET_THEME_COLORS: Record<WidgetThemePreset, Record<string, string>> = {
  'yellowstorm-modern': {
    primary: '#4f46e5',
    primaryForeground: '#ffffff',
    headerBackground: '#4338ca',
    headerForeground: '#ffffff',
    launcherBackground: '#4f46e5',
    launcherForeground: '#ffffff',
    background: '#eef2ff',
    surface: '#ffffff',
    surfaceAlt: '#f8fafc',
    text: '#172033',
    mutedText: '#667085',
    border: '#d0d5dd',
    userBubble: '#4f46e5',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    assistantBubbleText: '#172033',
    focusRing: '#2563eb',
  },
  'public-service-light': {
    primary: '#1d4ed8',
    primaryForeground: '#ffffff',
    headerBackground: '#ffffff',
    headerForeground: '#172033',
    launcherBackground: '#1d4ed8',
    launcherForeground: '#ffffff',
    background: '#f6f8fb',
    surface: '#ffffff',
    surfaceAlt: '#eef2f7',
    text: '#172033',
    mutedText: '#5f6b7a',
    border: '#cbd5e1',
    userBubble: '#1d4ed8',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    assistantBubbleText: '#172033',
    focusRing: '#1d4ed8',
  },
  'pold-magenta': {
    primary: '#b0005a',
    primaryForeground: '#ffffff',
    headerBackground: '#b0005a',
    headerForeground: '#ffffff',
    launcherBackground: '#b0005a',
    launcherForeground: '#ffffff',
    background: '#fff5fa',
    surface: '#ffffff',
    surfaceAlt: '#fde7f2',
    text: '#201425',
    mutedText: '#6f5b68',
    border: '#e7c7d8',
    userBubble: '#b0005a',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    assistantBubbleText: '#201425',
    focusRing: '#b0005a',
  },
  'neutral-blue': {
    primary: '#0f5f8f',
    primaryForeground: '#ffffff',
    headerBackground: '#0f5f8f',
    headerForeground: '#ffffff',
    launcherBackground: '#0f5f8f',
    launcherForeground: '#ffffff',
    background: '#f2f7fb',
    surface: '#ffffff',
    surfaceAlt: '#e9f2f8',
    text: '#172033',
    mutedText: '#5d6b78',
    border: '#c8d8e3',
    userBubble: '#0f5f8f',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    assistantBubbleText: '#172033',
    focusRing: '#0f5f8f',
  },
  'high-contrast-light': {
    primary: '#000000',
    primaryForeground: '#ffffff',
    headerBackground: '#000000',
    headerForeground: '#ffffff',
    launcherBackground: '#000000',
    launcherForeground: '#ffffff',
    background: '#ffffff',
    surface: '#ffffff',
    surfaceAlt: '#f2f2f2',
    text: '#000000',
    mutedText: '#333333',
    border: '#000000',
    userBubble: '#000000',
    userBubbleText: '#ffffff',
    assistantBubble: '#ffffff',
    assistantBubbleText: '#000000',
    focusRing: '#ffbf00',
  },
  'dark-modern': {
    primary: '#8b5cf6',
    primaryForeground: '#ffffff',
    headerBackground: '#111827',
    headerForeground: '#ffffff',
    launcherBackground: '#8b5cf6',
    launcherForeground: '#ffffff',
    background: '#0f172a',
    surface: '#111827',
    surfaceAlt: '#1f2937',
    text: '#f8fafc',
    mutedText: '#cbd5e1',
    border: '#334155',
    userBubble: '#8b5cf6',
    userBubbleText: '#ffffff',
    assistantBubble: '#1f2937',
    assistantBubbleText: '#f8fafc',
    focusRing: '#a78bfa',
  },
};
