const WIDGET_CHAT_API_URL = '__YELLOWSTORM_CHAT_API_URL__';
const WIDGET_TITLE = 'YellowStorm AI Support';

const WIDGET_STYLES = [
  '@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap");',
  '',
  '#ys-widget-root{position:fixed;right:20px;bottom:20px;z-index:99999;font-family:"Inter",system-ui,-apple-system,sans-serif;pointer-events:none;}',
  '#ys-widget-root *{box-sizing:border-box;pointer-events:auto;}',
  '',
  '#ys-widget-toggle{width:60px;height:60px;border:none;border-radius:50%;background:linear-gradient(135deg,#0f172a,#334155);color:#fff;cursor:pointer;box-shadow:0 8px 32px rgba(15,23,42,.4),0 2px 8px rgba(15,23,42,.2);font-size:0;transition:transform .2s cubic-bezier(.4,0,.2,1),box-shadow .2s ease;position:relative;overflow:visible;display:flex;align-items:center;justify-content:center;}',
  '#ys-widget-toggle::before{content:"\\1F5E8";font-size:26px;transition:transform .3s cubic-bezier(.4,0,.2,1);}',
  '#ys-widget-toggle::after{content:"";position:absolute;inset:-6px;border-radius:50%;border:2px solid rgba(15,23,42,.15);animation:ys-ring 2.5s ease-in-out infinite;pointer-events:none;}',
  '#ys-widget-toggle:hover{transform:scale(1.08);box-shadow:0 12px 40px rgba(15,23,42,.45),0 4px 12px rgba(15,23,42,.25);}',
  '#ys-widget-toggle:hover::before{transform:rotate(15deg) scale(1.1);}',
  '#ys-widget-toggle.ys-active{transform:rotate(90deg) scale(1.08);}',
  '#ys-widget-toggle.ys-active::before{content:"\\2715";font-size:20px;}',
  '#ys-widget-toggle.ys-active::after{animation:none;border-color:transparent;}',
  '',
  '#ys-widget-badge{position:absolute;top:-4px;right:-4px;min-width:20px;height:20px;border-radius:10px;background:#ef4444;color:#fff;font-size:11px;font-weight:700;line-height:20px;text-align:center;padding:0 6px;transform:scale(0);transition:transform .25s cubic-bezier(.4,0,.2,1);pointer-events:none;}',
  '#ys-widget-badge.ys-visible{transform:scale(1);}',
  '',
  '#ys-widget-panel{position:absolute;right:0;bottom:76px;width:400px;max-width:calc(100vw - 24px);height:640px;max-height:calc(100vh - 96px);border-radius:20px;overflow:hidden;background:#fff;box-shadow:0 32px 64px rgba(0,0,0,.18),0 8px 24px rgba(0,0,0,.12);display:flex;flex-direction:column;opacity:0;transform:translateY(16px) scale(.97);pointer-events:none;transition:opacity .25s cubic-bezier(.4,0,.2,1),transform .25s cubic-bezier(.4,0,.2,1);}',
  '#ys-widget-panel.ys-open{opacity:1;transform:translateY(0) scale(1);pointer-events:auto;}',
  '',
  '#ys-widget-header{height:64px;flex-shrink:0;display:flex;align-items:center;justify-content:space-between;padding:0 16px;background:linear-gradient(135deg,#0f172a,#1e293b);color:#fff;}',
  '#ys-widget-header-left{display:flex;align-items:center;gap:12px;}',
  '#ys-widget-avatar{width:36px;height:36px;border-radius:12px;background:linear-gradient(135deg,#6366f1,#8b5cf6);display:flex;align-items:center;justify-content:center;font-size:16px;font-weight:700;flex-shrink:0;}',
  '#ys-widget-title-wrap{display:flex;flex-direction:column;gap:2px;}',
  '#ys-widget-title{font-weight:600;font-size:14px;line-height:1.2;letter-spacing:-.01em;}',
  '#ys-widget-subtitle{font-size:11px;opacity:.6;display:flex;align-items:center;gap:5px;}',
  '#ys-widget-status-dot{width:6px;height:6px;border-radius:50%;background:#22c55e;flex-shrink:0;}',
  '#ys-widget-close{background:rgba(255,255,255,.1);color:#fff;border:none;width:32px;height:32px;border-radius:10px;font-size:18px;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:background .15s ease;line-height:1;}',
  '#ys-widget-close:hover{background:rgba(255,255,255,.2);}',
  '',
  '#ys-widget-body{display:flex;flex-direction:column;flex:1;min-height:0;background:#f8fafc;}',
  '#ys-widget-messages{flex:1;overflow-y:auto;padding:16px;display:flex;flex-direction:column;gap:12px;scroll-behavior:smooth;}',
  '#ys-widget-messages::-webkit-scrollbar{width:4px;}',
  '#ys-widget-messages::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:2px;}',
  '#ys-widget-messages::-webkit-scrollbar-track{background:transparent;}',
  '',
  '.ys-msg-wrap{display:flex;flex-direction:column;gap:4px;max-width:88%;animation:ys-msg-in .3s cubic-bezier(.4,0,.2,1);}',
  '.ys-msg-wrap.ys-right{align-self:flex-end;align-items:flex-end;}',
  '.ys-msg-wrap.ys-left{align-self:flex-start;align-items:flex-start;}',
  '.ys-msg{padding:10px 14px;border-radius:16px;font-size:13.5px;line-height:1.45;white-space:pre-wrap;word-break:break-word;}',
  '.ys-msg-user{background:linear-gradient(135deg,#0f172a,#1e293b);color:#fff;border-bottom-right-radius:6px;}',
  '.ys-msg-assistant{background:#fff;color:#1e293b;border:1px solid #e2e8f0;border-bottom-left-radius:6px;box-shadow:0 1px 2px rgba(0,0,0,.04);}',
  '.ys-msg-time{font-size:10px;color:#94a3b8;padding:0 4px;}',
  '.ys-msg-error{background:#fef2f2;color:#991b1b;border:1px solid #fecaca;border-radius:10px;padding:8px 12px;font-size:12px;align-self:center;}',
  '',
  '.ys-typing{display:flex;align-items:center;gap:4px;padding:12px 14px;background:#fff;border:1px solid #e2e8f0;border-radius:16px;border-bottom-left-radius:6px;max-width:60px;}',
  '.ys-typing-dot{width:7px;height:7px;border-radius:50%;background:#94a3b8;animation:ys-bounce 1.4s ease-in-out infinite;}',
  '.ys-typing-dot:nth-child(2){animation-delay:.2s;}',
  '.ys-typing-dot:nth-child(3){animation-delay:.4s;}',
  '',
  '#ys-widget-form{display:flex;gap:8px;padding:12px 12px 14px;border-top:1px solid #e2e8f0;background:#fff;flex-shrink:0;}',
  '#ys-widget-input{flex:1;height:42px;border:1.5px solid #e2e8f0;border-radius:12px;padding:0 14px;font-size:13.5px;font-family:inherit;outline:none;background:#f8fafc;transition:border-color .15s ease,box-shadow .15s ease,background .15s ease;color:#1e293b;}',
  '#ys-widget-input::placeholder{color:#94a3b8;}',
  '#ys-widget-input:focus{border-color:#6366f1;box-shadow:0 0 0 3px rgba(99,102,241,.12);background:#fff;}',
  '#ys-widget-send{width:42px;height:42px;border:none;border-radius:12px;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;transition:opacity .15s ease,transform .15s ease;box-shadow:0 2px 8px rgba(99,102,241,.3);}',
  '#ys-widget-send svg{width:18px;height:18px;}',
  '#ys-widget-send:hover{opacity:.9;transform:scale(1.04);}',
  '#ys-widget-send:disabled{opacity:.4;cursor:not-allowed;transform:none;}',
  '#ys-widget-powered{flex-shrink:0;text-align:center;padding:4px 0 8px;font-size:10px;color:#cbd5e1;}',
  '',
  '@keyframes ys-ring{0%,100%{transform:scale(1);opacity:1;}50%{transform:scale(1.25);opacity:0;}}',
  '@keyframes ys-msg-in{from{opacity:0;transform:translateY(8px);}to{opacity:1;transform:translateY(0);}}',
  '@keyframes ys-bounce{0%,60%,100%{transform:translateY(0);}30%{transform:translateY(-6px);}}',
].join('\n');

const WIDGET_HTML = [
  '<button id="ys-widget-toggle" type="button" aria-label="Open chat">',
  '  <span id="ys-widget-badge" role="status" aria-live="polite"></span>',
  '</button>',
  '<div id="ys-widget-panel" role="dialog" aria-label="YellowStorm Chat Widget">',
  '  <div id="ys-widget-header">',
  '    <div id="ys-widget-header-left">',
  '      <div id="ys-widget-avatar" aria-hidden="true">YS</div>',
  '      <div id="ys-widget-title-wrap">',
  '        <span id="ys-widget-title">' + WIDGET_TITLE + '</span>',
  '        <span id="ys-widget-subtitle"><span id="ys-widget-status-dot"></span>Online</span>',
  '      </div>',
  '    </div>',
  '    <button id="ys-widget-close" type="button" aria-label="Close chat">✕</button>',
  '  </div>',
  '  <div id="ys-widget-body">',
  '    <div id="ys-widget-messages"></div>',
  '  </div>',
  '  <form id="ys-widget-form">',
  '    <input id="ys-widget-input" type="text" placeholder="Type your message..." autocomplete="off" aria-label="Message input" />',
  '    <button id="ys-widget-send" type="submit" aria-label="Send message"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg></button>',
  '  </form>',
  '  <div id="ys-widget-powered">Powered by YellowStorm</div>',
  '</div>',
].join('\n');

const WIDGET_SCRIPT = [
  'var root=document.createElement("div");root.id="ys-widget-root";',
  'root.innerHTML=[\'<style>\',' + JSON.stringify(WIDGET_STYLES) + ',\'</style>\',' + JSON.stringify(WIDGET_HTML) + '].join("\\n");',
  'document.body.appendChild(root);',
  '',
  'var panel=document.getElementById("ys-widget-panel");',
  'var toggle=document.getElementById("ys-widget-toggle");',
  'var closeBtn=document.getElementById("ys-widget-close");',
  'var messagesEl=document.getElementById("ys-widget-messages");',
  'var form=document.getElementById("ys-widget-form");',
  'var input=document.getElementById("ys-widget-input");',
  'var sendBtn=document.getElementById("ys-widget-send");',
  'var badge=document.getElementById("ys-widget-badge");',
  'var isOpen=false;var requestInFlight=false;var unreadCount=0;',
  '',
  'function formatTime(){var d=new Date();var h=d.getHours();var m=d.getMinutes();return(h<10?"0":"")+h+":"+(m<10?"0":"")+m;}',
  '',
  'function setOpen(nextOpen){isOpen=nextOpen;panel.classList.toggle("ys-open",isOpen);toggle.classList.toggle("ys-active",isOpen);toggle.setAttribute("aria-expanded",String(isOpen));if(isOpen){unreadCount=0;badge.classList.remove("ys-visible");badge.textContent="";input.focus();}}',
  '',
  'function scrollToBottom(){messagesEl.scrollTop=messagesEl.scrollHeight;}',
  '',
  'function addMessage(role,text,isError){var wrap=document.createElement("div");wrap.className="ys-msg-wrap "+(role==="user"?"ys-right":"ys-left");if(isError){var err=document.createElement("div");err.className="ys-msg-error";err.textContent=text;messagesEl.appendChild(err);}else{var msg=document.createElement("div");msg.className="ys-msg "+(role==="user"?"ys-msg-user":"ys-msg-assistant");msg.textContent=text;var time=document.createElement("span");time.className="ys-msg-time";time.textContent=formatTime();wrap.appendChild(msg);wrap.appendChild(time);messagesEl.appendChild(wrap);}scrollToBottom();if(!isOpen&&role==="assistant"&&!isError){unreadCount++;badge.textContent=unreadCount>9?"9+":String(unreadCount);badge.classList.add("ys-visible");}}',
  '',
  'function showTyping(show){requestInFlight=show;sendBtn.disabled=show;var existing=messagesEl.querySelector(".ys-typing");if(show&&!existing){var typing=document.createElement("div");typing.className="ys-typing";typing.setAttribute("aria-label","AI is typing");typing.innerHTML=\'<span class="ys-typing-dot"></span><span class="ys-typing-dot"></span><span class="ys-typing-dot"></span>\';messagesEl.appendChild(typing);scrollToBottom();}if(!show&&existing){existing.remove();}}',
  '',
  'async function sendMessage(text){addMessage("user",text);showTyping(true);try{var response=await fetch(CHAT_API_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({agentId:AGENT_ID,message:text})});if(!response.ok)throw new Error("HTTP "+response.status);var data=await response.json();var reply=data&&data.data&&typeof data.data.reply==="string"?data.data.reply:data&&typeof data.reply==="string"?data.reply:"I received your message.";addMessage("assistant",reply);}catch(err){addMessage("assistant","Sorry, something went wrong. Please try again.",true);}finally{showTyping(false);}}',
  '',
  'addMessage("assistant","Hello! How can I help you today?");',
  '',
  'toggle.addEventListener("click",function(){setOpen(!isOpen);});',
  'closeBtn.addEventListener("click",function(){setOpen(false);});',
  'document.addEventListener("keydown",function(e){if(e.key==="Escape"&&isOpen)setOpen(false);});',
  'form.addEventListener("submit",function(e){e.preventDefault();if(requestInFlight)return;var value=input.value.trim();if(!value)return;input.value="";sendMessage(value);});',
].join('\n');

export function buildWidgetSnippet(agentId: string): string {
  const config = `var AGENT_ID="${agentId}";var CHAT_API_URL="${WIDGET_CHAT_API_URL}";var TITLE="${WIDGET_TITLE}";`;
  return [
    '<script>',
    '(function(){',
    config,
    WIDGET_SCRIPT,
    '})();',
    '</script>',
  ].join('\n');
}
