import type { AgentDeploymentSettings, AgentWidgetSettings } from '../types';

export const DEFAULT_WIDGET_SETTINGS = {
  version: 1,
  appSourceName: 'Website widget',
  identity: {
    organizationName: '',
    assistantTitle: 'Assistant demarches',
    assistantSubtitle: 'Service d aide en ligne',
    avatarMode: 'initials',
    avatarInitials: 'AD',
  },
  launcher: {
    label: 'Aide en ligne',
    mobileLabel: 'Aide',
    variant: 'pill',
    position: 'bottom-right',
    showUnreadBadge: true,
    showIntroTooltip: false,
    introTooltipText: 'Besoin d aide pour vos demarches ?',
  },
  theme: {
    preset: 'public-service-light',
    customEnabled: false,
    colors: {},
    radius: 'lg',
    density: 'comfortable',
  },
  layout: {
    desktopWidth: 400,
    desktopHeight: 620,
  },
  content: {
    greetingTitle: 'Bonjour, comment puis-je vous aider ?',
    greetingBody: 'Je peux vous aider a trouver une information, comprendre une demarche ou vous orienter vers le bon service.',
    privacyNotice: 'Ne saisissez pas de donnees sensibles dans le chat.',
    footerText: 'Propulse par YellowStorm',
    footerLinks: [],
    suggestions: [
      {
        id: 'find-procedure',
        label: 'Trouver une demarche',
        prompt: 'Je cherche une demarche administrative. Pouvez-vous m orienter ?',
        enabled: true,
        sortOrder: 10,
      },
      {
        id: 'contact-service',
        label: 'Contacter un service',
        prompt: 'Je souhaite contacter le bon service. Pouvez-vous m aider ?',
        enabled: true,
        sortOrder: 20,
      },
      {
        id: 'practical-info',
        label: 'Informations pratiques',
        prompt: 'Je cherche des informations pratiques : horaires, acces ou contacts.',
        enabled: true,
        sortOrder: 30,
      },
    ],
  },
  labels: {
    inputPlaceholder: 'Votre question...',
    sendButton: 'Envoyer le message',
    closeButton: 'Fermer le chat',
    optionsButton: 'Options du chat',
    newConversation: 'Nouvelle conversation',
    copyTranscript: 'Copier la conversation',
    copyMessage: 'Copier le message',
    downloadTranscript: 'Telecharger la conversation',
    transcriptCopied: 'Conversation copiee',
    messageCopied: 'Message copie',
    transcriptDownloaded: 'Conversation telechargee',
    emptyTranscript: 'Aucune conversation a copier',
    errorGeneric: 'Desole, une erreur est survenue. Veuillez reessayer.',
    errorReset: 'Impossible de demarrer une nouvelle conversation.',
    typing: 'L assistant redige une reponse',
    sourcesUsedSingular: '1 source utilisee',
    sourcesUsedPlural: '{count} sources utilisees',
    choiceSubmit: 'Envoyer',
    choiceDismiss: 'Passer cette question',
    choiceDismissed: 'Question ignoree',
    choiceDismissMessage: 'Je prefere ne pas repondre a cette question.',
    choiceOtherLabel: 'Autre reponse',
    choiceSendError: 'Impossible d envoyer ce choix. Reessayez.',
    choiceWaitForReply: 'Attendez la fin de la reponse en cours.',
    accessibilitySettings: 'Reglages accessibilite',
    accessibilitySettingsTitle: 'Reglages accessibilite',
    accessibilitySettingsDescription: 'Choisissez un profil d affichage. Ce choix est enregistre uniquement dans ce navigateur.',
    accessibilityProfile: 'Profil accessibilite',
    accessibilityClose: 'Fermer les reglages accessibilite',
    accessibilityReset: 'Utiliser le profil par defaut',
    microphoneStart: 'Demarrer la saisie vocale',
    microphoneUnavailable: 'La saisie vocale n est pas disponible dans ce navigateur',
    microphoneListening: 'Ecoute en cours. La saisie vocale est traitee par votre navigateur.',
    readAloud: 'Lire a voix haute',
    stopReading: 'Arreter la lecture',
    readAloudUnavailable: 'La lecture a voix haute n est pas disponible dans ce navigateur',
  },
  behavior: {
    defaultOpen: false,
    persistVisitorId: true,
    allowTranscriptCopy: true,
    allowTranscriptDownload: true,
    allowNewConversation: true,
    requirePrivacyNotice: true,
  },
  accessibility: {
    enabled: true, showSettingsButton: true, defaultProfile: 'standard',
    availableProfiles: ['standard', 'low-vision', 'high-contrast-light', 'high-contrast-dark', 'cognitive-comfort', 'motor-assistance', 'low-stimulation'],
    allowTextResize: true, allowLineSpacing: true, allowLetterSpacing: true, allowFontSelection: true, allowLinkUnderlining: true, allowHighContrast: true, allowCustomAccessibleColors: false, allowMotionControl: true, allowLargeTargets: true, allowSimplifiedMode: true, allowEnhancedFocus: true,
    enforceMinimumContrast: true, minimumTextContrastRatio: 4.5, minimumUiContrastRatio: 3,
    voiceInput: { enabled: true, language: 'auto', continuous: false, interimResults: true, autoPunctuation: true, autoSend: false, stopAfterSilenceMs: 3000, retainAudio: false },
    readAloud: { enabled: true, autoPlay: false, defaultRate: 1, highlightCurrentSentence: true, readSourcesByDefault: false },
    screenReader: { announceStreaming: true, announcementIntervalMs: 1500, announceChoices: true, announceSources: false, announceCompletion: true },
    keyboard: { shortcutsEnabled: true, microphoneShortcut: 'Alt+Shift+M', accessibilityPanelShortcut: 'Alt+Shift+A', readAloudShortcut: 'Alt+Shift+R' },
  },
} satisfies AgentWidgetSettings;

export function mergeWidgetSettings(value?: Partial<AgentWidgetSettings>): AgentWidgetSettings {
  return {
    ...DEFAULT_WIDGET_SETTINGS,
    ...value,
    identity: { ...DEFAULT_WIDGET_SETTINGS.identity, ...value?.identity },
    launcher: { ...DEFAULT_WIDGET_SETTINGS.launcher, ...value?.launcher },
    theme: {
      ...DEFAULT_WIDGET_SETTINGS.theme,
      ...value?.theme,
      colors: { ...DEFAULT_WIDGET_SETTINGS.theme.colors, ...(value?.theme?.colors ?? {}) },
    },
    layout: { ...DEFAULT_WIDGET_SETTINGS.layout, ...value?.layout },
    content: { ...DEFAULT_WIDGET_SETTINGS.content, ...value?.content },
    labels: { ...DEFAULT_WIDGET_SETTINGS.labels, ...value?.labels },
    behavior: { ...DEFAULT_WIDGET_SETTINGS.behavior, ...value?.behavior },
    accessibility: {
      ...DEFAULT_WIDGET_SETTINGS.accessibility, ...value?.accessibility,
      voiceInput: { ...DEFAULT_WIDGET_SETTINGS.accessibility.voiceInput, ...value?.accessibility?.voiceInput, autoSend: false, retainAudio: false },
      readAloud: { ...DEFAULT_WIDGET_SETTINGS.accessibility.readAloud, ...value?.accessibility?.readAloud, autoPlay: false },
      screenReader: { ...DEFAULT_WIDGET_SETTINGS.accessibility.screenReader, ...value?.accessibility?.screenReader },
      keyboard: { ...DEFAULT_WIDGET_SETTINGS.accessibility.keyboard, ...value?.accessibility?.keyboard },
    },
  };
}

export const DEFAULT_DEPLOYMENT_SETTINGS = {
  embedEnabled: false,
  restEnabled: false,
  widget: DEFAULT_WIDGET_SETTINGS,
} satisfies AgentDeploymentSettings;
