import { PlaybookFlowExecutionAdvisorMapper } from './playbook-flow-execution-advisor.mapper';

describe('PlaybookFlowExecutionAdvisorMapper', () => {
  const mapper = new PlaybookFlowExecutionAdvisorMapper();

  it('maps grpc judge results into the frontend-aligned shape', () => {
    const result = mapper.mapGrpcJudgeResult({
      accuracy_score: 81,
      completeness_score: 79,
      result_matching_score: 74,
      overall_score: 78,
      confidence: 0.66,
      tool_usage_score: 71,
      relevance_score: 72,
      specificity_score: 73,
      format_compliance_score: 74,
      evidence_grounding_score: 75,
      handoff_readiness_score: 76,
      hitl_appropriateness_score: 77,
      determinism_score: 78,
      step_optimization_priority: 79,
      playbook_optimization_priority: 80,
      risk_severity: 'high',
      blocking_issue_count: 2,
      downstream_impact_level: 'medium',
      recommended_action: 'optimize_step',
      expected_result_source: 'node_field',
      expected_result_type: 'semantic_description',
      expected_result_matched: true,
      expected_result_reason: 'Matched.',
      missing_facts: ['missing'],
      incoherences: ['issue'],
      unsupported_claims: ['claim'],
      handoff_risks: ['risk'],
      rewrite_hints: ['hint'],
      tool_selection_issues: ['selection'],
      missing_tool_calls: ['missing tool'],
      redundant_tool_calls: ['redundant'],
      tool_output_use_issues: ['output use'],
      tool_sequencing_issues: ['sequence'],
      tool_usage_strengths: ['strength'],
      tool_usage_recommendation: 'Use tools better.',
      safe_auto_fix_type: 'optimize_step',
      recommendation: 'update_current_playbook',
      reason: 'done',
    });

    expect(result).toMatchObject({
      accuracyScore: 81,
      completenessScore: 79,
      resultMatchingScore: 74,
      overallScore: 78,
      confidence: 0.66,
      toolUsageScore: 71,
      formatComplianceScore: 74,
      riskSeverity: 'high',
      blockingIssueCount: 2,
      downstreamImpactLevel: 'medium',
      recommendedAction: 'optimize_step',
      availableActions: { optimizeStep: true, optimizePlaybook: true },
      expectedResultSource: 'node_field',
      expectedResultType: 'semantic_description',
      expectedResultMatched: true,
      expectedResultReason: 'Matched.',
      toolUsageRecommendation: 'Use tools better.',
      safeAutoFixType: 'optimize_step',
      recommendation: 'update_current_playbook',
      reason: 'done',
    });
  });

  it('maps llm judge json and clamps invalid scores', () => {
    const result = mapper.mapLlmJudgeResult(JSON.stringify({
      accuracyScore: 120,
      completenessScore: -5,
      resultMatchingScore: 74.4,
      overallScore: 78,
      confidence: 66,
      toolUsageScore: 71,
      relevanceScore: 105,
      specificityScore: 20,
      formatComplianceScore: 64,
      evidenceGroundingScore: 82,
      handoffReadinessScore: 50,
      hitlAppropriatenessScore: 90,
      determinismScore: 45,
      stepOptimizationPriority: 91,
      playbookOptimizationPriority: 30,
      riskSeverity: 'critical',
      blockingIssueCount: 3,
      downstreamImpactLevel: 'high',
      recommendedAction: 'improve_output_contract',
      expectedResultSource: 'unexpected',
      expectedResultType: 'semantic_description',
      expectedResultMatched: true,
      expectedResultReason: 'Matched.',
      missingFacts: ['missing'],
      recommendation: 'update_current_playbook',
      reason: 'done',
    }));

    expect(result).toMatchObject({
      accuracyScore: 100,
      completenessScore: 0,
      resultMatchingScore: 74,
      expectedResultSource: 'none',
      expectedResultType: 'semantic_description',
      recommendation: 'update_current_playbook',
      relevanceScore: 100,
      riskSeverity: 'critical',
      downstreamImpactLevel: 'high',
      recommendedAction: 'improve_output_contract',
    });
  });
});
