"""Legacy shim: delegation helpers now live in delegation_factory (next to AgentDelegationFactory)."""

from src.smart_rag.agents.factories.delegation_factory import (
    _append_capability_aware_file_context,
    _append_connector_repo_context,
    _append_current_attachment_context,
    _append_run_code_guidance,
    _append_selected_workspace_context,
    _append_workspace_document_context,
    _attach_mcp_search_state,
    _attach_mcp_toolset,
    _build_connector_repo_fixed_params,
    _build_mcp_context_note,
    _build_workspace_document_context,
    _extract_original_expected_output,
    _get_connector_repo,
    _get_enabled_tool_config,
    _get_team_skills,
    _inject_connector_repo_into_bindings,
    _is_tool_enabled,
    _resolve_temperature,
    create_agent_for_delegation,
    create_regular_agent,
    create_search_agent_with_tools,
    create_standard_agent_with_tools,
    document_tree_injection_enabled,
    get_enhanced_prompt,
    merge_skills,
    prepare_agent_data,
)
