services:
  vectorstore-api:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    env_file:
      - .env
    ports:
      - '3013:8005'
    restart: always

  celery-flower:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    entrypoint: bash -c "celery -A worker.celery_app flower --loglevel=INFO --address=0.0.0.0 --port=5555 --basic-auth=$USERNAME:$PASSWORD"
    command: ""
    ports:
      - '5555:5555'
    restart: always
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-default:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info --heartbeat-interval=60 -P eventlet -Q default -c 6 -n default@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-image-index:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q image-indexation -c 6 -n image-indexation@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-text-index:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q text-indexation -c 6 -n text-indexation@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-smart-chunking:
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q smart-chunking -c 6 -n smart-chunking@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-indexation:
    restart: always
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info --heartbeat-interval=60 -P eventlet -Q azure-search.low-priority -c 6 -n azure-search-low-priority@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-chatbot:
    restart: always
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q metachatbot-api-default -c 5 -n metachatbot-api-default@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-data-processing:
    restart: always
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q data-processing.batch -c 1 -n data-processing.batch@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-conformity:
    restart: always
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q conformity.default -c 1 -n conformity.default@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared
  celery-worker-conversion:
    restart: always
    image: yscrmetachatbot001.azurecr.io/codex-vectorstore-api:1.0.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P eventlet -Q conversion -c 2 -n conversion@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

volumes:
  celery-data:
