/**
 * API Configuration
 */

export const API_CONFIG = {
  baseURL: process.env.NODE_ENV === 'development'
    ? import.meta.env.VITE_API_URL || 'http://localhost:3000/api/v1'
    : 'MY_APP_VITE_API_URL',
  timeout: 30000,
  withCredentials: true, // Required for HTTP-only cookies (refresh token)
} as const;

/**
 * Prod: env.sh replaces this literal with a real origin (e.g. https://poc.back.yellowmind.ai).
 * Do not compare against another copy of the same placeholder — sed replaces both sides.
 * Prefer this over nginx /socket.io/ proxy: the image runs as `metafront` and cannot
 * sed /etc/nginx/conf.d/default.conf (Permission denied → container exit).
 */
const SOCKET_BASE_INJECTED = 'MY_APP_SOCKET_BASE_URL';

function isHttpUrl(value: string): boolean {
  return /^https?:\/\//i.test(value);
}

/** Origin for Socket.IO (app-runtime, browser-session, whatsapp). */
export function getSocketBaseUrl(): string {
  if (process.env.NODE_ENV === 'development') {
    const devOverride = import.meta.env.VITE_SOCKET_BASE_URL?.trim();
    if (devOverride && isHttpUrl(devOverride)) {
      return new URL(devOverride).origin;
    }
  } else if (isHttpUrl(SOCKET_BASE_INJECTED)) {
    return new URL(SOCKET_BASE_INJECTED).origin;
  }

  const base = API_CONFIG.baseURL;
  if (isHttpUrl(base)) {
    try {
      return new URL(base).origin;
    } catch {
      /* fall through */
    }
  }

  return typeof window !== 'undefined' ? window.location.origin : 'http://localhost:3000';
}

export const AUTH_STORAGE_KEYS = {
  accessToken: 'yellostorm_access_token',
  user: 'yellostorm_user',
} as const;

export const API_ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    resendVerificationPublic: '/auth/resend-verification-public',
    sessions: '/auth/sessions',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    oauthProviders: '/auth/providers',
    oauthExchange: '/auth/providers/exchange',
  },
  users: {
    me: '/users/me',
    completeProfile: '/users/me/complete-profile',
    search: '/users/search',
    directory: '/users/directory',
  },
  health: {
    check: '/health',
    live: '/health/live',
    ready: '/health/ready',
    admin: '/admin/health',
    history: '/admin/health/history',
    stats: '/admin/health/stats',
    postgres: '/admin/health/postgres',
  },
  system: {
    maintenance: '/experimental/system/maintenance',
    registration: '/experimental/system/registration',
    appearance: '/experimental/system/appearance',
    appearanceLogos: '/experimental/system/appearance/logos',
    appearanceLogo: (id: string) => `/experimental/system/appearance/logos/${id}`,
    appearanceLogoFile: (id: string) => `/experimental/system/appearance/logos/${id}/file`,
    cors: '/experimental/system/cors',
    features: '/experimental/system/features',
    emailLogo: '/experimental/system/email-logo',
  },
  workspaceUploadSettings: {
    current: '/workspace-settings/uploads',
  },
  adminWorkspaceUploadSettings: {
    base: '/admin/workspace-settings/uploads',
  },
  workspaceArtifacts: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/artifacts`,
    configuration: (workspaceId: string) => `/workspaces/${workspaceId}/artifacts/configuration`,
    decisionFlows: (workspaceId: string) => `/workspaces/${workspaceId}/artifacts/decision-flows`,
    byId: (workspaceId: string, artifactId: string) => `/workspaces/${workspaceId}/artifacts/${artifactId}`,
    clone: (workspaceId: string, artifactId: string) => `/workspaces/${workspaceId}/artifacts/${artifactId}/clone`,
    retry: (workspaceId: string, artifactId: string) => `/workspaces/${workspaceId}/artifacts/${artifactId}/retry`,
  },
  adminWorkspaceEvidenceSearchSettings: {
    base: '/admin/workspace-settings/evidence-search',
    connectors: '/admin/workspace-settings/evidence-search/connectors',
  },
  adminWorkspaceTransformationSettings: {
    base: '/admin/workspace-settings/transformations',
    agents: '/admin/workspace-settings/transformations/agents',
  },
  adminConversationSettings: {
    base: '/admin/conversation-settings',
    agents: '/admin/conversation-settings/agents',
    sensitiveTextRedaction: '/admin/conversation-settings/sensitive-text-redaction',
  },
  adminPlaybookSettings: {
    base: '/admin/playbook-settings',
    plannerAgents: '/admin/playbook-settings/planner-agents',
  },
  adminGuardrails: {
    base: '/admin/guardrails',
  },
  adminEvaluationSettings: {
    base: '/admin/evaluation-settings',
  },
  adminWorkyWhatsAppSystemBot: {
    base: '/admin/worky/whatsapp-system-bot',
    expectedPhone: '/admin/worky/whatsapp-system-bot/expected-phone',
    connect: '/admin/worky/whatsapp-system-bot/connect',
    pairing: (sessionId: string) => `/admin/worky/whatsapp-system-bot/${sessionId}/pairing`,
    reconnect: (sessionId: string) => `/admin/worky/whatsapp-system-bot/${sessionId}/reconnect`,
    session: (sessionId: string) => `/admin/worky/whatsapp-system-bot/${sessionId}`,
  },
  adminTeamAutoBuilder: {
    config: '/admin/teams/auto-builder-config',
  },
  usage: {
    status: '/usage/status',
    plan: '/usage/plan',
    history: '/usage/history',
    plans: '/usage/plans',
    plansAll: '/usage/plans/all',
    planById: (id: string) => `/usage/plans/${id}`,
  },
  notifications: {
    stream: '/notifications/stream',
    list: '/notifications',
    unreadCount: '/notifications/unread/count',
    markRead: '/notifications/read',
    markAllRead: '/notifications/read-all',
  },
  workspaces: {
    list: '/workspaces',
    create: '/workspaces',
    byId: (id: string) => `/workspaces/${id}`,
    byAlias: (alias: string) => `/workspaces/alias/${alias}`,
    sharedWithMe: '/workspaces/shared-with-me',
    public: '/workspaces/public',
    visibility: (id: string) => `/workspaces/${id}/visibility`,
  },
  workspaceShares: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/shares`,
    byId: (workspaceId: string, shareId: string) =>
      `/workspaces/${workspaceId}/shares/${shareId}`,
  },
  workspaceDocuments: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    byId: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}`,
    downloadUrl: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}/download-url`,
    reindex: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}/reindex`,
    rename: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}/rename`,
    graphData: (workspaceId: string) =>
      `/workspaces/${workspaceId}/graph`,
    bulkDelete: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    deleteAll: (workspaceId: string) => `/workspaces/${workspaceId}/documents/all`,
    // Upload endpoints
    upload: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    uploadUrl: (workspaceId: string) => `/workspaces/${workspaceId}/documents/upload-url`,
    confirm: (workspaceId: string) => `/workspaces/${workspaceId}/documents/confirm`,
    bulk: (workspaceId: string) => `/workspaces/${workspaceId}/documents/bulk`,
    bulkProgress: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}/progress`,
    bulkComplete: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}/complete`,
    bulkSession: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}`,
    // Link (website URL) endpoints
    link: (workspaceId: string) => `/workspaces/${workspaceId}/documents/link`,
    validateUrl: (workspaceId: string) => `/workspaces/${workspaceId}/documents/validate-url`,
    links: (workspaceId: string) => `/workspaces/${workspaceId}/documents/links`,
    checkUrls: (workspaceId: string) => `/workspaces/${workspaceId}/documents/check-urls`,
    crawl: (workspaceId: string) => `/workspaces/${workspaceId}/documents/crawl`,
  },
  workspaceSettings: {
    list: '/workspace-settings',
    create: '/workspace-settings',
    byId: (id: string) => `/workspace-settings/${id}`,
    templates: '/workspace-settings/templates',
  },
  models: {
    list: '/models',
    byId: (id: string) => `/models/${id}`,
    byChef: (chefSlug: string) => `/models/chef/${chefSlug}`,
  },
  conversations: {
    list: '/conversations',
    create: '/conversations',
    createGoverned: '/conversations/governed',
    byId: (id: string) => `/conversations/${id}`,
    branch: (id: string) => `/conversations/${id}/branches`,
    playbookHandoffs: (id: string) => `/conversations/${id}/playbook-handoffs`,
    join: (id: string) => `/conversations/${id}/join`,
    taggedAgents: (id: string) => `/conversations/${id}/tagged-agents`,
    messages: (id: string) => `/conversations/${id}/messages`,
    activeStream: (id: string) => `/conversations/${id}/active-stream`,
    messageById: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}`,
    toolResult: (convId: string, msgId: string, componentId: string) => `/conversations/${convId}/messages/${msgId}/tools/${componentId}/result`,
    feedback: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/feedback`,
    rerunReliabilityEvaluation: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/reliability-evaluation/rerun`,
    regenerate: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/regenerate`,
    stop: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/stop`,
    frontendLatency: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/latency/frontend-paint`,
    branches: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/branches`,
    report: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/report`,
    markMentionSeen: (conversationId: string, messageId: string) => `/conversations/${conversationId}/messages/${messageId}/mention-seen`,
    workspaceDocuments: (id: string) => `/conversations/${id}/workspace-documents`,
    fileUploadUrl: (convId: string) => `/conversations/${convId}/files/upload-url`,
    fileUpload: (convId: string) => `/conversations/${convId}/files/upload`,
    fileConfirm: (convId: string) => `/conversations/${convId}/files/confirm`,
    fileDelete: (convId: string, docId: string) => `/conversations/${convId}/files/${docId}`,
    stream: '/conversations/stream',
    artifactUrl: (conversationId: string, messageId: string, artifactId: string) =>
      `/conversations/${conversationId}/messages/${messageId}/artifacts/${artifactId}/url`,
    citationUrl: (conversationId: string, messageId: string) =>
      `/conversations/${conversationId}/messages/${messageId}/citations/url`,
    composerSuggestions: '/conversations/suggestions',
    settings: '/conversations/settings',
    // Share endpoints
    shares: (id: string) => `/conversations/${id}/shares`,
    share: (id: string) => `/conversations/${id}/share`,
    revokeShare: (convId: string, shareId: string) => `/conversations/${convId}/share/${shareId}`,
    publicShare: (accessToken: string) => `/conversations/shared/${accessToken}`,
  },
  analytics: {
    users: '/experimental/analytics/users',
    usage: '/experimental/analytics/usage',
    conversations: '/experimental/analytics/conversations',
    quality: '/experimental/analytics/quality',
    summary: '/experimental/analytics/summary',
  },
  governance: {
    availableScopes: '/governance/me/available-scopes',
    programs: '/governance/programs',
    program: (programId: string) => `/governance/programs/${programId}`,
    scopes: (programId: string) => `/governance/programs/${programId}/scopes`,
    scope: (programId: string, scopeId: string) => `/governance/programs/${programId}/scopes/${scopeId}`,
    scopeOverview: (programId: string, scopeId: string) => `/governance/programs/${programId}/scopes/${scopeId}/overview`,
    scopeAudience: (programId: string, scopeId: string) => `/governance/programs/${programId}/scopes/${scopeId}/audience`,
    documents: (programId: string) => `/governance/programs/${programId}/documents`,
    document: (programId: string, documentId: string) => `/governance/programs/${programId}/documents/${documentId}`,
    documentEvents: (programId: string, documentId: string) => `/governance/programs/${programId}/documents/${documentId}/events`,
    documentValidity: (programId: string, documentId: string) => `/governance/programs/${programId}/documents/${documentId}/validity`,
    documentAction: (programId: string, documentId: string, action: string) => `/governance/programs/${programId}/documents/${documentId}/${action}`,
    temporalCandidates: (programId: string, documentId: string) => `/governance/programs/${programId}/documents/${documentId}/temporal-candidates`,
    temporalAnalysis: (programId: string, documentId: string) => `/governance/programs/${programId}/documents/${documentId}/temporal-analysis`,
    temporalCandidateDecision: (programId: string, documentId: string, recordId: string) => `/governance/programs/${programId}/documents/${documentId}/temporal-candidates/${recordId}/decision`,
    workspaceBindings: (programId: string) => `/governance/programs/${programId}/workspace-bindings`,
    workspaceBinding: (programId: string, bindingId: string) => `/governance/programs/${programId}/workspace-bindings/${bindingId}`,
    reconcileWorkspaceBinding: (programId: string, bindingId: string) => `/governance/programs/${programId}/workspace-bindings/${bindingId}/reconcile`,
    reconciliationRuns: (programId: string, bindingId: string) => `/governance/programs/${programId}/workspace-bindings/${bindingId}/reconciliation-runs`,
    reconciliationRun: (programId: string, bindingId: string, runId: string) => `/governance/programs/${programId}/workspace-bindings/${bindingId}/reconciliation-runs/${runId}`,
    resumeReconciliationRun: (programId: string, bindingId: string, runId: string) => `/governance/programs/${programId}/workspace-bindings/${bindingId}/reconciliation-runs/${runId}/resume`,
    memberships: (programId: string) => `/governance/programs/${programId}/memberships`,
    membership: (programId: string, membershipId: string) => `/governance/programs/${programId}/memberships/${membershipId}`,
    deployments: (programId: string) => `/governance/programs/${programId}/deployments`,
    deployment: (deploymentId: string) => `/governance/deployments/${deploymentId}`,
    revisions: (deploymentId: string) => `/governance/deployments/${deploymentId}/revisions`,
    revision: (deploymentId: string, revisionId: string) => `/governance/deployments/${deploymentId}/revisions/${revisionId}`,
    resolveContext: (deploymentId: string) => `/governance/deployments/${deploymentId}/resolve-context`,
    readiness: (deploymentId: string) => `/governance/deployments/${deploymentId}/readiness`,
    dryRuns: (deploymentId: string) => `/governance/deployments/${deploymentId}/dry-runs`,
    dryRun: (dryRunId: string) => `/governance/dry-runs/${dryRunId}`,
    dryRunResult: (dryRunId: string) => `/governance/dry-runs/${dryRunId}/result`,
    publish: (deploymentId: string) => `/governance/deployments/${deploymentId}/publish`,
    rollback: (deploymentId: string) => `/governance/deployments/${deploymentId}/rollback`,
    suspend: (deploymentId: string) => `/governance/deployments/${deploymentId}/suspend`,
    metrics: (programId: string) => `/governance/programs/${programId}/metrics`,
    knowledgeHealth: (programId: string) => `/governance/programs/${programId}/knowledge/health-summary`,
    knowledgeRefresh: (programId: string) => `/governance/programs/${programId}/knowledge/refresh`,
    knowledgeAlerts: (programId: string) => `/governance/programs/${programId}/knowledge/alerts`,
    knowledgeAlertAcknowledge: (programId: string, alertId: string) => `/governance/programs/${programId}/knowledge/alerts/${alertId}/acknowledge`,
    knowledgeRecommendations: (programId: string) => `/governance/programs/${programId}/knowledge/recommendations`,
    knowledgeRecommendationAction: (programId: string, recommendationId: string, action: 'accept' | 'reject' | 'apply') => `/governance/programs/${programId}/knowledge/recommendations/${recommendationId}/${action}`,
    metadataCandidates: (programId: string) => `/governance/programs/${programId}/knowledge/metadata-candidates`,
    metadataCandidateAction: (programId: string, candidateId: string, action: 'accept' | 'reject') => `/governance/programs/${programId}/knowledge/metadata-candidates/${candidateId}/${action}`,
  },
  roles: {
    base: '/admin/roles',
    active: '/admin/roles/active',
    byId: (id: string) => `/admin/roles/${id}`,
    assign: '/admin/roles/assign',
    unassign: '/admin/roles/unassign',
    userRoles: (userId: string) => `/admin/roles/user/${userId}`,
  },
  adminUsers: {
    base: '/admin/users',
    byId: (id: string) => `/admin/users/${id}`,
    suspend: (id: string) => `/admin/users/${id}/suspend`,
    activate: (id: string) => `/admin/users/${id}/activate`,
    approveRegistration: (id: string) => `/admin/users/${id}/approve-registration`,
    rejectRegistration: (id: string) => `/admin/users/${id}/reject-registration`,
    assignPlan: (id: string) => `/admin/users/${id}/assign-plan`,
  },
  auditLogs: {
    base: '/admin/audit-logs',
    actions: '/admin/audit-logs/actions',
    features: '/admin/audit-logs/features',
  },
  logs: {
    base: '/admin/logs',
    levels: '/admin/logs/levels',
    contexts: '/admin/logs/contexts',
    counts: '/admin/logs/counts',
  },
  reports: {
    base: '/reports',
    byId: (id: string) => `/reports/${id}`,
    status: (id: string) => `/reports/${id}/status`,
  },
  adminTools: {
    list: '/admin/tools',
    byId: (id: string) => `/admin/tools/${id}`,
  },
  adminToolCategories: {
    list: '/admin/tool-categories',
    byId: (id: string) => `/admin/tool-categories/${id}`,
  },
  adminSkills: {
    list: '/admin/skills',
    byId: (id: string) => `/admin/skills/${id}`,
    export: (id: string) => `/admin/skills/${id}/export`,
    import: '/admin/skills/import',
  },
  adminSkillCategories: {
    list: '/admin/skill-categories',
    byId: (id: string) => `/admin/skill-categories/${id}`,
  },
  adminConnectors: {
    list: '/admin/connectors',
    byId: (id: string) => `/admin/connectors/${id}`,
    inspect: '/admin/connectors/inspect',
    importMcp: '/admin/connectors/import-mcp',
    authorize: (id: string) => `/admin/connectors/${id}/authorize`,
    inspectConnector: (id: string) => `/admin/connectors/${id}/inspect`,
    oauthAuthorize: (appKey: string) => `/admin/connectors/oauth/${appKey}/authorize`,
    oauthStatus: (appKey: string) => `/admin/connectors/oauth/${appKey}/status`,
    oauthDisconnect: (appKey: string) => `/admin/connectors/oauth/${appKey}/connection`,
  },
  semanticModels: {
    base: '/semantic-models',
    byId: (id: string) => `/semantic-models/${id}`,
    clone: (id: string) => `/semantic-models/${id}/clone`,
    overview: (id: string) => `/semantic-models/${id}/overview`,
    graph: (id: string) => `/semantic-models/${id}/graph`,
    operations: (id: string) => `/semantic-models/${id}/graph/operations`,
    validate: (id: string) => `/semantic-models/${id}/graph/validate`,
    generateOntology: (id: string) => `/semantic-models/${id}/ontology/generate`,
    evidenceSearch: (id: string) => `/semantic-models/${id}/evidence/search`,
    mappingProposals: (id: string) => `/semantic-models/${id}/mapping/proposals`,
    mappingProposalJobs: (id: string) => `/semantic-models/${id}/mapping/proposals/jobs`,
    mappingProposalJob: (id: string, jobId: string) => `/semantic-models/${id}/mapping/proposals/jobs/${jobId}`,
    mappingPlanApply: (id: string, jobId: string) => `/semantic-models/${id}/mapping/jobs/${jobId}/apply`,
    ageGraph: (id: string) => `/semantic-models/${id}/age-graph`,
    ageGraphRebuild: (id: string) => `/semantic-models/${id}/age-graph/rebuild`,
    ageGraphOperations: (id: string) => `/semantic-models/${id}/age-graph/operations`,
    corpus: (id: string) => `/semantic-models/${id}/corpus`,
    builds: (id: string) => `/semantic-models/${id}/builds`,
    latestBuild: (id: string) => `/semantic-models/${id}/builds/latest`,
    build: (id: string, buildId: string) => `/semantic-models/${id}/builds/${buildId}`,
    bindings: (id: string) => `/semantic-models/${id}/bindings`,
    binding: (id: string, bindingId: string) => `/semantic-models/${id}/bindings/${bindingId}`,
    workspaces: (id: string) => `/semantic-models/${id}/workspaces`,
    workspace: (id: string, workspaceId: string) => `/semantic-models/${id}/workspaces/${workspaceId}`,
    versions: (id: string) => `/semantic-models/${id}/versions`,
    publish: (id: string) => `/semantic-models/${id}/versions/publish`,
    restore: (id: string, versionId: string) => `/semantic-models/${id}/versions/${versionId}/restore`,
    workspaceDefault: (workspaceId: string) => `/workspaces/${workspaceId}/semantic-model`,
    workspaceModels: (workspaceId: string) => `/workspaces/${workspaceId}/semantic-models`,
    ensureWorkspaceDefault: (workspaceId: string) => `/workspaces/${workspaceId}/semantic-model/ensure`,
    shares: (id: string) => `/semantic-models/${id}/shares`,
    share: (id: string, targetUserId: string) => `/semantic-models/${id}/shares/${targetUserId}`,
  },
  adminCatalogTransfer: {
    exportConnectors: '/admin/catalog-transfer/connectors/export',
    exportSkills: '/admin/catalog-transfer/skills/export',
    import: '/admin/catalog-transfer/import',
  },
  adminConnectorCategories: {
    list: '/admin/connector-categories',
    byId: (id: string) => `/admin/connector-categories/${id}`,
  },
  connectors: {
    list: '/connectors',
    byId: (id: string) => `/connectors/${id}`,
    credentials: (connectorId: string) => `/connectors/${connectorId}/credentials`,
    credential: (id: string) => `/connectors/credentials/${id}`,
    validateCredential: (id: string) => `/connectors/credentials/${id}/validate`,
    repositories: '/connectors/repositories',
  },
  adminPlaybookPrompts: {
    list: '/admin/playbook-prompts',
    import: '/admin/playbook-prompts/import',
    byKey: (key: string) => `/admin/playbook-prompts/${encodeURIComponent(key)}`,
  },
  adminPlaybookNodeTemplates: {
    list: '/playbook-flow-templates',
    import: '/playbook-flow-templates/import',
    byId: (id: string) => `/playbook-flow-templates/${id}`,
  },
  playbookNodeTemplates: {
    list: '/playbook-flow-templates',
  },
  adminAgentTypes: {
    list: '/admin/agent-types',
    byId: (id: string) => `/admin/agent-types/${id}`,
    prompts: (id: string) => `/admin/agent-types/${id}/prompts`,
    promptByModel: (id: string, modelId: string) => `/admin/agent-types/${id}/prompts/${encodeURIComponent(modelId)}`,
  },
  adminAgents: {
    list: '/admin/agents',
    byId: (id: string) => `/admin/agents/${id}`,
  },
  agentTypes: {
    active: '/agent-types/active',
  },
  memoryCards: {
    base: '/memory-cards',
  },
  agents: {
    list: '/agents',
    all: '/agents/all',
    humainResolve: '/agents/humain/resolve',
    byId: (id: string) => `/agents/${id}`,
    telegramIntegration: (id: string) => `/agents/${id}/telegram-integration`,
    whatsappIntegration: (id: string) => `/agents/${id}/whatsapp-integration`,
    whatsappEvents: (id: string) => `/agents/${id}/whatsapp-integration/events`,
    whatsappAutoRecover: (id: string) => `/agents/${id}/whatsapp-integration/auto-recover`,
    whatsappEnabled: (id: string) => `/agents/${id}/whatsapp-integration/enabled`,
    whatsappConnect: (id: string) => `/agents/${id}/whatsapp-integration/connect`,
    whatsappPairing: (id: string, sessionId: string) =>
      `/agents/${id}/whatsapp-integration/${sessionId}/pairing`,
    whatsappReconnect: (id: string, sessionId: string) =>
      `/agents/${id}/whatsapp-integration/${sessionId}/reconnect`,
    whatsappSession: (id: string, sessionId: string) =>
      `/agents/${id}/whatsapp-integration/${sessionId}`,
    a2aPublish: (id: string) => `/agents/${id}/a2a/publish`,
    a2aRotateKey: (id: string) => `/agents/${id}/a2a/rotate-key`,
    a2aRevoke: (id: string) => `/agents/${id}/a2a/revoke`,
    shares: (id: string) => `/agents/${id}/shares`,
    shareById: (id: string, shareId: string) => `/agents/${id}/shares/${shareId}`,
    unshare: (id: string) => `/agents/${id}/unshare`,
  },
  widgetTokens: {
    create: (agentId: string) => `/agents/${agentId}/widget-tokens`,
    list: (agentId: string) => `/agents/${agentId}/widget-tokens`,
    update: (agentId: string, tokenId: string) => `/agents/${agentId}/widget-tokens/${tokenId}`,
    revoke: (agentId: string, tokenId: string) => `/agents/${agentId}/widget-tokens/${tokenId}`,
  },
  adminWidgetTokens: {
    create: (agentId: string) => `/admin/agents/${agentId}/widget-tokens`,
  },
  teams: {
    list: '/teams',
    all: '/teams/all',
    byId: (id: string) => `/teams/${id}`,
    generate: '/teams/generate',
    hierarchy: (id: string) => `/teams/${id}/hierarchy`,
    shares: (id: string) => `/teams/${id}/shares`,
    shareById: (id: string, shareId: string) => `/teams/${id}/shares/${shareId}`,
    unshare: (id: string) => `/teams/${id}/unshare`,
  },
  userGroups: {
    list: '/user-groups',
    byId: (id: string) => `/user-groups/${id}`,
    members: (id: string) => `/user-groups/${id}/members`,
    memberById: (id: string, userId: string) => `/user-groups/${id}/members/${userId}`,
  },
  tools: {
    active: '/tools/active',
  },
  skills: {
    active: '/skills/active',
  },
  playbooks: {
    list: '/playbooks',
    generate: '/playbooks/generate',
    rewritePrompt: '/playbooks/rewrite-prompt',
    byId: (id: string) => `/playbooks/${id}`,
    inputContract: (id: string) => `/playbooks/${id}/input-contract`,
    integrationLink: (id: string) => `/playbooks/${id}/integration-link`,
    publicExecute: (token: string) => `/playbooks/public/${token}/execute`,
    execute: (id: string) => `/playbooks/${id}/execute`,
    resume: (id: string) => `/playbooks/${id}/resume`,
    stop: (id: string) => `/playbooks/${id}/stop`,
    executions: (id: string) => `/playbooks/${id}/executions`,
    execution: (id: string, execId: string) => `/playbooks/${id}/executions/${execId}`,
    hitlPolicy: (id: string) => `/playbooks/${id}/hitl/policy`,
    hitlBlockers: (id: string) => `/playbooks/${id}/hitl/blockers`,
    hitlBlocker: (id: string, blockerId: string) => `/playbooks/${id}/hitl/blockers/${blockerId}`,
    hitlBlockerNormalize: (id: string) => `/playbooks/${id}/hitl/blockers/normalize`,
    hitlNodePolicy: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/hitl/policy`,
    hitlMemories: (id: string) => `/playbooks/${id}/hitl/memories`,
    hitlMemory: (id: string, memoryId: string) => `/playbooks/${id}/hitl/memories/${memoryId}`,
    hitlEvents: (executionId: string) => `/executions/${executionId}/hitl/events`,
    hitlPending: (executionId: string) => `/executions/${executionId}/hitl/pending`,
    hitlResume: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/resume`,
    hitlDisableBlocker: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/disable-blocker`,
    deleteAllExecutions: (id: string) => `/playbooks/${id}/executions`,
    deleteExecution: (id: string, execId: string) => `/playbooks/${id}/executions/${execId}`,
    deleteStepExecution: (id: string, execId: string, taskId: string, stepExecutionId: string) =>
      `/playbooks/${id}/executions/${execId}/tasks/${taskId}/step-executions/${stepExecutionId}`,
    validateReplay: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/validate-replay`,
    replays: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replays`,
    activateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/activate`,
    updateReplayFormatGuide: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/format-guide`,
    updateReplayLabel: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    deleteReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    grabOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    outputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    intentDesign: (id: string) => `/playbooks/${id}/intent-design`,
    assistantTurns: (id: string) => `/playbooks/${id}/assistant/turns`,
    assistantAttachments: (id: string) => `/playbooks/${id}/assistant/attachments`,
    assistantAttachmentConfirm: (id: string, attachmentId: string) => `/playbooks/${id}/assistant/attachments/${attachmentId}/confirm`,
    assistantMessages: (id: string) => `/playbooks/${id}/assistant/messages`,
    intentTraces: (id: string) => `/playbooks/${id}/intent-traces`,
    intentConstructions: (id: string) => `/playbooks/${id}/intent-constructions`,
    intentConstruction: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}`,
    intentConstructionStream: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/stream`,
    intentConstructionCommit: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/commit`,
    intentConstructionApply: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/apply`,
    intentConstructionDiscard: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/discard`,
    intentConstructionRevert: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/revert`,
    cancelIntentConstruction: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/cancel`,
    advisorRemediationConstructions: (id: string) => `/playbooks/${id}/advisor-remediation-constructions`,
    advisorScriptPreview: (id: string) => `/playbooks/${id}/advisor-remediations/script-preview`,
    advisorScriptApply: (id: string) => `/playbooks/${id}/advisor-remediations/script-apply`,
    nodeAdvisor: (id: string, taskId: string) => `/playbooks/${id}/nodes/${taskId}/advisor`,
    skipStep: (id: string) => `/playbooks/${id}/steps/skip`,
    rerunStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/rerun-step`,
    runFromStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/run-from-step`,
    resumeFromStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/resume-from-step`,
    stream: '/playbooks/stream',
    design: (id: string) => `/playbooks/${id}/design`,
    designOperations: (id: string) => `/playbooks/${id}/design-operations`,
    designOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}`,
    cancelDesignOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}/cancel`,
    designMessages: (id: string) => `/playbooks/${id}/design-messages`,
    clearDesignMessages: (id: string) => `/playbooks/${id}/design-messages`,
    revertDesign: (id: string, msgId: string) => `/playbooks/${id}/design-messages/${msgId}/revert`,
    shares: (id: string) => `/playbooks/${id}/shares`,
    share: (id: string, shareId: string) => `/playbooks/${id}/shares/${shareId}`,
    cloneShare: (id: string) => `/playbooks/${id}/clone-share`,
    clone: (id: string) => `/playbooks/${id}/clone`,
    schedule: (id: string) => `/playbooks/${id}/schedule`,
    triggers: (id: string) => `/playbooks/${id}/triggers`,
    triggerSchedule: (id: string) => `/playbooks/${id}/triggers/schedule`,
    triggerMail: (id: string) => `/playbooks/${id}/triggers/mail`,
    syncMailSubscription: (id: string) => `/playbooks/${id}/triggers/mail/sync-subscription`,
    favorite: (id: string) => `/playbooks/${id}/favorite`,
    evaluationExecutions: (id: string) => `/playbooks/${id}/evaluations`,
    evaluationBaseline: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline`,
    evaluationBaselineFromExecution: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline/from-execution`,
    evaluationBaselineFromCurrentExecution: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline/from-current-execution`,
    repeatability: (id: string) => `/playbooks/${id}/repeatability`,
    repeatabilityTask: (id: string, taskId: string) => `/playbooks/${id}/repeatability/tasks/${taskId}`,
    bulkDelete: '/playbooks/bulk-delete',
    activeExecutions: '/playbooks/active-executions',
  },
  connectedApps: {
    list: '/connected-apps',
    connections: '/connected-apps/connections',
    mailboxCapability: '/connected-apps/mailbox-capability',
    authorize: (appKey: string) => `/connected-apps/${appKey}/authorize`,
    disconnect: (appKey: string) => `/connected-apps/${appKey}`,
  },
  adminConnectedApps: {
    list: '/admin/connected-apps',
    byId: (id: string) => `/admin/connected-apps/${id}`,
  },
  adminAuthProviders: {
    list: '/admin/auth-providers',
    byId: (id: string) => `/admin/auth-providers/${id}`,
    classic: '/admin/auth-providers/classic',
  },
  adminModels: {
    list: '/admin/models',
    byId: (id: string) => `/admin/models/${id}`,
    setDefault: (id: string) => `/admin/models/${id}/set-default`,
    clearDefault: (id: string) => `/admin/models/${id}/clear-default`,
    setConversationV2Default: (id: string) => `/admin/models/${id}/set-conversation-v2-default`,
    clearConversationV2Default: (id: string) => `/admin/models/${id}/clear-conversation-v2-default`,
    sync: '/admin/models/sync',
    default: '/admin/models/default',
  },
  projects: {
    list: '/projects',
    create: '/projects',
    byId: (id: string) => `/projects/${id}`,
  },
  classifier: {
    folders: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/folders`,
    folderById: (id: string) => `/classifier/folders/${id}`,
    folderMove: (id: string) => `/classifier/folders/${id}/move`,
    files: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/files`,
    fileFolder: (workspaceId: string, documentId: string) =>
      `/classifier/workspaces/${workspaceId}/files/${documentId}/folder`,
    runs: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/runs`,
    runById: (id: string) => `/classifier/runs/${id}`,
    rules: '/classifier/rules',
    ruleById: (id: string) => `/classifier/rules/${id}`,
    sync: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/sync`,
  },
  evaluation: {
    datasets: '/evaluation/datasets',
    datasetById: (id: string) => `/evaluation/datasets/${id}`,
    launch: '/evaluation/launch',
    run: '/evaluation/run',
    finalize: (id: string) => `/evaluation/results/${id}/finalize`,
    results: (agentId: string) => `/evaluation/results/${agentId}`,
    resultById: (id: string) => `/evaluation/results/${id}`,
    scenarios: '/evaluation/scenarios',
    scenariosByAgent: (agentId: string) => `/evaluation/scenarios/agent/${agentId}`,
    scenarioById: (id: string) => `/evaluation/scenarios/${id}`,
  },
  playbookFlows: {
    list: '/playbooks',
    byId: (id: string) => `/playbooks/${id}`,
    inputContract: (id: string) => `/playbooks/${id}/input-contract`,
    delta: (id: string) => `/playbooks/${id}/delta`,
    generate: '/playbooks/generate',
    rewritePrompt: '/playbooks/rewrite-prompt',
    design: (id: string) => `/playbooks/${id}/design`,
    designOperations: (id: string) => `/playbooks/${id}/design-operations`,
    designOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}`,
    cancelDesignOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}/cancel`,
    clone: (id: string) => `/playbooks/${id}/clone`,
    execute: (id: string) => `/playbooks/${id}/executions`,
    executions: (id: string) => `/playbooks/${id}/executions`,
    executionDetail: (executionId: string) => `/executions/${executionId}`,
    executionArtifactAccess: (executionId: string, artifactId: string) => `/executions/${executionId}/artifacts/${artifactId}/access`,
    artifactContent: '/executions/artifacts/content',
    hitlPolicy: (id: string) => `/playbooks/${id}/hitl/policy`,
    hitlBlockers: (id: string) => `/playbooks/${id}/hitl/blockers`,
    hitlBlocker: (id: string, blockerId: string) => `/playbooks/${id}/hitl/blockers/${blockerId}`,
    hitlBlockerNormalize: (id: string) => `/playbooks/${id}/hitl/blockers/normalize`,
    hitlNodePolicy: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/hitl/policy`,
    hitlMemories: (id: string) => `/playbooks/${id}/hitl/memories`,
    hitlMemory: (id: string, memoryId: string) => `/playbooks/${id}/hitl/memories/${memoryId}`,
    hitlEvents: (executionId: string) => `/executions/${executionId}/hitl/events`,
    hitlPending: (executionId: string) => `/executions/${executionId}/hitl/pending`,
    hitlResume: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/resume`,
    hitlDisableBlocker: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/disable-blocker`,
    runAdvisorEvaluation: (executionId: string, taskId: string) => `/executions/${executionId}/tasks/${taskId}/advisor-evaluation`,
    cancelExecution: (executionId: string) => `/executions/${executionId}/cancel`,
    resumeApproval: (executionId: string) => `/executions/${executionId}/resume-approval`,
    deleteExecution: (executionId: string) => `/executions/${executionId}`,
    deleteAllExecutions: (flowId: string) => `/playbooks/${flowId}/executions`,
    routerDecisions: (executionId: string) => `/executions/${executionId}/router-decisions`,
    traceReplay: (executionId: string) => `/executions/${executionId}/trace-replay`,
    reExecute: (executionId: string) => `/executions/${executionId}/re-execute`,
    validateReplay: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/validate-replay`,
    replays: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replays`,
    activateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/activate`,
    updateReplayFormatGuide: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/format-guide`,
    updateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    deleteReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    replayReports: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replay-reports`,
    outputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    grabOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    updateOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    deleteOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    nodeAdvisor: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/advisor`,
    evaluations: (flowId: string) => `/playbooks/${flowId}/evaluations`,
    evaluationBaseline: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline`,
    evaluationBaselineFromExecution: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline/from-execution`,
    evaluationBaselineFromCurrentExecution: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline/from-current-execution`,
    deleteEvaluationBaseline: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline`,
    repeatability: (flowId: string) => `/playbooks/${flowId}/repeatability`,
    repeatabilityTask: (flowId: string, taskId: string) => `/playbooks/${flowId}/repeatability/tasks/${taskId}`,
    triggers: (flowId: string) => `/playbooks/${flowId}/triggers`,
    triggerSchedule: (flowId: string) => `/playbooks/${flowId}/trigger/schedule`,
    triggerMail: (flowId: string) => `/playbooks/${flowId}/trigger/mail`,
    syncMailSubscription: (flowId: string) => `/playbooks/${flowId}/trigger/mail/subscription`,
  },
  playbookFlowTemplates: {
    list: '/playbook-flow-templates',
    enabled: '/playbook-flow-templates/enabled',
    nodeKinds: '/playbook-flow-templates/node-kinds',
    byId: (id: string) => `/playbook-flow-templates/${id}`,
  },
  worky: {
    streams: '/worky/streams',
    streamById: (id: string) => `/worky/streams/${id}`,
    streamEvents: (id: string) => `/worky/streams/${id}/events`,
    streamMessages: (id: string) => `/worky/streams/${id}/messages`,
    streamBoard: (id: string) => `/worky/streams/${id}/board`,
    streamDelete: (id: string) => `/worky/streams/${id}/delete`,
    respondInteraction: (id: string) => `/worky/interactions/${id}/respond`,
    taskById: (id: string) => `/worky/tasks/${id}`,
    taskMove: (id: string) => `/worky/tasks/${id}/move`,
    taskPause: (id: string) => `/worky/tasks/${id}/pause`,
    taskResume: (id: string) => `/worky/tasks/${id}/resume`,
    taskCancel: (id: string) => `/worky/tasks/${id}/cancel`,
    taskReview: (id: string) => `/worky/tasks/${id}/review`,
    taskResults: (id: string) => `/worky/tasks/${id}/results`,
    taskResultContent: (id: string) => `/worky/tasks/${id}/result-content`,
    taskHumanUpdate: (id: string) => `/worky/tasks/${id}/human-update`,
    streamBudget: (id: string) => `/worky/streams/${id}/budget`,
    executionReport: (id: string) => `/worky/streams/${id}/execution-report`,
    streamTraces: (id: string) => `/worky/streams/${id}/traces`,
    memoryProposals: '/worky/memory/proposals',
    memoryEntries: '/worky/memory/entries',
    memoryProposalConfirm: (id: string) => `/worky/memory/proposals/${id}/confirm`,
    memoryProposalReject: (id: string) => `/worky/memory/proposals/${id}/reject`,
    governancePolicy: '/worky/admin/governance-policy',
    sttTranscribe: '/worky/stt/transcribe',
    ttsSpeak: '/worky/tts/speak',
    voiceSession: '/worky/voice/session',
    voiceDispatch: '/worky/voice/tool/dispatch',
    voiceStatus: '/worky/voice/tool/status',
    voiceStop: '/worky/voice/tool/stop',
    voiceListTasks: '/worky/voice/tool/list-tasks',
    voiceTaskDetails: '/worky/voice/tool/task-details',
    voiceTranscript: '/worky/voice/tool/transcript',
    voicePrompt: (streamId: string) => `/worky/voice/prompt/${streamId}`,
    whatsappIntegration: (id: string) => `/worky/streams/${id}/whatsapp-integration`,
    whatsappConnect: (id: string) => `/worky/streams/${id}/whatsapp-integration/connect`,
    whatsappPairing: (id: string, sessionId: string) =>
      `/worky/streams/${id}/whatsapp-integration/${sessionId}/pairing`,
    whatsappReconnect: (id: string, sessionId: string) =>
      `/worky/streams/${id}/whatsapp-integration/${sessionId}/reconnect`,
    whatsappSession: (id: string, sessionId: string) =>
      `/worky/streams/${id}/whatsapp-integration/${sessionId}`,
    whatsappSystemBotStatus: '/worky/whatsapp-system-bot/status',
  },
} as const;
