/**
 * API Configuration
 */

export const API_CONFIG = {
  baseURL: process.env.NODE_ENV === 'development'
    ? import.meta.env.VITE_API_URL || 'http://localhost:3000/api/v1'
    : 'MY_APP_VITE_API_URL',
  timeout: 30000,
  withCredentials: true, // Required for HTTP-only cookies (refresh token)
} as const;

export const AUTH_STORAGE_KEYS = {
  accessToken: 'yellostorm_access_token',
  user: 'yellostorm_user',
} as const;

export const API_ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    resendVerificationPublic: '/auth/resend-verification-public',
    sessions: '/auth/sessions',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    oauthProviders: '/auth/providers',
    oauthExchange: '/auth/providers/exchange',
  },
  users: {
    me: '/users/me',
    completeProfile: '/users/me/complete-profile',
    search: '/users/search',
  },
  health: {
    check: '/health',
    live: '/health/live',
    ready: '/health/ready',
    history: '/health/history',
    stats: '/health/stats',
  },
  system: {
    maintenance: '/experimental/system/maintenance',
    registration: '/experimental/system/registration',
    appearance: '/experimental/system/appearance',
  },
  adminPlaybookSettings: {
    base: '/admin/playbook-settings',
  },
  usage: {
    status: '/usage/status',
    plan: '/usage/plan',
    history: '/usage/history',
    plans: '/usage/plans',
    plansAll: '/usage/plans/all',
    planById: (id: string) => `/usage/plans/${id}`,
  },
  notifications: {
    stream: '/notifications/stream',
    list: '/notifications',
    unreadCount: '/notifications/unread/count',
    markRead: '/notifications/read',
    markAllRead: '/notifications/read-all',
  },
  workspaces: {
    list: '/workspaces',
    create: '/workspaces',
    byId: (id: string) => `/workspaces/${id}`,
    byAlias: (alias: string) => `/workspaces/alias/${alias}`,
    sharedWithMe: '/workspaces/shared-with-me',
  },
  workspaceShares: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/shares`,
    byId: (workspaceId: string, shareId: string) =>
      `/workspaces/${workspaceId}/shares/${shareId}`,
  },
  workspaceDocuments: {
    list: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    byId: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}`,
    downloadUrl: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}/download-url`,
    reindex: (workspaceId: string, docId: string) =>
      `/workspaces/${workspaceId}/documents/${docId}/reindex`,
    bulkDelete: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    deleteAll: (workspaceId: string) => `/workspaces/${workspaceId}/documents/all`,
    // Upload endpoints
    upload: (workspaceId: string) => `/workspaces/${workspaceId}/documents`,
    uploadUrl: (workspaceId: string) => `/workspaces/${workspaceId}/documents/upload-url`,
    confirm: (workspaceId: string) => `/workspaces/${workspaceId}/documents/confirm`,
    bulk: (workspaceId: string) => `/workspaces/${workspaceId}/documents/bulk`,
    bulkProgress: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}/progress`,
    bulkComplete: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}/complete`,
    bulkSession: (workspaceId: string, sessionId: string) =>
      `/workspaces/${workspaceId}/documents/bulk/${sessionId}`,
  },
  workspaceSettings: {
    list: '/workspace-settings',
    create: '/workspace-settings',
    byId: (id: string) => `/workspace-settings/${id}`,
    templates: '/workspace-settings/templates',
  },
  models: {
    list: '/models',
    byId: (id: string) => `/models/${id}`,
    byChef: (chefSlug: string) => `/models/chef/${chefSlug}`,
  },
  conversations: {
    list: '/conversations',
    create: '/conversations',
    byId: (id: string) => `/conversations/${id}`,
    join: (id: string) => `/conversations/${id}/join`,
    taggedAgents: (id: string) => `/conversations/${id}/tagged-agents`,
    messages: (id: string) => `/conversations/${id}/messages`,
    messageById: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}`,
    feedback: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/feedback`,
    regenerate: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/regenerate`,
    stop: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/stop`,
    branches: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/branches`,
    report: (convId: string, msgId: string) => `/conversations/${convId}/messages/${msgId}/report`,
    markMentionSeen: (conversationId: string, messageId: string) => `/conversations/${conversationId}/messages/${messageId}/mention-seen`,
    workspaceDocuments: (id: string) => `/conversations/${id}/workspace-documents`,
    fileUploadUrl: (convId: string) => `/conversations/${convId}/files/upload-url`,
    fileUpload: (convId: string) => `/conversations/${convId}/files/upload`,
    fileConfirm: (convId: string) => `/conversations/${convId}/files/confirm`,
    fileDelete: (convId: string, docId: string) => `/conversations/${convId}/files/${docId}`,
    stream: '/conversations/stream',
    artifactUrl: '/conversations/artifact-url',
    composerSuggestions: '/conversations/suggestions',
    // Share endpoints
    shares: (id: string) => `/conversations/${id}/shares`,
    share: (id: string) => `/conversations/${id}/share`,
    revokeShare: (convId: string, shareId: string) => `/conversations/${convId}/share/${shareId}`,
    publicShare: (accessToken: string) => `/conversations/shared/${accessToken}`,
  },
  analytics: {
    users: '/experimental/analytics/users',
    usage: '/experimental/analytics/usage',
    conversations: '/experimental/analytics/conversations',
    quality: '/experimental/analytics/quality',
    summary: '/experimental/analytics/summary',
  },
  roles: {
    base: '/admin/roles',
    active: '/admin/roles/active',
    byId: (id: string) => `/admin/roles/${id}`,
    assign: '/admin/roles/assign',
    unassign: '/admin/roles/unassign',
    userRoles: (userId: string) => `/admin/roles/user/${userId}`,
  },
  adminUsers: {
    base: '/admin/users',
    byId: (id: string) => `/admin/users/${id}`,
    suspend: (id: string) => `/admin/users/${id}/suspend`,
    activate: (id: string) => `/admin/users/${id}/activate`,
    assignPlan: (id: string) => `/admin/users/${id}/assign-plan`,
  },
  auditLogs: {
    base: '/admin/audit-logs',
    actions: '/admin/audit-logs/actions',
    features: '/admin/audit-logs/features',
  },
  logs: {
    base: '/admin/logs',
    levels: '/admin/logs/levels',
    contexts: '/admin/logs/contexts',
    counts: '/admin/logs/counts',
  },
  reports: {
    base: '/reports',
    byId: (id: string) => `/reports/${id}`,
    status: (id: string) => `/reports/${id}/status`,
  },
  adminTools: {
    list: '/admin/tools',
    byId: (id: string) => `/admin/tools/${id}`,
  },
  adminToolCategories: {
    list: '/admin/tool-categories',
    byId: (id: string) => `/admin/tool-categories/${id}`,
  },
  adminSkills: {
    list: '/admin/skills',
    byId: (id: string) => `/admin/skills/${id}`,
    import: '/admin/skills/import',
  },
  adminSkillCategories: {
    list: '/admin/skill-categories',
    byId: (id: string) => `/admin/skill-categories/${id}`,
  },
  adminConnectors: {
    list: '/admin/connectors',
    byId: (id: string) => `/admin/connectors/${id}`,
    inspect: '/admin/connectors/inspect',
    importMcp: '/admin/connectors/import-mcp',
    authorize: (id: string) => `/admin/connectors/${id}/authorize`,
    inspectConnector: (id: string) => `/admin/connectors/${id}/inspect`,
    oauthAuthorize: (appKey: string) => `/admin/connectors/oauth/${appKey}/authorize`,
    oauthStatus: (appKey: string) => `/admin/connectors/oauth/${appKey}/status`,
    oauthDisconnect: (appKey: string) => `/admin/connectors/oauth/${appKey}/connection`,
  },
  adminConnectorCategories: {
    list: '/admin/connector-categories',
    byId: (id: string) => `/admin/connector-categories/${id}`,
  },
  connectors: {
    list: '/connectors',
    byId: (id: string) => `/connectors/${id}`,
    credentials: (connectorId: string) => `/connectors/${connectorId}/credentials`,
    credential: (id: string) => `/connectors/credentials/${id}`,
    validateCredential: (id: string) => `/connectors/credentials/${id}/validate`,
    repositories: '/connectors/repositories',
  },
  adminPlaybookPrompts: {
    list: '/admin/playbook-prompts',
    byKey: (key: string) => `/admin/playbook-prompts/${encodeURIComponent(key)}`,
  },
  adminPlaybookNodeTemplates: {
    list: '/playbook-flow-templates',
    byId: (id: string) => `/playbook-flow-templates/${id}`,
  },
  playbookNodeTemplates: {
    list: '/playbook-flow-templates',
  },
  adminAgentTypes: {
    list: '/admin/agent-types',
    byId: (id: string) => `/admin/agent-types/${id}`,
    prompts: (id: string) => `/admin/agent-types/${id}/prompts`,
    promptByModel: (id: string, modelId: string) => `/admin/agent-types/${id}/prompts/${encodeURIComponent(modelId)}`,
  },
  adminAgents: {
    list: '/admin/agents',
    byId: (id: string) => `/admin/agents/${id}`,
  },
  agentTypes: {
    active: '/agent-types/active',
  },
  agents: {
    list: '/agents',
    all: '/agents/all',
    byId: (id: string) => `/agents/${id}`,
    telegramIntegration: (id: string) => `/agents/${id}/telegram-integration`,
    a2aPublish: (id: string) => `/agents/${id}/a2a/publish`,
    a2aRotateKey: (id: string) => `/agents/${id}/a2a/rotate-key`,
    a2aRevoke: (id: string) => `/agents/${id}/a2a/revoke`,
  },
  tools: {
    active: '/tools/active',
  },
  skills: {
    active: '/skills/active',
  },
  playbooks: {
    list: '/playbooks',
    generate: '/playbooks/generate',
    rewritePrompt: '/playbooks/rewrite-prompt',
    byId: (id: string) => `/playbooks/${id}`,
    integrationLink: (id: string) => `/playbooks/${id}/integration-link`,
    publicExecute: (token: string) => `/playbooks/public/${token}/execute`,
    execute: (id: string) => `/playbooks/${id}/execute`,
    resume: (id: string) => `/playbooks/${id}/resume`,
    stop: (id: string) => `/playbooks/${id}/stop`,
    executions: (id: string) => `/playbooks/${id}/executions`,
    execution: (id: string, execId: string) => `/playbooks/${id}/executions/${execId}`,
    hitlPolicy: (id: string) => `/playbooks/${id}/hitl/policy`,
    hitlBlockers: (id: string) => `/playbooks/${id}/hitl/blockers`,
    hitlBlocker: (id: string, blockerId: string) => `/playbooks/${id}/hitl/blockers/${blockerId}`,
    hitlBlockerNormalize: (id: string) => `/playbooks/${id}/hitl/blockers/normalize`,
    hitlNodePolicy: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/hitl/policy`,
    hitlMemories: (id: string) => `/playbooks/${id}/hitl/memories`,
    hitlMemory: (id: string, memoryId: string) => `/playbooks/${id}/hitl/memories/${memoryId}`,
    hitlEvents: (executionId: string) => `/executions/${executionId}/hitl/events`,
    hitlPending: (executionId: string) => `/executions/${executionId}/hitl/pending`,
    hitlResume: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/resume`,
    hitlDisableBlocker: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/disable-blocker`,
    deleteAllExecutions: (id: string) => `/playbooks/${id}/executions`,
    deleteExecution: (id: string, execId: string) => `/playbooks/${id}/executions/${execId}`,
    deleteStepExecution: (id: string, execId: string, taskId: string, stepExecutionId: string) =>
      `/playbooks/${id}/executions/${execId}/tasks/${taskId}/step-executions/${stepExecutionId}`,
    validateReplay: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/validate-replay`,
    replays: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replays`,
    activateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/activate`,
    updateReplayFormatGuide: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/format-guide`,
    updateReplayLabel: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    deleteReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    grabOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    outputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    intent: (id: string) => `/playbooks/${id}/intent`,
    intentConstructions: (id: string) => `/playbooks/${id}/intent-constructions`,
    intentConstructionStream: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/stream`,
    cancelIntentConstruction: (id: string, constructionId: string) => `/playbooks/${id}/intent-constructions/${constructionId}/cancel`,
    advisorRemediationPreview: (id: string) => `/playbooks/${id}/advisor-remediations/preview`,
    advisorScriptPreview: (id: string) => `/playbooks/${id}/advisor-remediations/script-preview`,
    advisorScriptApply: (id: string) => `/playbooks/${id}/advisor-remediations/script-apply`,
    nodeAdvisor: (id: string, taskId: string) => `/playbooks/${id}/nodes/${taskId}/advisor`,
    skipStep: (id: string) => `/playbooks/${id}/steps/skip`,
    rerunStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/rerun-step`,
    runFromStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/run-from-step`,
    resumeFromStep: (playbookId: string, executionId: string) => `/playbooks/${playbookId}/executions/${executionId}/resume-from-step`,
    stream: '/playbooks/stream',
    design: (id: string) => `/playbooks/${id}/design`,
    designOperations: (id: string) => `/playbooks/${id}/design-operations`,
    designOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}`,
    cancelDesignOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}/cancel`,
    designMessages: (id: string) => `/playbooks/${id}/design-messages`,
    revertDesign: (id: string, msgId: string) => `/playbooks/${id}/design-messages/${msgId}/revert`,
    cloneShare: (id: string) => `/playbooks/${id}/clone-share`,
    clone: (id: string) => `/playbooks/${id}/clone`,
    schedule: (id: string) => `/playbooks/${id}/schedule`,
    triggers: (id: string) => `/playbooks/${id}/triggers`,
    triggerSchedule: (id: string) => `/playbooks/${id}/triggers/schedule`,
    triggerMail: (id: string) => `/playbooks/${id}/triggers/mail`,
    syncMailSubscription: (id: string) => `/playbooks/${id}/triggers/mail/sync-subscription`,
    favorite: (id: string) => `/playbooks/${id}/favorite`,
    evaluationExecutions: (id: string) => `/playbooks/${id}/evaluations`,
    evaluationBaseline: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline`,
    evaluationBaselineFromExecution: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline/from-execution`,
    evaluationBaselineFromCurrentExecution: (id: string, taskId: string) => `/playbooks/${id}/evaluation-tasks/${taskId}/baseline/from-current-execution`,
    repeatability: (id: string) => `/playbooks/${id}/repeatability`,
    repeatabilityTask: (id: string, taskId: string) => `/playbooks/${id}/repeatability/tasks/${taskId}`,
    bulkDelete: '/playbooks/bulk-delete',
    activeExecutions: '/playbooks/active-executions',
  },
  connectedApps: {
    list: '/connected-apps',
    connections: '/connected-apps/connections',
    mailboxCapability: '/connected-apps/mailbox-capability',
    authorize: (appKey: string) => `/connected-apps/${appKey}/authorize`,
    disconnect: (appKey: string) => `/connected-apps/${appKey}`,
  },
  adminConnectedApps: {
    list: '/admin/connected-apps',
    byId: (id: string) => `/admin/connected-apps/${id}`,
  },
  adminAuthProviders: {
    list: '/admin/auth-providers',
    byId: (id: string) => `/admin/auth-providers/${id}`,
    classic: '/admin/auth-providers/classic',
  },
  adminModels: {
    list: '/admin/models',
    byId: (id: string) => `/admin/models/${id}`,
    setDefault: (id: string) => `/admin/models/${id}/set-default`,
    clearDefault: (id: string) => `/admin/models/${id}/clear-default`,
    sync: '/admin/models/sync',
    default: '/admin/models/default',
  },
  projects: {
    list: '/projects',
    create: '/projects',
    byId: (id: string) => `/projects/${id}`,
  },
  classifier: {
    folders: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/folders`,
    folderById: (id: string) => `/classifier/folders/${id}`,
    folderMove: (id: string) => `/classifier/folders/${id}/move`,
    files: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/files`,
    fileFolder: (workspaceId: string, documentId: string) =>
      `/classifier/workspaces/${workspaceId}/files/${documentId}/folder`,
    runs: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/runs`,
    runById: (id: string) => `/classifier/runs/${id}`,
    rules: '/classifier/rules',
    ruleById: (id: string) => `/classifier/rules/${id}`,
    sync: (workspaceId: string) => `/classifier/workspaces/${workspaceId}/sync`,
  },
  evaluation: {
    datasets: '/evaluation/datasets',
    datasetById: (id: string) => `/evaluation/datasets/${id}`,
    launch: '/evaluation/launch',
    run: '/evaluation/run',
    finalize: (id: string) => `/evaluation/results/${id}/finalize`,
    results: (agentId: string) => `/evaluation/results/${agentId}`,
    resultById: (id: string) => `/evaluation/results/${id}`,
    scenarios: '/evaluation/scenarios',
    scenariosByAgent: (agentId: string) => `/evaluation/scenarios/agent/${agentId}`,
    scenarioById: (id: string) => `/evaluation/scenarios/${id}`,
  },
  playbookFlows: {
    list: '/playbooks',
    byId: (id: string) => `/playbooks/${id}`,
    delta: (id: string) => `/playbooks/${id}/delta`,
    generate: '/playbooks/generate',
    rewritePrompt: '/playbooks/rewrite-prompt',
    design: (id: string) => `/playbooks/${id}/design`,
    designOperations: (id: string) => `/playbooks/${id}/design-operations`,
    designOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}`,
    cancelDesignOperation: (id: string, operationId: string) => `/playbooks/${id}/design-operations/${operationId}/cancel`,
    clone: (id: string) => `/playbooks/${id}/clone`,
    execute: (id: string) => `/playbooks/${id}/executions`,
    executions: (id: string) => `/playbooks/${id}/executions`,
    executionDetail: (executionId: string) => `/executions/${executionId}`,
    hitlPolicy: (id: string) => `/playbooks/${id}/hitl/policy`,
    hitlBlockers: (id: string) => `/playbooks/${id}/hitl/blockers`,
    hitlBlocker: (id: string, blockerId: string) => `/playbooks/${id}/hitl/blockers/${blockerId}`,
    hitlBlockerNormalize: (id: string) => `/playbooks/${id}/hitl/blockers/normalize`,
    hitlNodePolicy: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/hitl/policy`,
    hitlMemories: (id: string) => `/playbooks/${id}/hitl/memories`,
    hitlMemory: (id: string, memoryId: string) => `/playbooks/${id}/hitl/memories/${memoryId}`,
    hitlEvents: (executionId: string) => `/executions/${executionId}/hitl/events`,
    hitlPending: (executionId: string) => `/executions/${executionId}/hitl/pending`,
    hitlResume: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/resume`,
    hitlDisableBlocker: (executionId: string, interruptId: string) => `/executions/${executionId}/hitl/${interruptId}/disable-blocker`,
    runAdvisorEvaluation: (executionId: string, taskId: string) => `/executions/${executionId}/tasks/${taskId}/advisor-evaluation`,
    cancelExecution: (executionId: string) => `/executions/${executionId}/cancel`,
    resumeApproval: (executionId: string) => `/executions/${executionId}/resume-approval`,
    deleteExecution: (executionId: string) => `/executions/${executionId}`,
    deleteAllExecutions: (flowId: string) => `/playbooks/${flowId}/executions`,
    routerDecisions: (executionId: string) => `/executions/${executionId}/router-decisions`,
    traceReplay: (executionId: string) => `/executions/${executionId}/trace-replay`,
    reExecute: (executionId: string) => `/executions/${executionId}/re-execute`,
    validateReplay: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/validate-replay`,
    replays: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replays`,
    activateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/activate`,
    updateReplayFormatGuide: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}/format-guide`,
    updateReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    deleteReplay: (id: string, taskId: string, replayId: string) => `/playbooks/${id}/tasks/${taskId}/replays/${replayId}`,
    replayReports: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/replay-reports`,
    outputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    grabOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    updateOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    deleteOutputFormatTemplate: (id: string, taskId: string) => `/playbooks/${id}/tasks/${taskId}/output-format-template`,
    nodeAdvisor: (id: string, nodeId: string) => `/playbooks/${id}/nodes/${nodeId}/advisor`,
    evaluations: (flowId: string) => `/playbooks/${flowId}/evaluations`,
    evaluationBaseline: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline`,
    evaluationBaselineFromExecution: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline/from-execution`,
    evaluationBaselineFromCurrentExecution: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline/from-current-execution`,
    deleteEvaluationBaseline: (flowId: string, taskId: string) => `/playbooks/${flowId}/evaluation-tasks/${taskId}/baseline`,
    repeatability: (flowId: string) => `/playbooks/${flowId}/repeatability`,
    repeatabilityTask: (flowId: string, taskId: string) => `/playbooks/${flowId}/repeatability/tasks/${taskId}`,
    triggers: (flowId: string) => `/playbooks/${flowId}/triggers`,
    triggerSchedule: (flowId: string) => `/playbooks/${flowId}/trigger/schedule`,
    triggerMail: (flowId: string) => `/playbooks/${flowId}/trigger/mail`,
    syncMailSubscription: (flowId: string) => `/playbooks/${flowId}/trigger/mail/subscription`,
  },
  playbookFlowTemplates: {
    list: '/playbook-flow-templates',
    enabled: '/playbook-flow-templates/enabled',
    nodeKinds: '/playbook-flow-templates/node-kinds',
    byId: (id: string) => `/playbook-flow-templates/${id}`,
  },
} as const;
