services:
  yellowstorm-vectorstore-api-dev:
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    env_file:
      - .env
    ports:
      - '3413:8005'
    restart: always

  celery-flower:
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    entrypoint: bash -c "celery -A worker.celery_app flower --loglevel=INFO --address=0.0.0.0 --port=5555 --basic-auth=metachatbot:metachatbot"
    command: ""
    ports:
      - '5564:5555'
    restart: always
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-default:
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info --heartbeat-interval=60 -P prefork -Q default -c 6 -n default@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-redis-index:
    restart: always
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q redis-index -n redis-index@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-logical-indexing:
    restart: always
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q logical-indexing -c 5 -n logical-indexing"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-image-index:
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q image-indexation -c 6 -n image-indexation@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-text-index:
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    restart: always
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q text-indexation -c 6 -n text-indexation@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-indexation:
    restart: always
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info --heartbeat-interval=60 -P prefork -Q qdrant-index.low-priority -c 6 -n qdrant-index-low-priority@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-chatbot:
    restart: always
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q metachatbot-api-default -c 5 -n metachatbot-api-default@%h"
    env_file:
      - .env
    volumes:
      - celery-data:/tmp/shared

  celery-worker-conversion:
    restart: always
    image: yscrmetachatbot001.azurecr.io/yellowstorm-vectorstore:0.9.2
    user: "1000:1000"
    command: ""
    entrypoint: bash -c "celery -A worker.celery_app worker --loglevel=info -P prefork -Q conversion -c 2 -n conversion@%h"
    env_file:
       - .env
    volumes:
      - celery-data:/tmp/shared

volumes:
  celery-data:
