import { HitlBlockerRule } from '../schemas/playbook-flow-hitl.schema';

export const DEFAULT_HITL_BLOCKERS: ReadonlyArray<Omit<HitlBlockerRule, 'createdAt' | 'updatedAt'>> = [
  {
    id: 'system-missing-required-input',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'missing_required_input',
    label: 'Missing required input',
    description: 'Pause when a required input resolves to null or empty.',
    action: 'clarify',
    riskLevel: 'high',
    sensitivity: 'minimal',
    matcherType: 'input_binding',
    matcherConfig: { requiredOnly: true },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: [],
    createdBy: 'system',
  },
  {
    id: 'system-missing-document',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'missing_document',
    label: 'Missing document or file',
    description: 'Pause when the task references a document or file that is unavailable.',
    action: 'clarify',
    riskLevel: 'high',
    sensitivity: 'minimal',
    matcherType: 'deterministic',
    matcherConfig: { patterns: ['missing document', 'file not found', 'unavailable document'] },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: [],
    createdBy: 'system',
  },
  {
    id: 'system-ambiguous-instruction',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'ambiguous_instruction',
    label: 'Ambiguous instruction',
    description: 'Pause when the agent cannot choose one safe interpretation.',
    action: 'clarify',
    riskLevel: 'medium',
    sensitivity: 'balanced',
    matcherType: 'llm_judge',
    matcherConfig: { askWhenMultipleSafeInterpretationsExist: true },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: [],
    createdBy: 'system',
  },
  {
    id: 'system-destructive-action',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'destructive_action',
    label: 'Destructive action',
    description: 'Pause before deleting, overwriting, revoking, or purging data.',
    action: 'approve',
    riskLevel: 'critical',
    sensitivity: 'minimal',
    matcherType: 'tool_action',
    matcherConfig: { verbs: ['delete', 'overwrite', 'revoke', 'purge'] },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: ['delete', 'overwrite', 'revoke', 'purge'],
    createdBy: 'system',
  },
  {
    id: 'system-external-send',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'external_send',
    label: 'External send or share',
    description: 'Pause before sending, sharing, publishing, or calling an external API.',
    action: 'approve',
    riskLevel: 'critical',
    sensitivity: 'minimal',
    matcherType: 'tool_action',
    matcherConfig: { verbs: ['send', 'share', 'publish', 'webhook'] },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: ['send', 'share', 'publish', 'webhook'],
    createdBy: 'system',
  },
  {
    id: 'system-sensitive-domain',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'sensitive_domain',
    label: 'Sensitive domain',
    description: 'Pause for legal, HR, finance, security, or compliance-sensitive work.',
    action: 'approve',
    riskLevel: 'high',
    sensitivity: 'balanced',
    matcherType: 'llm_judge',
    matcherConfig: { domains: ['legal', 'hr', 'finance', 'security', 'compliance'] },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: [],
    createdBy: 'system',
  },
  {
    id: 'system-explicit-user-instruction',
    scope: 'workflow',
    nodeId: null,
    enabled: true,
    kind: 'explicit_user_instruction',
    label: 'Explicit approval instruction',
    description: 'Pause when task text says to ask, confirm, or get approval before continuing.',
    action: 'approve',
    riskLevel: 'high',
    sensitivity: 'minimal',
    matcherType: 'deterministic',
    matcherConfig: { phrases: ['ask before', 'confirm with me', 'get approval', 'do not proceed without'] },
    promptTemplate: null,
    appliesToToolNames: [],
    appliesToConnectorActions: [],
    createdBy: 'system',
  },
];
