-- =============================================================================
-- Agent — PostgreSQL schema (shareable contract)
-- =============================================================================
-- Source of truth for the `agents` data model after migration off MongoDB.
-- Other AI-related services read/join/index these tables DIRECTLY (no HTTP).
--
-- Design: docs/superpowers/specs/2026-08-04-agent-collection-postgres-migration-design.md
-- Derived from: back/src/modules/agent/schemas/agent.schema.ts (Mongoose)
--
-- CONTRACT NOTES — please review before agreeing:
--   * IDS: `agents.id` and every *_id column below hold a MongoDB ObjectId, kept
--     as its 24-char lowercase-hex string (NOT a uuid). This preserves the ids
--     already referenced by ~15 collections that stay in MongoDB. New agents are
--     created with an ObjectId-format string generated by the app.
--   * NO cross-database FKs: tool/skill/connector/workspace/user/agent_type ids
--     point at documents that REMAIN in MongoDB. Postgres cannot foreign-key
--     them, so those columns are plain `char(24)`, integrity app-enforced (same
--     guarantee as today — Mongo never enforced them either). The ONLY real FKs
--     are agent_id -> agents(id) on the junction tables (ON DELETE CASCADE).
--   * agent_type stays in MongoDB. `agent_type_id` is the opaque ref;
--     `agent_type_slug` is denormalized so external readers need no Mongo hop.
--   * guardrails / deployment_settings are non-relational config blobs -> jsonb.
--
-- Convention: snake_case identifiers, timestamptz, PostgreSQL 14+.
-- =============================================================================

-- Reusable domain for a Mongo ObjectId rendered as 24 hex chars.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'object_id') THEN
    CREATE DOMAIN object_id AS char(24)
      CHECK (VALUE ~ '^[0-9a-f]{24}$');
  END IF;
END
$$;

-- -----------------------------------------------------------------------------
-- agents  (one row per agent)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agents (
  id                            object_id    PRIMARY KEY,

  -- Identity / config
  name                          varchar(50)  NOT NULL,
  slug                          varchar(100) NOT NULL DEFAULT '',
  role                          text         NOT NULL,                    -- maxlength 50000
  description                   varchar(1000) NOT NULL DEFAULT '',
  temperature                   real         NOT NULL DEFAULT 0
                                  CHECK (temperature >= 0 AND temperature <= 1),
  llm_model                     varchar(100),                            -- optional
  reasoning_effort              varchar(50),                             -- optional, model-specific
  email                         varchar(320),                            -- optional
  instruction                   text         NOT NULL DEFAULT '',         -- maxlength 50000
  ignore_pre_prompt             boolean      NOT NULL DEFAULT false,

  -- Type (agent_types stays in MongoDB)
  agent_type_id                 object_id    NOT NULL,                    -- opaque ref -> Mongo AgentType
  agent_type_slug               varchar(100) NOT NULL DEFAULT '',         -- denormalized for external readers

  -- Temporary child agents
  enable_temporary_child_agents boolean      NOT NULL DEFAULT false,
  max_temporary_child_agents    smallint     NOT NULL DEFAULT 4
                                  CHECK (max_temporary_child_agents BETWEEN 1 AND 8),

  -- Flags
  is_default                    boolean      NOT NULL DEFAULT false,
  is_active                     boolean      NOT NULL DEFAULT true,
  is_default_for_type           boolean      NOT NULL DEFAULT false,

  -- Ownership (users stays in MongoDB)
  created_by                    object_id    NOT NULL,                    -- opaque ref -> Mongo User

  -- Non-relational config blobs
  guardrails                    jsonb        NOT NULL DEFAULT '{}'::jsonb,
  deployment_settings           jsonb        NOT NULL DEFAULT '{}'::jsonb,

  -- A2A publishing (api key itself is never stored)
  a2a_published                 boolean      NOT NULL DEFAULT false,
  a2a_agent_id                  text,
  a2a_agent_card_url            text,
  a2a_api_key_header            text,
  a2a_published_at              timestamptz,

  -- Semantic index of the agent role. Populated ONLY for humain-type agents
  -- (embedding of `name. role`, qwen3-embedding, 2560-dim). halfvec is
  -- required because pgvector's index types cap plain `vector` at 2000 dims.
  role_embedding                halfvec(2560),

  -- Timestamps (Mongoose `timestamps: true`)
  created_at                    timestamptz  NOT NULL DEFAULT now(),
  updated_at                    timestamptz  NOT NULL DEFAULT now()
);

-- Indexes ported 1:1 from agent.schema.ts -----------------------------------
CREATE INDEX  IF NOT EXISTS idx_agents_created_by_is_active
  ON agents (created_by, is_active);
CREATE INDEX  IF NOT EXISTS idx_agents_is_default_is_active
  ON agents (is_default, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_name_created_by
  ON agents (name, created_by);
-- Partial-unique slug indexes (MongoDB partialFilterExpression -> PG WHERE)
CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_created_by_slug_non_default
  ON agents (created_by, slug)
  WHERE is_default = false AND slug <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_slug_default
  ON agents (slug, is_default)
  WHERE is_default = true AND slug <> '';
CREATE INDEX  IF NOT EXISTS idx_agents_type_created_by_default_for_type
  ON agents (agent_type_id, created_by, is_default_for_type);
CREATE INDEX  IF NOT EXISTS idx_agents_type_is_default_default_for_type
  ON agents (agent_type_id, is_default, is_default_for_type);

-- Added for external readers (NOT in the Mongo schema) — review/keep or drop:
CREATE INDEX  IF NOT EXISTS idx_agents_agent_type_slug ON agents (agent_type_slug);
CREATE INDEX  IF NOT EXISTS idx_agents_is_active        ON agents (is_active);

-- Semantic (vector) index for humain-agent role search. Requires the pgvector
-- extension (>= 0.7 for halfvec). HNSW + cosine distance.
-- CREATE EXTENSION IF NOT EXISTS vector;
CREATE INDEX IF NOT EXISTS idx_agents_role_embedding
  ON agents USING hnsw (role_embedding halfvec_cosine_ops);

-- -----------------------------------------------------------------------------
-- Junction tables (the reference arrays on the agent document).
-- ref-side id -> Mongo document (no FK); agent_id -> agents(id) (real FK).
-- Reverse indexes on the ref column answer "which agents use X" for services.
-- -----------------------------------------------------------------------------

-- Agent.tools[] -> Tool
CREATE TABLE IF NOT EXISTS agent_tools (
  agent_id  object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  tool_id   object_id NOT NULL,
  PRIMARY KEY (agent_id, tool_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_tools_tool_id ON agent_tools (tool_id);

-- Agent.skills[] -> Skill
CREATE TABLE IF NOT EXISTS agent_skills (
  agent_id  object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  skill_id  object_id NOT NULL,
  PRIMARY KEY (agent_id, skill_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_skills_skill_id ON agent_skills (skill_id);

-- Agent.disabledSkills[] -> Skill
CREATE TABLE IF NOT EXISTS agent_disabled_skills (
  agent_id  object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  skill_id  object_id NOT NULL,
  PRIMARY KEY (agent_id, skill_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_disabled_skills_skill_id ON agent_disabled_skills (skill_id);

-- Agent.connectors[] -> Connector
CREATE TABLE IF NOT EXISTS agent_connectors (
  agent_id      object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  connector_id  object_id NOT NULL,
  PRIMARY KEY (agent_id, connector_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_connectors_connector_id ON agent_connectors (connector_id);

-- Agent.knowledgeBases[] -> Workspace
CREATE TABLE IF NOT EXISTS agent_knowledge_bases (
  agent_id      object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  workspace_id  object_id NOT NULL,
  PRIMARY KEY (agent_id, workspace_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_bases_workspace_id ON agent_knowledge_bases (workspace_id);

-- Agent.connectorActionSelections[] -> { connector, actionKeys[] }
CREATE TABLE IF NOT EXISTS agent_connector_actions (
  agent_id      object_id NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  connector_id  object_id NOT NULL,
  action_keys   text[]    NOT NULL DEFAULT '{}',
  PRIMARY KEY (agent_id, connector_id)
);
CREATE INDEX IF NOT EXISTS idx_agent_connector_actions_connector_id ON agent_connector_actions (connector_id);

-- =============================================================================
-- guardrails jsonb shape (documented, not enforced):
--   {
--     "promptInjection": {
--       "inputGuardrailEnabled":    boolean,
--       "outputGuardrailEnabled":   boolean,
--       "toolCallGuardrailEnabled": boolean,
--       "inputClassifierPrompt":    string,
--       "outputClassifierPrompt":   string,
--       "toolCallClassifierPrompt": string,
--       "blockMessage":             string
--     }
--   }
--
-- deployment_settings jsonb shape (documented, not enforced):
--   {
--     "embedEnabled": boolean,
--     "restEnabled":  boolean,
--     "widget":       object | null   -- free-form Record<string, unknown>
--   }
-- =============================================================================
