import { Injectable } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { BadRequestException, ConflictException, ForbiddenException, NotFoundException } from '@modules/exceptions';
import { Workspace, WorkspaceDocument } from '@modules/workspace/schemas/workspace.schema';
import { WorkspaceShare, WorkspaceShareDocument } from '@modules/workspace/schemas/workspace-share.schema';
import { ErrorCode } from '@modules/exceptions/constants/error-codes';
import { GovernanceProgramService } from './governance-program.service';
import { GovernanceAccessService } from './governance-access.service';
import { GovernanceWorkspaceBinding, GovernanceWorkspaceBindingDocument } from '../schemas/governance-workspace-binding.schema';
import type { CreateGovernanceWorkspaceBindingDto, UpdateGovernanceWorkspaceBindingDto } from '../dto/create-governance-workspace-binding.dto';

@Injectable()
export class GovernanceWorkspaceBindingService {
  constructor(@InjectModel(GovernanceWorkspaceBinding.name) private readonly bindingModel: Model<GovernanceWorkspaceBindingDocument>, @InjectModel(Workspace.name) private readonly workspaceModel: Model<WorkspaceDocument>, @InjectModel(WorkspaceShare.name) private readonly shareModel: Model<WorkspaceShareDocument>, private readonly programs: GovernanceProgramService, private readonly access: GovernanceAccessService) {}
  async create(actorId: string, programId: string, dto: CreateGovernanceWorkspaceBindingDto): Promise<GovernanceWorkspaceBindingDocument> { await this.programs.assertOwnedProgram(actorId, programId); const scopeIds = dto.scopeIds ?? []; if ((dto.visibility === 'program_shared' && scopeIds.length !== 0) || (dto.visibility === 'scope_specific' && scopeIds.length !== 1) || (dto.visibility === 'multi_scope' && scopeIds.length < 2)) throw new BadRequestException(ErrorCode.VALIDATION_ERROR, 'Visibility and scope selection are inconsistent'); if (dto.visibility === 'program_shared') await this.access.assertProgramWideAccess(actorId, programId); else await this.access.assertScopeSelection(actorId, programId, scopeIds); const workspace = await this.workspaceModel.findById(dto.workspaceId).exec(); if (!workspace) throw new NotFoundException(ErrorCode.WORKSPACE_NOT_FOUND, 'Workspace not found'); const canManage = workspace.createdBy.equals(actorId) || (!workspace.isPublic && Boolean(await this.shareModel.exists({ workspaceId: workspace._id, sharedWithUserId: new Types.ObjectId(actorId), permission: 'readwrite' }))); if (!canManage) throw new ForbiddenException(ErrorCode.WORKSPACE_FORBIDDEN, 'Write access to the workspace is required'); try { return await this.bindingModel.create({ programId: new Types.ObjectId(programId), workspaceId: new Types.ObjectId(dto.workspaceId), visibility: dto.visibility, scopeIds: scopeIds.map((id) => new Types.ObjectId(id)), ingestionMode: dto.ingestionMode ?? 'assisted', defaults: dto.defaults ?? {}, createdBy: new Types.ObjectId(actorId) }); } catch (error) { if (typeof error === 'object' && error !== null && 'code' in error && (error as { code?: number }).code === 11000) throw new ConflictException(ErrorCode.VALIDATION_ERROR, 'Workspace is already bound to this program'); throw error; } }
  async list(actorId: string, programId: string): Promise<GovernanceWorkspaceBindingDocument[]> { await this.programs.assertOwnedProgram(actorId, programId); return this.bindingModel.find({ programId: new Types.ObjectId(programId) }).sort({ createdAt: -1 }).exec(); }
  async find(actorId: string, programId: string, bindingId: string): Promise<GovernanceWorkspaceBindingDocument> { await this.programs.assertOwnedProgram(actorId, programId); const binding = await this.bindingModel.findOne({ _id: this.objectId(bindingId, 'bindingId'), programId: new Types.ObjectId(programId) }).exec(); if (!binding) throw new NotFoundException(ErrorCode.VALIDATION_ERROR, 'Workspace binding not found'); return binding; }
  async enabledForWorkspace(workspaceId: string): Promise<GovernanceWorkspaceBindingDocument[]> { return this.bindingModel.find({ workspaceId: this.objectId(workspaceId, 'workspaceId'), enabled: true }).exec(); }
  async update(actorId: string, programId: string, bindingId: string, dto: UpdateGovernanceWorkspaceBindingDto): Promise<GovernanceWorkspaceBindingDocument> { await this.programs.assertOwnedProgram(actorId, programId); const binding = await this.bindingModel.findOne({ _id: this.objectId(bindingId, 'bindingId'), programId: new Types.ObjectId(programId) }).exec(); if (!binding) throw new NotFoundException(ErrorCode.VALIDATION_ERROR, 'Workspace binding not found'); if (dto.enabled !== undefined) binding.enabled = dto.enabled; if (dto.ingestionMode) binding.ingestionMode = dto.ingestionMode; if (dto.defaults) binding.defaults = dto.defaults; await binding.save(); return binding; }
  async delete(actorId: string, programId: string, bindingId: string): Promise<void> { const binding = await this.find(actorId, programId, bindingId); await binding.deleteOne(); }
  async assertAccessible(actorId: string, programId: string, bindingId: string): Promise<void> { await this.programs.assertOwnedProgram(actorId, programId); const binding = await this.bindingModel.exists({ _id: this.objectId(bindingId, 'bindingId'), programId: new Types.ObjectId(programId) }); if (!binding) throw new NotFoundException(ErrorCode.VALIDATION_ERROR, 'Workspace binding not found'); }
  private objectId(value: string, field: string): Types.ObjectId { if (!Types.ObjectId.isValid(value)) throw new BadRequestException(ErrorCode.VALIDATION_ERROR, `${field} must be a valid identifier`); return new Types.ObjectId(value); }
}
