-- Cross-schema foreign keys, hygiene and statistics (remediation plan 5.2).
-- GENERATED by scripts/migrate/generate-0025.ts — edit fk-specs.ts and regenerate,
-- never edit this file directly.
--
-- Idempotent: every constraint is created NOT VALID (if missing) and validated
-- in its own lock-safe block, so re-runs on a live database are no-ops.

SET LOCAL lock_timeout = '5s';

-- widget_tokens.created_by had no leading index (remediation R-17).
CREATE INDEX IF NOT EXISTS idx_widget_tokens_created_by ON channels.widget_tokens (created_by);

-- fk_artifacts_workspace on workspace.workspace_artifacts
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_artifacts_workspace' AND conrelid = 'workspace.workspace_artifacts'::regclass) THEN
    ALTER TABLE workspace.workspace_artifacts ADD CONSTRAINT fk_artifacts_workspace FOREIGN KEY (workspace_id) REFERENCES workspace.workspaces(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE workspace.workspace_artifacts VALIDATE CONSTRAINT fk_artifacts_workspace;

-- fk_gov_bindings_workspace on governance.governance_workspace_bindings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_gov_bindings_workspace' AND conrelid = 'governance.governance_workspace_bindings'::regclass) THEN
    ALTER TABLE governance.governance_workspace_bindings ADD CONSTRAINT fk_gov_bindings_workspace FOREIGN KEY (workspace_id) REFERENCES workspace.workspaces(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE governance.governance_workspace_bindings VALIDATE CONSTRAINT fk_gov_bindings_workspace;

-- fk_agents_agent_type on public.agents
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agents_agent_type' AND conrelid = 'public.agents'::regclass) THEN
    ALTER TABLE public.agents ADD CONSTRAINT fk_agents_agent_type FOREIGN KEY (agent_type_id) REFERENCES catalog.agent_types(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agents VALIDATE CONSTRAINT fk_agents_agent_type;

-- fk_agent_tools_tool on public.agent_tools
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agent_tools_tool' AND conrelid = 'public.agent_tools'::regclass) THEN
    ALTER TABLE public.agent_tools ADD CONSTRAINT fk_agent_tools_tool FOREIGN KEY (tool_id) REFERENCES catalog.tools(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agent_tools VALIDATE CONSTRAINT fk_agent_tools_tool;

-- fk_agent_skills_skill on public.agent_skills
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agent_skills_skill' AND conrelid = 'public.agent_skills'::regclass) THEN
    ALTER TABLE public.agent_skills ADD CONSTRAINT fk_agent_skills_skill FOREIGN KEY (skill_id) REFERENCES catalog.skills(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agent_skills VALIDATE CONSTRAINT fk_agent_skills_skill;

-- fk_agent_disabled_skills_skill on public.agent_disabled_skills
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agent_disabled_skills_skill' AND conrelid = 'public.agent_disabled_skills'::regclass) THEN
    ALTER TABLE public.agent_disabled_skills ADD CONSTRAINT fk_agent_disabled_skills_skill FOREIGN KEY (skill_id) REFERENCES catalog.skills(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agent_disabled_skills VALIDATE CONSTRAINT fk_agent_disabled_skills_skill;

-- fk_users_plan on identity.users
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_plan' AND conrelid = 'identity.users'::regclass) THEN
    ALTER TABLE identity.users ADD CONSTRAINT fk_users_plan FOREIGN KEY (plan_id) REFERENCES catalog.plans(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE identity.users VALIDATE CONSTRAINT fk_users_plan;

-- fk_user_app_connections_app_key on integrations.user_app_connections
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_app_connections_app_key' AND conrelid = 'integrations.user_app_connections'::regclass) THEN
    ALTER TABLE integrations.user_app_connections ADD CONSTRAINT fk_user_app_connections_app_key FOREIGN KEY (app_key) REFERENCES integrations.connected_app_definitions(app_key) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE integrations.user_app_connections VALIDATE CONSTRAINT fk_user_app_connections_app_key;

-- fk_connector_skills_skill on integrations.connector_skills
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_connector_skills_skill' AND conrelid = 'integrations.connector_skills'::regclass) THEN
    ALTER TABLE integrations.connector_skills ADD CONSTRAINT fk_connector_skills_skill FOREIGN KEY (skill_id) REFERENCES catalog.skills(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE integrations.connector_skills VALIDATE CONSTRAINT fk_connector_skills_skill;

-- fk_telegram_chat_bindings_conversation on channels.telegram_chat_bindings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_telegram_chat_bindings_conversation' AND conrelid = 'channels.telegram_chat_bindings'::regclass) THEN
    ALTER TABLE channels.telegram_chat_bindings ADD CONSTRAINT fk_telegram_chat_bindings_conversation FOREIGN KEY (conversation_id) REFERENCES conversation.conversations(id) ON DELETE SET NULL NOT VALID;
  END IF;
END $$;
ALTER TABLE channels.telegram_chat_bindings VALIDATE CONSTRAINT fk_telegram_chat_bindings_conversation;

-- fk_telegram_chat_bindings_user on channels.telegram_chat_bindings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_telegram_chat_bindings_user' AND conrelid = 'channels.telegram_chat_bindings'::regclass) THEN
    ALTER TABLE channels.telegram_chat_bindings ADD CONSTRAINT fk_telegram_chat_bindings_user FOREIGN KEY (user_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE channels.telegram_chat_bindings VALIDATE CONSTRAINT fk_telegram_chat_bindings_user;

-- fk_telegram_chat_bindings_agent on channels.telegram_chat_bindings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_telegram_chat_bindings_agent' AND conrelid = 'channels.telegram_chat_bindings'::regclass) THEN
    ALTER TABLE channels.telegram_chat_bindings ADD CONSTRAINT fk_telegram_chat_bindings_agent FOREIGN KEY (agent_id) REFERENCES public.agents(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE channels.telegram_chat_bindings VALIDATE CONSTRAINT fk_telegram_chat_bindings_agent;

-- fk_telegram_integrations_user on channels.telegram_integrations
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_telegram_integrations_user' AND conrelid = 'channels.telegram_integrations'::regclass) THEN
    ALTER TABLE channels.telegram_integrations ADD CONSTRAINT fk_telegram_integrations_user FOREIGN KEY (user_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE channels.telegram_integrations VALIDATE CONSTRAINT fk_telegram_integrations_user;

-- fk_widget_tokens_created_by on channels.widget_tokens
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_widget_tokens_created_by' AND conrelid = 'channels.widget_tokens'::regclass) THEN
    ALTER TABLE channels.widget_tokens ADD CONSTRAINT fk_widget_tokens_created_by FOREIGN KEY (created_by) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE channels.widget_tokens VALIDATE CONSTRAINT fk_widget_tokens_created_by;

-- fk_shared_agents_shared_with on public.shared_agents
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shared_agents_shared_with' AND conrelid = 'public.shared_agents'::regclass) THEN
    ALTER TABLE public.shared_agents ADD CONSTRAINT fk_shared_agents_shared_with FOREIGN KEY (shared_with) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE public.shared_agents VALIDATE CONSTRAINT fk_shared_agents_shared_with;

-- fk_shared_agents_shared_by on public.shared_agents
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shared_agents_shared_by' AND conrelid = 'public.shared_agents'::regclass) THEN
    ALTER TABLE public.shared_agents ADD CONSTRAINT fk_shared_agents_shared_by FOREIGN KEY (shared_by) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE public.shared_agents VALIDATE CONSTRAINT fk_shared_agents_shared_by;

-- fk_shared_teams_shared_with on teams.shared_teams
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shared_teams_shared_with' AND conrelid = 'teams.shared_teams'::regclass) THEN
    ALTER TABLE teams.shared_teams ADD CONSTRAINT fk_shared_teams_shared_with FOREIGN KEY (shared_with) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE teams.shared_teams VALIDATE CONSTRAINT fk_shared_teams_shared_with;

-- fk_shared_teams_shared_by on teams.shared_teams
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_shared_teams_shared_by' AND conrelid = 'teams.shared_teams'::regclass) THEN
    ALTER TABLE teams.shared_teams ADD CONSTRAINT fk_shared_teams_shared_by FOREIGN KEY (shared_by) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE teams.shared_teams VALIDATE CONSTRAINT fk_shared_teams_shared_by;

-- fk_teams_created_by on teams.teams
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_teams_created_by' AND conrelid = 'teams.teams'::regclass) THEN
    ALTER TABLE teams.teams ADD CONSTRAINT fk_teams_created_by FOREIGN KEY (created_by) REFERENCES identity.users(id) NOT VALID;
  END IF;
END $$;
ALTER TABLE teams.teams VALIDATE CONSTRAINT fk_teams_created_by;

-- fk_agent_connectors_connector on public.agent_connectors
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agent_connectors_connector' AND conrelid = 'public.agent_connectors'::regclass) THEN
    ALTER TABLE public.agent_connectors ADD CONSTRAINT fk_agent_connectors_connector FOREIGN KEY (connector_id) REFERENCES integrations.connectors(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agent_connectors VALIDATE CONSTRAINT fk_agent_connectors_connector;

-- fk_agent_connector_actions_connector on public.agent_connector_actions
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_agent_connector_actions_connector' AND conrelid = 'public.agent_connector_actions'::regclass) THEN
    ALTER TABLE public.agent_connector_actions ADD CONSTRAINT fk_agent_connector_actions_connector FOREIGN KEY (connector_id) REFERENCES integrations.connectors(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
ALTER TABLE public.agent_connector_actions VALIDATE CONSTRAINT fk_agent_connector_actions_connector;

-- Fresh statistics for the new tables (39 of 48 were never analyzed).
DO $analyze$
DECLARE t record;
BEGIN
  FOR t IN
    SELECT n.nspname AS schema, c.relname AS name
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      LEFT JOIN pg_stat_user_tables s ON s.relid = c.oid
     WHERE c.relkind = 'r'
       AND n.nspname IN ('identity', 'authz', 'catalog', 'ops', 'integrations', 'teams', 'channels')
       AND s.last_analyze IS NULL AND s.last_autoanalyze IS NULL
  LOOP
    EXECUTE 'ANALYZE ' || quote_ident(t.schema) || '.' || quote_ident(t.name);
  END LOOP;
END
$analyze$;
