-- Foreign keys of conversation-v2 and app-runtime (roadmap: cross-schema FKs once the data was complete).
-- GENERATED by scripts/migrate/generate-0037.ts — edit fk-specs.ts and regenerate,
-- never edit this file directly.
--
-- Idempotent and safe on dirty data: each constraint is added NOT VALID (enforced for every new write)
-- when missing, and validated in its own block only when no orphan row remains. A constraint that
-- still has orphans stays NOT VALID; scripts/migrate/2026-10-conversation-app-runtime-fk.ts validates
-- it after exporting and removing them (opt-in --delete-orphans). Numbered 0037 after 0036_logs.

SET LOCAL lock_timeout = '5s';

-- Leading indexes for the referencing columns that had none (db:verify check4).
CREATE INDEX IF NOT EXISTS idx_c2_sessions_system_workspace ON conversation_v2.sessions (system_workspace_id);
CREATE INDEX IF NOT EXISTS idx_c2_app_shares_owner ON conversation_v2.app_shares (owner_id);
CREATE INDEX IF NOT EXISTS idx_ar_tickets_binding ON app_runtime.tickets (binding_id);
CREATE INDEX IF NOT EXISTS idx_ar_tickets_user ON app_runtime.tickets (user_id);

-- fk_c2_sessions_owner on conversation_v2.sessions
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_c2_sessions_owner' AND conrelid = 'conversation_v2.sessions'::regclass) THEN
    ALTER TABLE conversation_v2.sessions ADD CONSTRAINT fk_c2_sessions_owner FOREIGN KEY (owner_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM conversation_v2.sessions s WHERE NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = s.owner_id)) c) = 0 THEN
    ALTER TABLE conversation_v2.sessions VALIDATE CONSTRAINT fk_c2_sessions_owner;
  END IF;
END $$;

-- fk_c2_sessions_system_workspace on conversation_v2.sessions
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_c2_sessions_system_workspace' AND conrelid = 'conversation_v2.sessions'::regclass) THEN
    ALTER TABLE conversation_v2.sessions ADD CONSTRAINT fk_c2_sessions_system_workspace FOREIGN KEY (system_workspace_id) REFERENCES workspace.workspaces(id) ON DELETE SET NULL NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM conversation_v2.sessions s WHERE s.system_workspace_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM workspace.workspaces w WHERE w.id = s.system_workspace_id)) c) = 0 THEN
    ALTER TABLE conversation_v2.sessions VALIDATE CONSTRAINT fk_c2_sessions_system_workspace;
  END IF;
END $$;

-- fk_c2_app_shares_owner on conversation_v2.app_shares
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_c2_app_shares_owner' AND conrelid = 'conversation_v2.app_shares'::regclass) THEN
    ALTER TABLE conversation_v2.app_shares ADD CONSTRAINT fk_c2_app_shares_owner FOREIGN KEY (owner_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM conversation_v2.app_shares a WHERE NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = a.owner_id)) c) = 0 THEN
    ALTER TABLE conversation_v2.app_shares VALIDATE CONSTRAINT fk_c2_app_shares_owner;
  END IF;
END $$;

-- fk_c2_app_shares_recipient on conversation_v2.app_shares
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_c2_app_shares_recipient' AND conrelid = 'conversation_v2.app_shares'::regclass) THEN
    ALTER TABLE conversation_v2.app_shares ADD CONSTRAINT fk_c2_app_shares_recipient FOREIGN KEY (recipient_user_id) REFERENCES identity.users(id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM conversation_v2.app_shares a WHERE a.recipient_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = a.recipient_user_id)) c) = 0 THEN
    ALTER TABLE conversation_v2.app_shares VALIDATE CONSTRAINT fk_c2_app_shares_recipient;
  END IF;
END $$;

-- fk_ar_bindings_user on app_runtime.bindings
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_bindings_user' AND conrelid = 'app_runtime.bindings'::regclass) THEN
    ALTER TABLE app_runtime.bindings ADD CONSTRAINT fk_ar_bindings_user FOREIGN KEY (user_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.bindings b WHERE NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = b.user_id)) c) = 0 THEN
    ALTER TABLE app_runtime.bindings VALIDATE CONSTRAINT fk_ar_bindings_user;
  END IF;
END $$;

-- fk_ar_tickets_binding on app_runtime.tickets
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_tickets_binding' AND conrelid = 'app_runtime.tickets'::regclass) THEN
    ALTER TABLE app_runtime.tickets ADD CONSTRAINT fk_ar_tickets_binding FOREIGN KEY (binding_id) REFERENCES app_runtime.bindings(binding_id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.tickets t WHERE NOT EXISTS (SELECT 1 FROM app_runtime.bindings b WHERE b.binding_id = t.binding_id)) c) = 0 THEN
    ALTER TABLE app_runtime.tickets VALIDATE CONSTRAINT fk_ar_tickets_binding;
  END IF;
END $$;

-- fk_ar_tickets_user on app_runtime.tickets
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_tickets_user' AND conrelid = 'app_runtime.tickets'::regclass) THEN
    ALTER TABLE app_runtime.tickets ADD CONSTRAINT fk_ar_tickets_user FOREIGN KEY (user_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.tickets t WHERE NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = t.user_id)) c) = 0 THEN
    ALTER TABLE app_runtime.tickets VALIDATE CONSTRAINT fk_ar_tickets_user;
  END IF;
END $$;

-- fk_ar_tool_calls_binding on app_runtime.tool_calls
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_tool_calls_binding' AND conrelid = 'app_runtime.tool_calls'::regclass) THEN
    ALTER TABLE app_runtime.tool_calls ADD CONSTRAINT fk_ar_tool_calls_binding FOREIGN KEY (binding_id) REFERENCES app_runtime.bindings(binding_id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.tool_calls t WHERE NOT EXISTS (SELECT 1 FROM app_runtime.bindings b WHERE b.binding_id = t.binding_id)) c) = 0 THEN
    ALTER TABLE app_runtime.tool_calls VALIDATE CONSTRAINT fk_ar_tool_calls_binding;
  END IF;
END $$;

-- fk_ar_ai_preview_tickets_binding on app_runtime.ai_preview_tickets
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_ai_preview_tickets_binding' AND conrelid = 'app_runtime.ai_preview_tickets'::regclass) THEN
    ALTER TABLE app_runtime.ai_preview_tickets ADD CONSTRAINT fk_ar_ai_preview_tickets_binding FOREIGN KEY (binding_id) REFERENCES app_runtime.bindings(binding_id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.ai_preview_tickets t WHERE NOT EXISTS (SELECT 1 FROM app_runtime.bindings b WHERE b.binding_id = t.binding_id)) c) = 0 THEN
    ALTER TABLE app_runtime.ai_preview_tickets VALIDATE CONSTRAINT fk_ar_ai_preview_tickets_binding;
  END IF;
END $$;

-- fk_ar_ai_preview_tickets_billable_user on app_runtime.ai_preview_tickets
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_ai_preview_tickets_billable_user' AND conrelid = 'app_runtime.ai_preview_tickets'::regclass) THEN
    ALTER TABLE app_runtime.ai_preview_tickets ADD CONSTRAINT fk_ar_ai_preview_tickets_billable_user FOREIGN KEY (billable_user_id) REFERENCES identity.users(id) NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.ai_preview_tickets t WHERE NOT EXISTS (SELECT 1 FROM identity.users u WHERE u.id = t.billable_user_id)) c) = 0 THEN
    ALTER TABLE app_runtime.ai_preview_tickets VALIDATE CONSTRAINT fk_ar_ai_preview_tickets_billable_user;
  END IF;
END $$;

-- fk_ar_source_revisions_binding on app_runtime.source_revisions
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_source_revisions_binding' AND conrelid = 'app_runtime.source_revisions'::regclass) THEN
    ALTER TABLE app_runtime.source_revisions ADD CONSTRAINT fk_ar_source_revisions_binding FOREIGN KEY (workspace_id) REFERENCES app_runtime.bindings(workspace_id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.source_revisions r WHERE NOT EXISTS (SELECT 1 FROM app_runtime.bindings b WHERE b.workspace_id = r.workspace_id)) c) = 0 THEN
    ALTER TABLE app_runtime.source_revisions VALIDATE CONSTRAINT fk_ar_source_revisions_binding;
  END IF;
END $$;

-- fk_ar_finalized_revisions_binding on app_runtime.finalized_revisions
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ar_finalized_revisions_binding' AND conrelid = 'app_runtime.finalized_revisions'::regclass) THEN
    ALTER TABLE app_runtime.finalized_revisions ADD CONSTRAINT fk_ar_finalized_revisions_binding FOREIGN KEY (workspace_id) REFERENCES app_runtime.bindings(workspace_id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM app_runtime.finalized_revisions r WHERE NOT EXISTS (SELECT 1 FROM app_runtime.bindings b WHERE b.workspace_id = r.workspace_id)) c) = 0 THEN
    ALTER TABLE app_runtime.finalized_revisions VALIDATE CONSTRAINT fk_ar_finalized_revisions_binding;
  END IF;
END $$;
