-- Foreign key of a classifier run to its playbook (roadmap P5: the flow store is on Postgres now).
-- GENERATED by scripts/migrate/generate-0041.ts — edit fk-specs.ts and regenerate,
-- never edit this file directly.
--
-- Idempotent and safe on dirty data: each constraint is added NOT VALID (enforced for every new write)
-- when missing, and validated in its own block only when no orphan row remains. A constraint that
-- still has orphans stays NOT VALID; scripts/migrate/2026-10-classifier-playbook-fk.ts validates
-- it after exporting and removing them (opt-in --delete-orphans). Numbered 0041 after 0040_playbook.

SET LOCAL lock_timeout = '5s';

-- Leading indexes for the referencing columns that had none (db:verify check4).
CREATE INDEX IF NOT EXISTS idx_classifier_runs_playbook ON classifier.runs (playbook_id);

-- fk_classifier_runs_playbook on classifier.runs
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_classifier_runs_playbook' AND conrelid = 'classifier.runs'::regclass) THEN
    ALTER TABLE classifier.runs ADD CONSTRAINT fk_classifier_runs_playbook FOREIGN KEY (playbook_id) REFERENCES playbook.flows(id) ON DELETE CASCADE NOT VALID;
  END IF;
  IF (SELECT c.n FROM (SELECT count(*)::int AS n FROM classifier.runs r WHERE NOT EXISTS (SELECT 1 FROM playbook.flows f WHERE f.id = r.playbook_id)) c) = 0 THEN
    ALTER TABLE classifier.runs VALIDATE CONSTRAINT fk_classifier_runs_playbook;
  END IF;
END $$;
