import type { MessageRecord } from '../message-store';
import * as schema from '@modules/postgres/schema';

export function mapPostgresMessage(row: typeof schema.messages.$inferSelect): MessageRecord {
  return {
    id: row.id.trim(),
    conversationId: row.conversationId.trim(),
    senderId: row.senderId?.trim(),
    parentMessageId: row.parentMessageId?.trim(),
    conversationType: row.conversationType as MessageRecord['conversationType'],
    content: row.content ?? undefined,
    components: row.components as MessageRecord['components'],
    attachedFileIds: row.attachedFileIds?.map((id) => id.trim()),
    agentIds: row.agentIds?.map((id) => id.trim()),
    memberIds: row.memberIds?.map((id) => id.trim()),
    modelId: row.modelId ?? undefined,
    reasoningEffort: row.reasoningEffort ?? undefined,
    webSearchEnabled: row.webSearchEnabled,
    questionMessageId: row.questionMessageId?.trim(),
    answerMessageId: row.answerMessageId?.trim(),
    feedback: row.feedback as MessageRecord['feedback'],
    feedbackAt: row.feedbackAt ?? undefined,
    isEdited: row.isEdited,
    editedAt: row.editedAt ?? undefined,
    isStreaming: row.isStreaming,
    isComplete: row.isComplete,
    streamExecutionLeaseId: row.streamExecutionLeaseId ?? undefined,
    streamExecutionLeaseExpiresAt: row.streamExecutionLeaseExpiresAt ?? undefined,
    inputTokens: row.inputTokens ?? undefined,
    outputTokens: row.outputTokens ?? undefined,
    modelRequestTelemetry: row.modelRequestTelemetry as MessageRecord['modelRequestTelemetry'],
    durationMs: row.durationMs ?? undefined,
    timeToFirstChunk: row.timeToFirstChunk ?? undefined,
    timeToFirstToken: row.timeToFirstToken ?? undefined,
    latencyMetrics: row.latencyMetrics as MessageRecord['latencyMetrics'],
    requestId: row.requestId ?? undefined,
    guardrailDecision: row.guardrailDecision as MessageRecord['guardrailDecision'],
    interaction: row.interaction as MessageRecord['interaction'],
    interactions: row.interactions as MessageRecord['interactions'],
    replayContext: row.replayContext as MessageRecord['replayContext'],
    reliabilityEvaluation: row.reliabilityEvaluation as MessageRecord['reliabilityEvaluation'],
    correctionWorkflow: row.correctionWorkflow as MessageRecord['correctionWorkflow'],
    reliabilityEvaluationHeartbeatAt: row.reliabilityEvaluationHeartbeatAt ?? undefined,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}
