export const semanticModelQueryKeys = {
  all: ['semantic-models'] as const,
  catalog: (filters: Record<string, unknown>) => ['semantic-models','catalog',filters] as const,
  model: (id: string) => ['semantic-models','model',id] as const,
  graph: (id: string) => ['semantic-models','graph',id] as const,
  bindings: (id: string) => ['semantic-models','bindings',id] as const,
  workspaces: (id: string) => ['semantic-models','workspaces',id] as const,
  versions: (id: string) => ['semantic-models','versions',id] as const,
  workspace: (id: string) => ['semantic-models','workspace-entry',id] as const,
  sourceAssets: (id: string) => ['semantic-models','source-assets',id] as const,
  sourceAssetProfile: (id: string, documentId: string, sheetName?: string) => ['semantic-models','source-asset-profile',id,documentId,sheetName??''] as const,
  sourceMappings: (id: string) => ['semantic-models','source-mappings',id] as const,
  relationRules: (id: string) => ['semantic-models','relation-rules',id] as const,
  identityRules: (id: string) => ['semantic-models','identity-rules',id] as const,
  sourcePolicies: (id: string) => ['semantic-models','source-policies',id] as const,
  dataPreview: (id: string, limit: number) => ['semantic-models','data-preview',id,limit] as const,
  corrections: (id: string) => ['semantic-models','corrections',id] as const,
  mappingHealth: (id: string) => ['semantic-models','mapping-health',id] as const,
  freshness: (id: string) => ['semantic-models','freshness',id] as const,
  sourceSuggestions: (id: string) => ['semantic-models','source-suggestions',id] as const,
  canvasPositions: (id: string) => ['semantic-models','canvas-positions',id] as const,
  readiness: (id: string) => ['semantic-models','readiness',id] as const,
  reviewQueue: (id: string) => ['semantic-models','review-queue',id] as const,
  reviewItems: (id: string, status: 'open' | 'resolved') => ['semantic-models','review-items',id,status] as const,
};
