import { Button } from '@/components/ui/button';
import { useModuleTranslation } from '@/modules/localization';
import { useAcknowledgeKnowledgeAlert, useApplyKnowledgeRecommendation, useDecideKnowledgeRecommendation, useDecideMetadataCandidate, useKnowledgeAlerts, useKnowledgeHealth, useKnowledgeRecommendations, useMetadataCandidates, useRefreshKnowledge } from '../../query/hooks';
import { KnowledgeHealthSummary } from './KnowledgeHealthSummary';
import { KnowledgeAlertCard } from './KnowledgeAlertCard';
import { KnowledgeRecommendationCard } from './KnowledgeRecommendationCard';
import { MetadataCandidateReview } from './MetadataCandidateReview';

export function KnowledgeActionCenter({ programId, scopeId, onOpenSource }: Readonly<{ programId: string | null; scopeId: string; onOpenSource: (sourceId: string) => void }>): JSX.Element {
  const { t } = useModuleTranslation('governance');
  const health = useKnowledgeHealth(programId, scopeId); const alerts = useKnowledgeAlerts(programId, scopeId); const recommendations = useKnowledgeRecommendations(programId, scopeId); const metadata = useMetadataCandidates(programId, scopeId);
  const refresh = useRefreshKnowledge(programId, scopeId); const acknowledge = useAcknowledgeKnowledgeAlert(programId, scopeId); const decideRecommendation = useDecideKnowledgeRecommendation(programId, scopeId); const applyRecommendation = useApplyKnowledgeRecommendation(programId, scopeId); const decideMetadata = useDecideMetadataCandidate(programId, scopeId);
  const isError = health.isError || alerts.isError || recommendations.isError || metadata.isError || refresh.isError || acknowledge.isError || decideRecommendation.isError || applyRecommendation.isError || decideMetadata.isError;
  const isLoading = health.isLoading || alerts.isLoading || recommendations.isLoading || metadata.isLoading;
  return <section className='grid gap-4 rounded-2xl border bg-muted/20 p-4' aria-labelledby='knowledge-action-center-title'><div className='flex flex-wrap items-start justify-between gap-3'><div><h3 id='knowledge-action-center-title' className='font-semibold'>{t('knowledge.title')}</h3><p className='text-sm text-muted-foreground'>{t('knowledge.description')}</p></div><Button type='button' size='sm' disabled={refresh.isPending} onClick={() => refresh.mutate()}>{refresh.isPending ? t('knowledge.refreshing') : t('knowledge.refresh')}</Button></div>{isError && <p role='alert' className='text-sm text-destructive'>{t('knowledge.error')}</p>}{isLoading && <p className='text-sm text-muted-foreground'>{t('knowledge.loading')}</p>}{health.data && <KnowledgeHealthSummary summary={health.data} />}<section className='grid gap-2'><h3 className='text-sm font-semibold'>{t('knowledge.alerts.title')}</h3>{(alerts.data ?? []).map((alert) => <KnowledgeAlertCard key={alert.id} alert={alert} pending={acknowledge.isPending} onAcknowledge={() => acknowledge.mutate(alert.id)} onOpenSource={alert.sourceId ? () => onOpenSource(alert.sourceId as string) : undefined} />)}{alerts.data?.length === 0 && <p className='text-sm text-muted-foreground'>{t('knowledge.alerts.empty')}</p>}</section><section className='grid gap-2'><h3 className='text-sm font-semibold'>{t('knowledge.recommendations.title')}</h3>{(recommendations.data ?? []).map((recommendation) => <KnowledgeRecommendationCard key={recommendation.id} recommendation={recommendation} pending={decideRecommendation.isPending || applyRecommendation.isPending} onDecision={(action) => decideRecommendation.mutate({ id: recommendation.id, action })} onApply={() => applyRecommendation.mutate(recommendation.id)} onOpenSource={recommendation.sourceId ? () => onOpenSource(recommendation.sourceId as string) : undefined} />)}{recommendations.data?.length === 0 && <p className='text-sm text-muted-foreground'>{t('knowledge.recommendations.empty')}</p>}</section><section className='grid gap-2'><h3 className='text-sm font-semibold'>{t('knowledge.metadata.title')}</h3>{(metadata.data ?? []).map((candidate) => <MetadataCandidateReview key={candidate.id} candidate={candidate} pending={decideMetadata.isPending} onDecision={(action) => decideMetadata.mutate({ id: candidate.id, action })} />)}{metadata.data?.length === 0 && <p className='text-sm text-muted-foreground'>{t('knowledge.metadata.empty')}</p>}</section></section>;
}
