import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeftRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useModuleTranslation } from '@/modules/localization';
import { useSemanticModelEditorStore } from '../../store';
import type { SemanticNodeType, SemanticRelationType } from '../../types';
import { businessKey, nextConceptPosition } from '../../utils/model-utils';
import { FormField, INPUT, TEXTAREA } from '../form/FormParts';

export function AddConceptDialog({ open,onOpenChange }: Readonly<{ open:boolean; onOpenChange:(open:boolean)=>void }>) {
  const { t } = useModuleTranslation('semantic-model'); const commit=useSemanticModelEditorStore((state)=>state.commit); const focus=useSemanticModelEditorStore((state)=>state.focus); const graph=useSemanticModelEditorStore((state)=>state.graph); const [label,setLabel]=useState(''); const [description,setDescription]=useState('');
  useEffect(() => { if (!open) { setLabel(''); setDescription(''); } },[open]);
  const add=()=>{if(!graph||!label.trim())return;const entity:SemanticNodeType={id:crypto.randomUUID(),key:businessKey(label),label:label.trim(),description:description.trim(),category:'business_object',recordPolicy:'optional',systemKey:null,aliases:[],attributes:[],position:nextConceptPosition(graph.nodes)};commit({type:'node_type.create',entity},(current)=>({...current,nodes:[...current.nodes,entity]}));focus(entity.id);onOpenChange(false);};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{t('concept.createTitle')}</DialogTitle><DialogDescription>{t('concept.createDescription')}</DialogDescription></DialogHeader><div className='space-y-4 py-2'><FormField label={t('field.label')} htmlFor='semantic-concept-label'><Input id='semantic-concept-label' className={INPUT} value={label} onChange={(event)=>setLabel(event.target.value)} placeholder={t('concept.placeholder')} autoFocus /></FormField><FormField label={t('field.description')} htmlFor='semantic-concept-description'><Textarea id='semantic-concept-description' className={TEXTAREA} rows={3} value={description} onChange={(event)=>setDescription(event.target.value)} placeholder={t('concept.descriptionPlaceholder')} /></FormField></div><DialogFooter><Button variant='outline' onClick={()=>onOpenChange(false)}>{t('action.cancel')}</Button><Button onClick={add} disabled={!label.trim()}>{t('concept.add')}</Button></DialogFooter></DialogContent></Dialog>;
}

export function AddRelationDialog({ open,onOpenChange,initialConnection }: Readonly<{ open:boolean; onOpenChange:(open:boolean)=>void; initialConnection?: { sourceId: string; targetId: string } | null }>) {
  const {t}=useModuleTranslation('semantic-model');const graph=useSemanticModelEditorStore((state)=>state.graph);const commit=useSemanticModelEditorStore((state)=>state.commit);const [label,setLabel]=useState('');const [source,setSource]=useState('');const [target,setTarget]=useState('');const lockedConnection=Boolean(initialConnection);
  useEffect(()=>{
    if (!open) { setLabel('');setSource('');setTarget('');return; }
    setSource(initialConnection?.sourceId ?? '');
    setTarget(initialConnection?.targetId ?? '');
  },[initialConnection?.sourceId,initialConnection?.targetId,open]);
  const add=(event?:FormEvent)=>{event?.preventDefault();if(!graph||!label.trim()||!source||!target)return;const entity:SemanticRelationType={id:crypto.randomUUID(),key:businessKey(label),label:label.trim(),inverseLabel:'',description:'',sourceNodeTypeId:source,targetNodeTypeId:target,cardinality:'many_to_many',traversable:true,filterable:true,attributes:[]};commit({type:'relation_type.create',entity},(current)=>({...current,relations:[...current.relations,entity]}));onOpenChange(false);};
  const sourceLabel=graph?.nodes.find((node)=>node.id===source)?.label;
  const targetLabel=graph?.nodes.find((node)=>node.id===target)?.label;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><form onSubmit={add}><DialogHeader><DialogTitle>{t('relation.createTitle')}</DialogTitle><DialogDescription>{t('relation.createDescription')}</DialogDescription></DialogHeader><div className='mt-5 space-y-4'><div className='grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-end'><FormField label={t('relation.from')}><Select value={source} onValueChange={setSource} disabled={lockedConnection}><SelectTrigger className={INPUT}><SelectValue placeholder={t('relation.chooseConcept')} /></SelectTrigger><SelectContent>{graph?.nodes.map((node)=><SelectItem key={node.id} value={node.id}>{node.label}</SelectItem>)}</SelectContent></Select></FormField><Button type='button' size='icon' variant='ghost' className='h-9 w-9 justify-self-center' disabled={lockedConnection||!source||!target} onClick={()=>{setSource(target);setTarget(source);}} aria-label={t('relation.swap')} title={t('relation.swap')}><ArrowLeftRight className='h-4 w-4' /></Button><FormField label={t('relation.to')}><Select value={target} onValueChange={setTarget} disabled={lockedConnection}><SelectTrigger className={INPUT}><SelectValue placeholder={t('relation.chooseConcept')} /></SelectTrigger><SelectContent>{graph?.nodes.map((node)=><SelectItem key={node.id} value={node.id}>{node.label}</SelectItem>)}</SelectContent></Select></FormField></div><FormField label={t('relation.wording')} htmlFor='semantic-relation-label'><Input id='semantic-relation-label' className={INPUT} value={label} onChange={(event)=>setLabel(event.target.value)} placeholder={t('relation.placeholder')} autoFocus /></FormField>{sourceLabel&&targetLabel&&<p className='rounded-lg bg-primary/5 px-3 py-2 text-sm'><span className='font-semibold'>{sourceLabel}</span>{' '}<span className='text-primary'>{label.trim()||t('relation.placeholderShort')}</span>{' '}<span className='font-semibold'>{targetLabel}</span></p>}</div><DialogFooter className='mt-6'><Button type='button' variant='outline' onClick={()=>onOpenChange(false)}>{t('action.cancel')}</Button><Button type='submit' disabled={!label.trim()||!source||!target}>{t('relation.connect')}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function AddRecordDialog({ open,onOpenChange }: Readonly<{ open:boolean; onOpenChange:(open:boolean)=>void }>) {
  const {t}=useModuleTranslation('semantic-model');const graph=useSemanticModelEditorStore((state)=>state.graph);const commit=useSemanticModelEditorStore((state)=>state.commit);const [label,setLabel]=useState('');const [typeId,setTypeId]=useState('');const types=graph?.nodes.filter((node)=>node.recordPolicy!=='none')??[];
  const add=()=>{if(!graph||!label.trim()||!typeId)return;const entity={id:crypto.randomUUID(),nodeTypeId:typeId,label:label.trim(),values:{},status:'active' as const,position:{x:100+graph.records.length*24,y:100+graph.records.length*20}};commit({type:'record.create',entity},(current)=>({...current,records:[...current.records,entity]}));useSemanticModelEditorStore.getState().select(entity.id,{details:true});onOpenChange(false);setLabel('');setTypeId('');};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{t('records.createTitle')}</DialogTitle><DialogDescription>{t('records.createDescription')}</DialogDescription></DialogHeader><div className='space-y-4 py-2'><FormField label={t('records.type')}><Select value={typeId} onValueChange={setTypeId}><SelectTrigger className={INPUT}><SelectValue placeholder={t('records.chooseType')} /></SelectTrigger><SelectContent>{types.map((node)=><SelectItem key={node.id} value={node.id}>{node.label}</SelectItem>)}</SelectContent></Select></FormField><FormField label={t('field.label')} htmlFor='semantic-record-label'><Input id='semantic-record-label' className={INPUT} value={label} onChange={(event)=>setLabel(event.target.value)} placeholder={t('records.placeholder')} /></FormField></div><DialogFooter><Button variant='outline' onClick={()=>onOpenChange(false)}>{t('action.cancel')}</Button><Button onClick={add} disabled={!label.trim()||!typeId}>{t('records.add')}</Button></DialogFooter></DialogContent></Dialog>;
}
