import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useModuleTranslation } from '@/modules/localization';
import { governanceApi } from '../../api';
import { useGovernanceSourceEvents, useGovernanceSourceVersions } from '../../query/hooks';
import { governanceQueryKeys } from '../../query/queryKeys';
import type { GovernanceSource, GovernanceSourceVersion } from '../../types';
import { TemporalCandidatesPanel } from './TemporalCandidatesPanel';

const validityModes: GovernanceSourceVersion['validity']['mode'][] = ['unknown', 'fixed_date', 'relative_duration', 'until_replaced', 'until_funds_exhausted', 'open_ended'];

export function SourcePassportDrawer({ open, onOpenChange, programId, source }: Readonly<{ open: boolean; onOpenChange: (open: boolean) => void; programId: string | null; source: GovernanceSource | null }>): JSX.Element {
  const { t } = useModuleTranslation('governance'); const queryClient = useQueryClient();
  const { data: versions = [] } = useGovernanceSourceVersions(programId, source?.id ?? null); const { data: events = [] } = useGovernanceSourceEvents(programId, source?.id ?? null);
  const [selectedVersionId, setSelectedVersionId] = useState<string | null>(null); const current = versions.find((version) => version.id === selectedVersionId) ?? versions[0];
  const invalidate = () => { if (!programId || !source) return; void queryClient.invalidateQueries({ queryKey: governanceQueryKeys.sourceVersions(programId, source.id) }); void queryClient.invalidateQueries({ queryKey: governanceQueryKeys.sourceEvents(programId, source.id) }); };
  const transition = useMutation({ mutationFn: ({ versionId, action }: { versionId: string; action: 'submit-review' | 'return-to-editing' | 'approve' | 'reject' | 'publish' }) => governanceApi.transitionSourceVersion(programId ?? '', source?.id ?? '', versionId, action), onSuccess: invalidate });
  const updateValidity = useMutation({ mutationFn: ({ versionId, patch }: { versionId: string; patch: Partial<GovernanceSourceVersion['validity']> }) => governanceApi.updateSourceValidity(programId ?? '', source?.id ?? '', versionId, patch), onSuccess: invalidate });
  const saveValidity = (patch: Partial<GovernanceSourceVersion['validity']>) => { if (current) updateValidity.mutate({ versionId: current.id, patch }); }; const dateValue = (value?: string | null) => value?.slice(0, 10) ?? '';
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className='max-h-[85vh] max-w-2xl overflow-y-auto'><DialogHeader><DialogTitle>{source?.title ?? t('sourcePassport.title')}</DialogTitle><DialogDescription>{t('sourcePassport.description')}</DialogDescription></DialogHeader>{current ? <div key={current.id} className='grid gap-4'>
    <div className='grid gap-2 rounded-xl border p-3 sm:grid-cols-4'>{[['sourcePassport.version', `v${current.versionNumber}`], ['sourcePassport.technical', current.technicalStatus], ['sourcePassport.lifecycle', current.lifecycleStatus], ['sourcePassport.validity', current.validity.mode]].map(([label, value]) => <div key={label}><p className='text-xs text-muted-foreground'>{t(label as never)}</p><p className='text-sm font-medium'>{value}</p></div>)}</div>
    <div className='grid gap-2'><h3 className='text-sm font-semibold'>{t('sourcePassport.versions')}</h3><div className='flex flex-wrap gap-2'>{versions.map((version) => <Button key={version.id} type='button' size='sm' variant={version.id === current.id ? 'default' : 'outline'} onClick={() => setSelectedVersionId(version.id)}>{t('sourcePassport.version')} {version.versionNumber}</Button>)}</div></div>
    <div className='flex flex-wrap gap-2'>{current.lifecycleStatus === 'captured' && <Button size='sm' onClick={() => transition.mutate({ versionId: current.id, action: 'submit-review' })}>{t('sourcePassport.submit')}</Button>}{current.lifecycleStatus === 'to_review' && <><Button size='sm' onClick={() => transition.mutate({ versionId: current.id, action: 'approve' })}>{t('sourcePassport.approve')}</Button><Button size='sm' variant='outline' onClick={() => transition.mutate({ versionId: current.id, action: 'reject' })}>{t('sourcePassport.reject')}</Button><Button size='sm' variant='outline' onClick={() => transition.mutate({ versionId: current.id, action: 'return-to-editing' })}>{t('sourcePassport.return')}</Button></>}{current.lifecycleStatus === 'approved' && <Button size='sm' disabled={current.technicalStatus !== 'ready'} onClick={() => transition.mutate({ versionId: current.id, action: 'publish' })}>{t('sourcePassport.publish')}</Button>}</div>
    <div className='grid gap-3 rounded-xl border p-3'><h3 className='text-sm font-semibold'>{t('sourcePassport.validity')}</h3><Select value={current.validity.mode} disabled={updateValidity.isPending} onValueChange={(mode: GovernanceSourceVersion['validity']['mode']) => saveValidity({ mode })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{validityModes.map((mode) => <SelectItem key={mode} value={mode}>{t(`sourcePassport.validityMode.${mode}`)}</SelectItem>)}</SelectContent></Select>
      <div className='grid gap-3 sm:grid-cols-2'>{([['effective-from', 'sourcePassport.effectiveFrom', 'effectiveFrom'], ['effective-until', 'sourcePassport.effectiveUntil', 'effectiveUntil'], ['last-reviewed', 'sourcePassport.lastReviewed', 'lastReviewedAt'], ['next-review', 'sourcePassport.nextReview', 'nextReviewAt']] as const).map(([id, label, field]) => <div key={id} className='grid gap-1'><Label htmlFor={id}>{t(label)}</Label><Input id={id} type='date' defaultValue={dateValue(current.validity[field])} onBlur={(event) => saveValidity({ [field]: event.target.value || null })} /></div>)}<div className='grid gap-1'><Label htmlFor='review-frequency'>{t('sourcePassport.reviewFrequency')}</Label><Input id='review-frequency' type='number' min='1' defaultValue={current.validity.reviewFrequencyDays ?? undefined} onBlur={(event) => saveValidity({ reviewFrequencyDays: event.target.value ? Number(event.target.value) : null })} /></div><div className='grid gap-1'><Label htmlFor='confidence'>{t('sourcePassport.confidence')}</Label><Input id='confidence' type='number' min='0' max='1' step='0.01' defaultValue={current.validity.confidence} onBlur={(event) => saveValidity({ confidence: Number(event.target.value) })} /></div></div>
      <label className='flex items-center gap-2 text-sm'><Input type='checkbox' checked={current.validity.inclusiveEnd === true} onChange={(event) => saveValidity({ inclusiveEnd: event.target.checked })} />{t('sourcePassport.inclusiveEnd')}</label><label className='flex items-center gap-2 text-sm'><Input type='checkbox' checked={current.validity.manuallyOverridden === true} onChange={(event) => saveValidity({ manuallyOverridden: event.target.checked })} />{t('sourcePassport.manualOverride')}</label><p className='text-xs text-muted-foreground'>{t('sourcePassport.businessStatus')}: {current.validity.businessStatus} · {t('sourcePassport.evidenceCount')}: {current.validity.evidence?.length ?? 0}</p>
    </div>
    {programId && source && <TemporalCandidatesPanel programId={programId} sourceId={source.id} version={current} onChanged={invalidate} />}
    <div className='grid gap-1 text-sm'><h3 className='font-semibold'>{t('sourcePassport.audit')}</h3>{current.submittedForReviewAt && <p>{t('sourcePassport.submittedAt')}: {new Date(current.submittedForReviewAt).toLocaleString()}</p>}{current.reviewedAt && <p>{t('sourcePassport.reviewedAt')}: {new Date(current.reviewedAt).toLocaleString()}</p>}{current.publishedAt && <p>{t('sourcePassport.publishedAt')}: {new Date(current.publishedAt).toLocaleString()}</p>}</div><div><h3 className='text-sm font-semibold'>{t('sourcePassport.history')}</h3>{events.map((event) => <div key={event.id} className='mt-2 rounded-lg border p-2 text-sm'>{event.eventType}</div>)}</div>
  </div> : <p className='text-sm text-muted-foreground'>{t('sourcePassport.empty')}</p>}</DialogContent></Dialog>;
}
