import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useModuleTranslation } from '@/modules/localization';
import { governanceApi } from '../../api';
import type { GovernanceSourceVersion } from '../../types';

export function TemporalCandidatesPanel({ programId, sourceId, version, onChanged }: Readonly<{ programId: string; sourceId: string; version: GovernanceSourceVersion; onChanged: () => void }>): JSX.Element {
  const { t } = useModuleTranslation('governance'); const [corrections, setCorrections] = useState<Record<string, string>>({});
  const candidates = useQuery({ queryKey: ['governance', 'temporal-candidates', programId, sourceId, version.id], queryFn: () => governanceApi.listTemporalCandidates(programId, sourceId, version.id), refetchInterval: 3_000 });
  const analysis = useQuery({ queryKey: ['governance', 'temporal-analysis', programId, sourceId, version.id], queryFn: () => governanceApi.getTemporalAnalysisStatus(programId, sourceId, version.id), refetchInterval: (query) => { const job = query.state.data; return job && (['pending', 'running'].includes(job.status) || (job.status === 'failed' && job.attempts < 5)) ? 3_000 : false; } });
  const run = useMutation({ mutationFn: () => governanceApi.runTemporalAnalysis(programId, sourceId, version.id), onSuccess: () => { void candidates.refetch(); void analysis.refetch(); } });
  const decide = useMutation({ mutationFn: ({ id, action, correctedValue }: { id: string; action: 'confirm' | 'correct' | 'reject'; correctedValue?: string }) => governanceApi.decideTemporalCandidate(programId, sourceId, version.id, id, { action, correctedValue }), onSuccess: () => { void candidates.refetch(); onChanged(); } });
  const records = candidates.data ?? [];
  const hasError = candidates.isError || analysis.isError || run.isError || decide.isError || analysis.data?.status === 'failed';
  return <section className='grid gap-3 rounded-xl border p-3' aria-labelledby='temporal-candidates-title'><div className='flex flex-wrap items-center justify-between gap-2'><div><h3 id='temporal-candidates-title' className='text-sm font-semibold'>{t('sourcePassport.temporal.title')}</h3><p className='text-xs text-muted-foreground'>{t('sourcePassport.temporal.description')}</p></div><Button type='button' size='sm' variant='outline' disabled={run.isPending || version.technicalStatus !== 'ready'} onClick={() => run.mutate()}>{run.isPending ? t('sourcePassport.temporal.starting') : t('sourcePassport.temporal.run')}</Button></div>{hasError && <p role='alert' className='text-sm text-destructive'>{t('sourcePassport.temporal.error')}</p>}{records.length === 0 ? <p className='text-sm text-muted-foreground'>{t('sourcePassport.temporal.empty')}</p> : records.map((record) => <article key={record.id} className='grid gap-2 rounded-lg border p-3'><div className='flex flex-wrap items-center justify-between gap-2'><p className='text-sm font-medium'>{t(`sourcePassport.temporal.field.${record.candidate.field}`)}: {record.candidate.value ?? record.candidate.mode}</p><span className='rounded-full bg-muted px-2 py-1 text-xs'>{t(`sourcePassport.temporal.status.${record.decisionStatus}`)}</span></div><p className='text-xs text-muted-foreground'>{record.candidate.reasoningSummary} · {Math.round(record.candidate.confidence * 100)}%</p>{record.validation.issues.map((issue) => <p key={issue.code} className='text-xs text-amber-700 dark:text-amber-300'>{issue.message}</p>)}{record.evidence.map((evidence) => <blockquote key={evidence.id} className='border-l-2 pl-3 text-xs'><p>{evidence.excerpt}</p><footer className='mt-1 text-muted-foreground'>{t('sourcePassport.temporal.location', { page: evidence.page ?? '—', section: evidence.sectionId ?? evidence.blockId ?? '—' })}</footer></blockquote>)}{record.decisionStatus === 'pending' && <div className='flex flex-wrap gap-2'><Button type='button' size='sm' onClick={() => decide.mutate({ id: record.id, action: 'confirm' })}>{t('sourcePassport.temporal.confirm')}</Button><Button type='button' size='sm' variant='outline' onClick={() => decide.mutate({ id: record.id, action: 'reject' })}>{t('sourcePassport.temporal.reject')}</Button><Input className='h-9 min-w-40 flex-1' aria-label={t('sourcePassport.temporal.correctedValue')} value={corrections[record.id] ?? ''} onChange={(event) => setCorrections((current) => ({ ...current, [record.id]: event.target.value }))} placeholder={t('sourcePassport.temporal.correctedValue')} /><Button type='button' size='sm' variant='secondary' disabled={!corrections[record.id]} onClick={() => decide.mutate({ id: record.id, action: 'correct', correctedValue: corrections[record.id] })}>{t('sourcePassport.temporal.correct')}</Button></div>}</article>)}</section>;
}
