import { useEffect, useState } from 'react';
import { ArrowRight, Loader2, Network, Plus, Sparkles } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { showError } from '@/lib/notifications';
import { useModuleTranslation } from '@/modules/localization';
import { semanticModelApi } from '../api';
import type { SemanticModel } from '../types';

export function WorkspaceSemanticModelPage() {
  const {id}=useParams();const {t}=useModuleTranslation('semantic-model');const navigate=useNavigate();const [models,setModels]=useState<SemanticModel[]|null>(null);
  useEffect(()=>{if(!id)return;void semanticModelApi.workspaceModels(id).then(async(items)=>{if(!items.some((item)=>item.originWorkspaceId===id)){const ensured=await semanticModelApi.ensureWorkspaceDefault(id);setModels([ensured,...items]);}else setModels(items);}).catch((error)=>{showError(t('workspace.loadError'),{description:error instanceof Error?error.message:undefined});setModels([]);});},[id,t]);
  if(!models)return <div className='flex min-h-80 items-center justify-center'><Loader2 className='h-7 w-7 animate-spin text-primary' /></div>;
  const defaultModel=models.find((item)=>item.originWorkspaceId===id);const others=models.filter((item)=>item.id!==defaultModel?.id);
  return <main className='min-h-full px-5 py-8 sm:px-10'><div className='mx-auto max-w-5xl space-y-8'><header className='flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between'><div><div className='flex items-center gap-2 text-sm font-medium text-primary'><Sparkles className='h-4 w-4' />{t('workspace.eyebrow')}</div><h1 className='mt-2 text-3xl font-semibold'>{t('workspace.title')}</h1><p className='mt-2 text-muted-foreground'>{t('workspace.description')}</p></div><Button variant='outline' asChild><Link to={`/workspace/${id}`}>{t('workspace.documents')}</Link></Button></header>{defaultModel&&<Card className='overflow-hidden border-sky-400/40'><div className='h-1 bg-sky-500' /><CardHeader><div className='flex items-start gap-3'><div className='rounded-xl bg-sky-500/10 p-3 text-sky-600'><Sparkles className='h-5 w-5' /></div><div><CardTitle>{defaultModel.name}</CardTitle><p className='mt-1 text-sm text-muted-foreground'>{t('workspace.defaultDescription')}</p></div></div></CardHeader><CardContent><Button onClick={()=>navigate(`/semantic-models/${defaultModel.id}`)}>{t('workspace.openDefault')}<ArrowRight className='ml-2 h-4 w-4' /></Button></CardContent></Card>}<section><div className='mb-4 flex items-center justify-between'><div><h2 className='text-lg font-semibold'>{t('workspace.otherModels')}</h2><p className='text-sm text-muted-foreground'>{t('workspace.otherModelsDescription')}</p></div><Button asChild variant='outline'><Link to='/semantic-models'><Plus className='mr-2 h-4 w-4' />{t('workspace.browse')}</Link></Button></div>{others.length?<div className='grid gap-4 sm:grid-cols-2'>{others.map((item)=><button key={item.id} className='flex items-center gap-3 rounded-2xl border bg-card p-4 text-left hover:border-primary/40' onClick={()=>navigate(`/semantic-models/${item.id}`)}><Network className='h-5 w-5 text-primary' /><div className='min-w-0 flex-1'><p className='truncate font-medium'>{item.name}</p><p className='truncate text-xs text-muted-foreground'>{item.description}</p></div><ArrowRight className='h-4 w-4' /></button>)}</div>:<div className='rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground'>{t('workspace.noOtherModels')}</div>}</section></div></main>;
}
