import { useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useModuleTranslation } from '@/modules/localization';
import { governanceApi } from '../../api';

export function TemporalCandidatesPanel({ programId, documentId, indexingStatus, onChanged }: Readonly<{ programId: string; documentId: string; indexingStatus: string; onChanged: () => void }>): JSX.Element {
  const { t } = useModuleTranslation('governance');
  const [corrections, setCorrections] = useState<Record<string, string>>({});
  const candidates = useQuery({ queryKey: ['governance', 'temporal-candidates', programId, documentId], queryFn: () => governanceApi.listTemporalCandidates(programId, documentId), refetchInterval: 3_000 });
  const analysis = useQuery({ queryKey: ['governance', 'temporal-analysis', programId, documentId], queryFn: () => governanceApi.getTemporalAnalysisStatus(programId, documentId), refetchInterval: (query) => query.state.data && ['pending', 'running'].includes(query.state.data.status) ? 3_000 : false });
  const run = useMutation({ mutationFn: () => governanceApi.runTemporalAnalysis(programId, documentId), onSuccess: () => { void candidates.refetch(); void analysis.refetch(); } });
  const decide = useMutation({ mutationFn: ({ id, action, correctedValue }: { id: string; action: 'confirm' | 'correct' | 'reject'; correctedValue?: string }) => governanceApi.decideTemporalCandidate(programId, documentId, id, { action, correctedValue }), onSuccess: () => { void candidates.refetch(); onChanged(); } });
  const records = candidates.data ?? [];
  const hasError = candidates.isError || analysis.isError || run.isError || decide.isError || analysis.data?.status === 'failed';
  return <section className='grid gap-3 rounded-xl border p-3'><div className='flex flex-wrap items-center justify-between gap-2'><div><h3 className='text-sm font-semibold'>{t('documentPassport.temporalTitle')}</h3><p className='text-xs text-muted-foreground'>{t('documentPassport.temporalDescription')}</p></div><Button type='button' size='sm' variant='outline' disabled={run.isPending || indexingStatus !== 'ready'} onClick={() => run.mutate()}>{run.isPending ? t('documentPassport.starting') : t('documentPassport.searchEvidence')}</Button></div>{hasError && <p role='alert' className='text-sm text-destructive'>{t('documentPassport.temporalError')}</p>}{records.length === 0 ? <p className='text-sm text-muted-foreground'>{t('documentPassport.noCandidates')}</p> : records.map((record) => <article key={record.id} className='grid gap-2 rounded-lg border p-3'><div className='flex items-center justify-between gap-2'><p className='text-sm font-medium'>{record.candidate.field}: {record.candidate.value ?? record.candidate.mode}</p><span className='rounded-full bg-muted px-2 py-1 text-xs'>{record.decisionStatus}</span></div><p className='text-xs text-muted-foreground'>{record.candidate.reasoningSummary}</p>{record.evidence.map((evidence) => <blockquote key={evidence.id} className='border-l-2 pl-3 text-xs'>{evidence.excerpt}</blockquote>)}{record.decisionStatus === 'pending' && <div className='flex flex-wrap gap-2'><Button size='sm' onClick={() => decide.mutate({ id: record.id, action: 'confirm' })}>{t('documentPassport.confirm')}</Button><Button size='sm' variant='outline' onClick={() => decide.mutate({ id: record.id, action: 'reject' })}>{t('documentPassport.reject')}</Button><Input className='h-8 min-w-40 flex-1' value={corrections[record.id] ?? ''} onChange={(event) => setCorrections((current) => ({ ...current, [record.id]: event.target.value }))} placeholder={t('documentPassport.correctedValue')} /><Button size='sm' variant='outline' disabled={!corrections[record.id]} onClick={() => decide.mutate({ id: record.id, action: 'correct', correctedValue: corrections[record.id] })}>{t('documentPassport.correct')}</Button></div>}</article>)}</section>;
}
