/**
 * Canonical React/Vite starter revision seeded in Ceph.
 * Manifest: appbuilder/manifests/_system/starter_react_vite_v3.json
 * Blobs:    appbuilder/blobs/sha256/<aa>/<fullsha>
 *
 * Auto-generated by scripts/publish-starter-to-ceph.ts — do not edit manually.
 */
export const STARTER_REACT_VITE_V3_REVISION_ID = 'starter_react_vite_v3';

export const STARTER_REACT_VITE_V3_MANIFEST_KEY =
  'appbuilder/manifests/_system/starter_react_vite_v3.json';

export interface StarterManifestFile {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

export const STARTER_REACT_VITE_V3_FILES: readonly StarterManifestFile[] = [
  {
    path: 'index.html',
    sha256: '1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    objectKey: 'appbuilder/blobs/sha256/10/1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    size: 300,
  },
  {
    path: 'package.json',
    sha256: 'd047cd410032302339b315e84e9916cfdcdb0899a974f29e305520e60c336255',
    objectKey: 'appbuilder/blobs/sha256/d0/d047cd410032302339b315e84e9916cfdcdb0899a974f29e305520e60c336255',
    size: 619,
  },
  {
    path: 'postcss.config.js',
    sha256: 'e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    objectKey: 'appbuilder/blobs/sha256/e3/e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    size: 81,
  },
  {
    path: 'src/App.css',
    sha256: 'feba8cc42a281b52bd438215b86cdc7bdae3bcf39c57dccf9cf7b0c4b120c73e',
    objectKey: 'appbuilder/blobs/sha256/fe/feba8cc42a281b52bd438215b86cdc7bdae3bcf39c57dccf9cf7b0c4b120c73e',
    size: 60,
  },
  {
    path: 'src/App.jsx',
    sha256: '753b51350f8a7a057d297a987aabf04fa3168a0ce5354ba88338744ebf45df47',
    objectKey: 'appbuilder/blobs/sha256/75/753b51350f8a7a057d297a987aabf04fa3168a0ce5354ba88338744ebf45df47',
    size: 140,
  },
  {
    path: 'src/AppRouter.tsx',
    sha256: 'f6b1e6cb63b440014f4362b6ebb481540a9aa75f6f9f7287d4a0e6525257a23a',
    objectKey: 'appbuilder/blobs/sha256/f6/f6b1e6cb63b440014f4362b6ebb481540a9aa75f6f9f7287d4a0e6525257a23a',
    size: 1687,
  },
  {
    path: 'src/components/auth/ProtectedRoute.tsx',
    sha256: '6a2488a508e9e3d45a5732b249fb89e695aeb2c846558c226332371bb3970b31',
    objectKey: 'appbuilder/blobs/sha256/6a/6a2488a508e9e3d45a5732b249fb89e695aeb2c846558c226332371bb3970b31',
    size: 689,
  },
  {
    path: 'src/components/ui/button.tsx',
    sha256: '884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    objectKey: 'appbuilder/blobs/sha256/88/884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    size: 524,
  },
  {
    path: 'src/components/ui/card.tsx',
    sha256: '9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    objectKey: 'appbuilder/blobs/sha256/9b/9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    size: 1014,
  },
  {
    path: 'src/components/ui/input.tsx',
    sha256: 'f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    objectKey: 'appbuilder/blobs/sha256/f4/f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    size: 483,
  },
  {
    path: 'src/components/ui/label.tsx',
    sha256: 'de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    objectKey: 'appbuilder/blobs/sha256/de/de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    size: 256,
  },
  {
    path: 'src/index.css',
    sha256: 'ae9c8245d09fbbee69711142d745d5d595d049a5f70b139a2f09db54ecd36878',
    objectKey: 'appbuilder/blobs/sha256/ae/ae9c8245d09fbbee69711142d745d5d595d049a5f70b139a2f09db54ecd36878',
    size: 581,
  },
  {
    path: 'src/lib/app-base.ts',
    sha256: '89a1a6155979076a070993b20e01e22090f073939d44cd26c50b9574227943bb',
    objectKey: 'appbuilder/blobs/sha256/89/89a1a6155979076a070993b20e01e22090f073939d44cd26c50b9574227943bb',
    size: 1749,
  },
  {
    path: 'src/lib/utils.ts',
    sha256: '9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    objectKey: 'appbuilder/blobs/sha256/93/9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    size: 169,
  },
  {
    path: 'src/lib/yellowmind-auth.tsx',
    sha256: '9fccafd85b174518ab64fa1f15370108e5baf98951ef16799267a97186fe6453',
    objectKey: 'appbuilder/blobs/sha256/9f/9fccafd85b174518ab64fa1f15370108e5baf98951ef16799267a97186fe6453',
    size: 8870,
  },
  {
    path: 'src/lib/yellowmind-data.ts',
    sha256: '67416f527cd687a69fb708d6418cb2eb062ef9639db97a843914eb1abd66841d',
    objectKey: 'appbuilder/blobs/sha256/67/67416f527cd687a69fb708d6418cb2eb062ef9639db97a843914eb1abd66841d',
    size: 7016,
  },
  {
    path: 'src/main.jsx',
    sha256: '79a45ec3ccdf44a1bac5a4f674b737669496d67b220e995a4177360f1970ee2c',
    objectKey: 'appbuilder/blobs/sha256/79/79a45ec3ccdf44a1bac5a4f674b737669496d67b220e995a4177360f1970ee2c',
    size: 252,
  },
  {
    path: 'src/pages/AuthPages.tsx',
    sha256: '8d8d2f2221dea99e073f0610126300d012497b2fea0fc4f72d651d7416649fad',
    objectKey: 'appbuilder/blobs/sha256/8d/8d8d2f2221dea99e073f0610126300d012497b2fea0fc4f72d651d7416649fad',
    size: 5500,
  },
  {
    path: 'src/vite-env.d.ts',
    sha256: '65996936fbb042915f7b74a200fcdde7e410f32a669b1ab9597cfaa4b0faddb5',
    objectKey: 'appbuilder/blobs/sha256/65/65996936fbb042915f7b74a200fcdde7e410f32a669b1ab9597cfaa4b0faddb5',
    size: 38,
  },
  {
    path: 'tailwind.config.js',
    sha256: 'ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    objectKey: 'appbuilder/blobs/sha256/ef/ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    size: 700,
  },
  {
    path: 'tsconfig.json',
    sha256: '7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    objectKey: 'appbuilder/blobs/sha256/7c/7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    size: 426,
  },
  {
    path: 'vite.config.js',
    sha256: 'a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    objectKey: 'appbuilder/blobs/sha256/a3/a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    size: 388,
  },
] as const;
