/**
 * Canonical React/Vite starter revision seeded in Ceph.
 * Manifest: appbuilder/manifests/_system/starter_react_vite_v6.json
 * Blobs:    appbuilder/blobs/sha256/<aa>/<fullsha>
 *
 * Auto-generated by scripts/publish-starter-to-ceph.ts — do not edit manually.
 */
export const STARTER_REACT_VITE_V6_REVISION_ID = 'starter_react_vite_v6';

export const STARTER_REACT_VITE_V6_MANIFEST_KEY =
  'appbuilder/manifests/_system/starter_react_vite_v6.json';

export interface StarterManifestFile {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

export const STARTER_REACT_VITE_V6_FILES: readonly StarterManifestFile[] = [
  {
    path: 'index.html',
    sha256: '1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    objectKey: 'appbuilder/blobs/sha256/10/1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    size: 300,
  },
  {
    path: 'package.json',
    sha256: '0e6f55406e5e6d4ef560dcf24a4b8f8b3a49f029931e1282f889508c35bca533',
    objectKey: 'appbuilder/blobs/sha256/0e/0e6f55406e5e6d4ef560dcf24a4b8f8b3a49f029931e1282f889508c35bca533',
    size: 645,
  },
  {
    path: 'postcss.config.js',
    sha256: 'e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    objectKey: 'appbuilder/blobs/sha256/e3/e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    size: 81,
  },
  {
    path: 'public/brand/yellowsys-logo.svg',
    sha256: 'e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    objectKey: 'appbuilder/blobs/sha256/e5/e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    size: 3394,
  },
  {
    path: 'src/App.css',
    sha256: '91700ae3c78878a4de3b4a6dc394967f2e0330381da7ce168f0619d2cfddfd31',
    objectKey: 'appbuilder/blobs/sha256/91/91700ae3c78878a4de3b4a6dc394967f2e0330381da7ce168f0619d2cfddfd31',
    size: 76,
  },
  {
    path: 'src/App.jsx',
    sha256: '273e2bb10d7e2d86725fd3c6f5a6f7db9922e0aff4fbe327e36927b3f1c6f0e7',
    objectKey: 'appbuilder/blobs/sha256/27/273e2bb10d7e2d86725fd3c6f5a6f7db9922e0aff4fbe327e36927b3f1c6f0e7',
    size: 3819,
  },
  {
    path: 'src/AppRouter.tsx',
    sha256: '549a66259b250e669aa696e2724182f6c686bbb7f0e33336797166dc744cdc43',
    objectKey: 'appbuilder/blobs/sha256/54/549a66259b250e669aa696e2724182f6c686bbb7f0e33336797166dc744cdc43',
    size: 1925,
  },
  {
    path: 'src/components/auth/ProtectedRoute.tsx',
    sha256: '42f9ea86e2898dbd35d3375cbf35166fe320c310d560509dff958302b81f3376',
    objectKey: 'appbuilder/blobs/sha256/42/42f9ea86e2898dbd35d3375cbf35166fe320c310d560509dff958302b81f3376',
    size: 1115,
  },
  {
    path: 'src/components/ui/button.tsx',
    sha256: '884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    objectKey: 'appbuilder/blobs/sha256/88/884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    size: 524,
  },
  {
    path: 'src/components/ui/card.tsx',
    sha256: '9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    objectKey: 'appbuilder/blobs/sha256/9b/9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    size: 1014,
  },
  {
    path: 'src/components/ui/input.tsx',
    sha256: 'f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    objectKey: 'appbuilder/blobs/sha256/f4/f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    size: 483,
  },
  {
    path: 'src/components/ui/label.tsx',
    sha256: 'de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    objectKey: 'appbuilder/blobs/sha256/de/de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    size: 256,
  },
  {
    path: 'src/index.css',
    sha256: '6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    objectKey: 'appbuilder/blobs/sha256/6a/6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    size: 1633,
  },
  {
    path: 'src/lib/app-base.ts',
    sha256: '304dbd16c89ba9f759187665ebbaace0d10aa59d1f5ca50a9350cecdacd1262d',
    objectKey: 'appbuilder/blobs/sha256/30/304dbd16c89ba9f759187665ebbaace0d10aa59d1f5ca50a9350cecdacd1262d',
    size: 3513,
  },
  {
    path: 'src/lib/utils.ts',
    sha256: '9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    objectKey: 'appbuilder/blobs/sha256/93/9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    size: 169,
  },
  {
    path: 'src/lib/yellowmind-ai.ts',
    sha256: '104ce4df2f86fa97986a9a3268e84ca807dcaf0c61b5b1382f18bc16cb493cae',
    objectKey: 'appbuilder/blobs/sha256/10/104ce4df2f86fa97986a9a3268e84ca807dcaf0c61b5b1382f18bc16cb493cae',
    size: 13929,
  },
  {
    path: 'src/lib/yellowmind-auth.tsx',
    sha256: 'a0efac72eddb419906d0bf4d231a6bd26aa2e01a46b15a609a5f947715128c94',
    objectKey: 'appbuilder/blobs/sha256/a0/a0efac72eddb419906d0bf4d231a6bd26aa2e01a46b15a609a5f947715128c94',
    size: 11633,
  },
  {
    path: 'src/lib/yellowmind-data.ts',
    sha256: '6393b67e141c7b94f420b572efc2b2e34c800fc5c06222fe5f19d68ba6532148',
    objectKey: 'appbuilder/blobs/sha256/63/6393b67e141c7b94f420b572efc2b2e34c800fc5c06222fe5f19d68ba6532148',
    size: 8486,
  },
  {
    path: 'src/lib/ym-diag.ts',
    sha256: '35f0e01177befaa7b31e3a4dde3784df55f40a8930daf5f8b99005921349be84',
    objectKey: 'appbuilder/blobs/sha256/35/35f0e01177befaa7b31e3a4dde3784df55f40a8930daf5f8b99005921349be84',
    size: 5883,
  },
  {
    path: 'src/main.jsx',
    sha256: '88822af3667b847356ee51d4a70dd376d255f7f5bbcd334c989019095f9801fd',
    objectKey: 'appbuilder/blobs/sha256/88/88822af3667b847356ee51d4a70dd376d255f7f5bbcd334c989019095f9801fd',
    size: 308,
  },
  {
    path: 'src/pages/AuthPages.tsx',
    sha256: '6b75548870838240f13f5d4952c85524970763f714807186afafa25968b8dbe6',
    objectKey: 'appbuilder/blobs/sha256/6b/6b75548870838240f13f5d4952c85524970763f714807186afafa25968b8dbe6',
    size: 15623,
  },
  {
    path: 'src/vite-env.d.ts',
    sha256: '9acbb53980604a2e244325f67e911f24940e30c1afcc4f51763bbf11272561f4',
    objectKey: 'appbuilder/blobs/sha256/9a/9acbb53980604a2e244325f67e911f24940e30c1afcc4f51763bbf11272561f4',
    size: 443,
  },
  {
    path: 'tailwind.config.js',
    sha256: 'ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    objectKey: 'appbuilder/blobs/sha256/ef/ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    size: 700,
  },
  {
    path: 'tsconfig.json',
    sha256: '7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    objectKey: 'appbuilder/blobs/sha256/7c/7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    size: 426,
  },
  {
    path: 'vite.config.js',
    sha256: 'a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    objectKey: 'appbuilder/blobs/sha256/a3/a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    size: 388,
  },
] as const;
