/**
 * Canonical React/Vite starter revision seeded in Ceph.
 * Manifest: appbuilder/manifests/_system/starter_react_vite_v6.json
 * Blobs:    appbuilder/blobs/sha256/<aa>/<fullsha>
 *
 * Auto-generated by scripts/publish-starter-to-ceph.ts — do not edit manually.
 */
export const starter_react_vite_v6_REVISION_ID = 'starter_react_vite_v6';

export const starter_react_vite_v6_MANIFEST_KEY =
  'appbuilder/manifests/_system/starter_react_vite_v6.json';

export interface StarterManifestFile {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

export const starter_react_vite_v6_FILES: readonly StarterManifestFile[] = [
  {
    path: 'index.html',
    sha256: '1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    objectKey: 'appbuilder/blobs/sha256/10/1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    size: 300,
  },
  {
    path: 'package.json',
    sha256: 'd047cd410032302339b315e84e9916cfdcdb0899a974f29e305520e60c336255',
    objectKey: 'appbuilder/blobs/sha256/d0/d047cd410032302339b315e84e9916cfdcdb0899a974f29e305520e60c336255',
    size: 619,
  },
  {
    path: 'postcss.config.js',
    sha256: 'e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    objectKey: 'appbuilder/blobs/sha256/e3/e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    size: 81,
  },
  {
    path: 'public/brand/yellowsys-logo.svg',
    sha256: 'e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    objectKey: 'appbuilder/blobs/sha256/e5/e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    size: 3394,
  },
  {
    path: 'src/App.css',
    sha256: 'feba8cc42a281b52bd438215b86cdc7bdae3bcf39c57dccf9cf7b0c4b120c73e',
    objectKey: 'appbuilder/blobs/sha256/fe/feba8cc42a281b52bd438215b86cdc7bdae3bcf39c57dccf9cf7b0c4b120c73e',
    size: 60,
  },
  {
    path: 'src/App.jsx',
    sha256: '753b51350f8a7a057d297a987aabf04fa3168a0ce5354ba88338744ebf45df47',
    objectKey: 'appbuilder/blobs/sha256/75/753b51350f8a7a057d297a987aabf04fa3168a0ce5354ba88338744ebf45df47',
    size: 140,
  },
  {
    path: 'src/AppRouter.tsx',
    sha256: 'ee5f5d8f07355c920a4a069405bb99dec45f42289e518e14e59cd812abf2cc5c',
    objectKey: 'appbuilder/blobs/sha256/ee/ee5f5d8f07355c920a4a069405bb99dec45f42289e518e14e59cd812abf2cc5c',
    size: 1612,
  },
  {
    path: 'src/components/auth/ProtectedRoute.tsx',
    sha256: '5e24405589cc386ae953f92a8dc2167bf018f7122100f995e3ad566408ec85b3',
    objectKey: 'appbuilder/blobs/sha256/5e/5e24405589cc386ae953f92a8dc2167bf018f7122100f995e3ad566408ec85b3',
    size: 733,
  },
  {
    path: 'src/components/ui/button.tsx',
    sha256: '884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    objectKey: 'appbuilder/blobs/sha256/88/884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    size: 524,
  },
  {
    path: 'src/components/ui/card.tsx',
    sha256: '9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    objectKey: 'appbuilder/blobs/sha256/9b/9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    size: 1014,
  },
  {
    path: 'src/components/ui/input.tsx',
    sha256: 'f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    objectKey: 'appbuilder/blobs/sha256/f4/f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    size: 483,
  },
  {
    path: 'src/components/ui/label.tsx',
    sha256: 'de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    objectKey: 'appbuilder/blobs/sha256/de/de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    size: 256,
  },
  {
    path: 'src/index.css',
    sha256: '6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    objectKey: 'appbuilder/blobs/sha256/6a/6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    size: 1633,
  },
  {
    path: 'src/lib/app-base.ts',
    sha256: 'b9cca2e0ad079d58270f8abfc6ace1f85c532851d9c4a6c9ce5111f93270e8b8',
    objectKey: 'appbuilder/blobs/sha256/b9/b9cca2e0ad079d58270f8abfc6ace1f85c532851d9c4a6c9ce5111f93270e8b8',
    size: 2059,
  },
  {
    path: 'src/lib/utils.ts',
    sha256: '9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    objectKey: 'appbuilder/blobs/sha256/93/9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    size: 169,
  },
  {
    path: 'src/lib/yellowmind-auth.tsx',
    sha256: 'fcc24c5b6c8132ab5dda7f3d4ae4431c0dd08b6649a89d6c335c52f713dda1be',
    objectKey: 'appbuilder/blobs/sha256/fc/fcc24c5b6c8132ab5dda7f3d4ae4431c0dd08b6649a89d6c335c52f713dda1be',
    size: 10470,
  },
  {
    path: 'src/lib/yellowmind-data.ts',
    sha256: '98f74399b8d2222e5b11d997b8035a7e158e5605c5dc87ad29ff4a5f47f4aeb6',
    objectKey: 'appbuilder/blobs/sha256/98/98f74399b8d2222e5b11d997b8035a7e158e5605c5dc87ad29ff4a5f47f4aeb6',
    size: 7254,
  },
  {
    path: 'src/main.jsx',
    sha256: '79a45ec3ccdf44a1bac5a4f674b737669496d67b220e995a4177360f1970ee2c',
    objectKey: 'appbuilder/blobs/sha256/79/79a45ec3ccdf44a1bac5a4f674b737669496d67b220e995a4177360f1970ee2c',
    size: 252,
  },
  {
    path: 'src/pages/AuthPages.tsx',
    sha256: 'b64a464bf18eccec124145ec628c80b6296205328385cd6199b2d5ff2fe61056',
    objectKey: 'appbuilder/blobs/sha256/b6/b64a464bf18eccec124145ec628c80b6296205328385cd6199b2d5ff2fe61056',
    size: 14277,
  },
  {
    path: 'src/vite-env.d.ts',
    sha256: '65996936fbb042915f7b74a200fcdde7e410f32a669b1ab9597cfaa4b0faddb5',
    objectKey: 'appbuilder/blobs/sha256/65/65996936fbb042915f7b74a200fcdde7e410f32a669b1ab9597cfaa4b0faddb5',
    size: 38,
  },
  {
    path: 'tailwind.config.js',
    sha256: 'ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    objectKey: 'appbuilder/blobs/sha256/ef/ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    size: 700,
  },
  {
    path: 'tsconfig.json',
    sha256: '7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    objectKey: 'appbuilder/blobs/sha256/7c/7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    size: 426,
  },
  {
    path: 'vite.config.js',
    sha256: 'a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    objectKey: 'appbuilder/blobs/sha256/a3/a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    size: 388,
  },
] as const;
