/**
 * Canonical React/Vite starter revision seeded in Ceph.
 * Manifest: appbuilder/manifests/_system/starter_react_vite_v6.json
 * Blobs:    appbuilder/blobs/sha256/<aa>/<fullsha>
 *
 * Auto-generated by scripts/publish-starter-to-ceph.ts — do not edit manually.
 */
export const STARTER_REACT_VITE_V6_REVISION_ID = 'starter_react_vite_v6';

export const STARTER_REACT_VITE_V6_MANIFEST_KEY =
  'appbuilder/manifests/_system/starter_react_vite_v6.json';

export interface StarterManifestFile {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

export const STARTER_REACT_VITE_V6_FILES: readonly StarterManifestFile[] = [
  {
    path: 'index.html',
    sha256: '1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    objectKey: 'appbuilder/blobs/sha256/10/1014d23e974155d7848ea9798d05321f6b412466791e5fa71c9a375d44507baf',
    size: 300,
  },
  {
    path: 'package.json',
    sha256: '0e6f55406e5e6d4ef560dcf24a4b8f8b3a49f029931e1282f889508c35bca533',
    objectKey: 'appbuilder/blobs/sha256/0e/0e6f55406e5e6d4ef560dcf24a4b8f8b3a49f029931e1282f889508c35bca533',
    size: 645,
  },
  {
    path: 'postcss.config.js',
    sha256: 'e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    objectKey: 'appbuilder/blobs/sha256/e3/e32657baf631d7c5f4dc67b4b2ee0ec8e7d5b3c41860e09cddce7c0377cd80bc',
    size: 81,
  },
  {
    path: 'public/brand/yellowsys-logo.svg',
    sha256: 'e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    objectKey: 'appbuilder/blobs/sha256/e5/e56ea7965a0d5a887dcc07b2052f90ab251875c7d61a5438613cfb9ee90a3e2b',
    size: 3394,
  },
  {
    path: 'src/App.css',
    sha256: 'e3b46bf212aeb659f0c680bca0a9a9b6032c67a39f0563efd8feb64958c06c9c',
    objectKey: 'appbuilder/blobs/sha256/e3/e3b46bf212aeb659f0c680bca0a9a9b6032c67a39f0563efd8feb64958c06c9c',
    size: 77,
  },
  {
    path: 'src/App.jsx',
    sha256: '8d6cb948b128c29a01422a696d54c61b2156fd2d2cc1df3977e9b4186ebabb36',
    objectKey: 'appbuilder/blobs/sha256/8d/8d6cb948b128c29a01422a696d54c61b2156fd2d2cc1df3977e9b4186ebabb36',
    size: 2379,
  },
  {
    path: 'src/AppRouter.tsx',
    sha256: 'a195a5e692907630df552361bce6aced5f078c8d45fab0c8818811411a035158',
    objectKey: 'appbuilder/blobs/sha256/a1/a195a5e692907630df552361bce6aced5f078c8d45fab0c8818811411a035158',
    size: 1816,
  },
  {
    path: 'src/components/auth/ProtectedRoute.tsx',
    sha256: '42f9ea86e2898dbd35d3375cbf35166fe320c310d560509dff958302b81f3376',
    objectKey: 'appbuilder/blobs/sha256/42/42f9ea86e2898dbd35d3375cbf35166fe320c310d560509dff958302b81f3376',
    size: 1115,
  },
  {
    path: 'src/components/ui/button.tsx',
    sha256: '884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    objectKey: 'appbuilder/blobs/sha256/88/884b67691ab230ced7e159f8fe83ed34d42dcca19771172724956a655b08d63c',
    size: 524,
  },
  {
    path: 'src/components/ui/card.tsx',
    sha256: '9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    objectKey: 'appbuilder/blobs/sha256/9b/9b40ca3377c79df73e0969df4c8f064c3990fa573ed8ab1b536f63c2b88efaf7',
    size: 1014,
  },
  {
    path: 'src/components/ui/input.tsx',
    sha256: 'f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    objectKey: 'appbuilder/blobs/sha256/f4/f4936dd5269a61e89c8b3b308c84de0965ad93592b4aaac8bd5253c43117fc8f',
    size: 483,
  },
  {
    path: 'src/components/ui/label.tsx',
    sha256: 'de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    objectKey: 'appbuilder/blobs/sha256/de/de512547a39437c076716b1c489966e825cc1e94d499bc6370e2f170297c4e26',
    size: 256,
  },
  {
    path: 'src/index.css',
    sha256: '6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    objectKey: 'appbuilder/blobs/sha256/6a/6a231568549109e36f565fbfd349380e1a7cbf66706a1bc70c41cbf6875c8e34',
    size: 1633,
  },
  {
    path: 'src/lib/app-base.ts',
    sha256: 'b9cca2e0ad079d58270f8abfc6ace1f85c532851d9c4a6c9ce5111f93270e8b8',
    objectKey: 'appbuilder/blobs/sha256/b9/b9cca2e0ad079d58270f8abfc6ace1f85c532851d9c4a6c9ce5111f93270e8b8',
    size: 2059,
  },
  {
    path: 'src/lib/utils.ts',
    sha256: '9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    objectKey: 'appbuilder/blobs/sha256/93/9304a861c8673bee09e0f12de31773abbde503b02e59dfd74763ddec2e37cf05',
    size: 169,
  },
  {
    path: 'src/lib/yellowmind-ai.ts',
    sha256: 'c33ded9062a1d97d28d5db57e8b32540283d364eee0c3431066ea713473f3dcc',
    objectKey: 'appbuilder/blobs/sha256/c3/c33ded9062a1d97d28d5db57e8b32540283d364eee0c3431066ea713473f3dcc',
    size: 12864,
  },
  {
    path: 'src/lib/yellowmind-auth.tsx',
    sha256: 'cc8e1d3158e88544ec2c15aef0b1d6bdf145c4cbde1993f4766908b1641e5139',
    objectKey: 'appbuilder/blobs/sha256/cc/cc8e1d3158e88544ec2c15aef0b1d6bdf145c4cbde1993f4766908b1641e5139',
    size: 11654,
  },
  {
    path: 'src/lib/yellowmind-data.ts',
    sha256: '9a8073398103f6903161408285563565b06b4ed48f2320e48400378388716a08',
    objectKey: 'appbuilder/blobs/sha256/9a/9a8073398103f6903161408285563565b06b4ed48f2320e48400378388716a08',
    size: 8531,
  },
  {
    path: 'src/lib/ym-diag.ts',
    sha256: '770c715731c56f8befe87a018b3f0c14097f496d4c326d9430f9f41dad118b29',
    objectKey: 'appbuilder/blobs/sha256/77/770c715731c56f8befe87a018b3f0c14097f496d4c326d9430f9f41dad118b29',
    size: 5643,
  },
  {
    path: 'src/main.jsx',
    sha256: '88822af3667b847356ee51d4a70dd376d255f7f5bbcd334c989019095f9801fd',
    objectKey: 'appbuilder/blobs/sha256/88/88822af3667b847356ee51d4a70dd376d255f7f5bbcd334c989019095f9801fd',
    size: 308,
  },
  {
    path: 'src/pages/AuthPages.tsx',
    sha256: '1044a1224bc1f741be41e37080d1916c1bea35ca9353e6c3b4b491c7418a7df6',
    objectKey: 'appbuilder/blobs/sha256/10/1044a1224bc1f741be41e37080d1916c1bea35ca9353e6c3b4b491c7418a7df6',
    size: 16063,
  },
  {
    path: 'src/vite-env.d.ts',
    sha256: '9acbb53980604a2e244325f67e911f24940e30c1afcc4f51763bbf11272561f4',
    objectKey: 'appbuilder/blobs/sha256/9a/9acbb53980604a2e244325f67e911f24940e30c1afcc4f51763bbf11272561f4',
    size: 443,
  },
  {
    path: 'tailwind.config.js',
    sha256: 'ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    objectKey: 'appbuilder/blobs/sha256/ef/ef707b6afd77305af98a11bfc09147df80a00374d299b1b804f126c737ace159',
    size: 700,
  },
  {
    path: 'tsconfig.json',
    sha256: '7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    objectKey: 'appbuilder/blobs/sha256/7c/7cfe69983e00ffb818129b7d796f722aea713f53c841b5bd1652637125034f5c',
    size: 426,
  },
  {
    path: 'vite.config.js',
    sha256: 'a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    objectKey: 'appbuilder/blobs/sha256/a3/a38b046136d4ed68515ffa4febe119a00259752d5e164dc7c0d1515d3c7974cb',
    size: 388,
  },
] as const;
