import asyncio

from fastapi import FastAPI, Request, status
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse, Response
from opentelemetry import trace
from opentelemetry.trace import Span

from .correlation import CorrelationIdMiddleware

from .cors import add_cors
from .logging import add_logging
from .tracing import add_tracing
from ..config.settings import Settings

from src.config.settings import get_settings
app_settings = get_settings()
chat_semaphore = asyncio.Semaphore(app_settings.MAX_CONCURRENCY)
chat_queue = asyncio.Queue(maxsize=app_settings.MAX_QUEUE_LENGTH)




def add_middleware(app: FastAPI, app_settings: Settings) -> None:
    """
    add middleware to fastapi application
    Args:
        app: FastAPI application.
        app_settings: settings of the application

    """
    add_cors(app)
    if app_settings.APPLICATION_INSIGHTS_LOG:
        app.add_middleware(CorrelationIdMiddleware)
    else:
        add_logging(app)
        # the trancing is changing the correlation id !
        add_tracing(app)
    app.add_middleware(ChatQueueMiddleware)


class ChatQueueMiddleware(BaseHTTPMiddleware):

    async def dispatch(self, request: Request, call_next):
        """
        Middleware to manage the request queue and concurrency for the /chat endpoint.

        This middleware intercepts requests to the /chat endpoint, and attempts to add
        them to an asyncio queue. If the queue is full, it returns a 503 Service Unavailable response.
        If the request is successfully added to the queue, it processes the request using a semaphore
        to limit concurrency. Once the request is processed, it is removed from the queue.

        If the request is not for the /chat endpoint, it is passed to the next middleware or endpoint.

        Args:
            request (Request): The incoming request object.
            call_next (Callable): The next middleware or endpoint to call.

        Returns:
            Response: The response generated by the next middleware or endpoint, or a 503 error response
                      if the queue is full.
        """
        if request.url.path == "/chatbots/chat":
            try:
                await chat_queue.put(request)
            except asyncio.QueueFull:
                return JSONResponse(
                    {"detail": "Chat request queue is full, please try again later."},
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                )

            try:
                async with chat_semaphore:
                    chat_queue.get_nowait()
                    response = await call_next(request)
                    return response
            except asyncio.QueueEmpty:
                return JSONResponse(
                    {"detail": "Chat request queue is full, please try again later."},
                    status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                )
        else:
            return await call_next(request)
