export const governanceQueryKeys = {
  all: ['governance'] as const,
  programs: () => [...governanceQueryKeys.all, 'programs'] as const,
  program: (programId: string) => [...governanceQueryKeys.programs(), programId] as const,
  scopes: (programId: string) => [...governanceQueryKeys.program(programId), 'scopes'] as const,
  scopeOverview: (programId: string, scopeId: string) => [...governanceQueryKeys.scopes(programId), scopeId, 'overview'] as const,
  scopeAudience: (programId: string, scopeId: string) => [...governanceQueryKeys.scopes(programId), scopeId, 'audience'] as const,
  availableScopes: () => [...governanceQueryKeys.all, 'available-scopes'] as const,
  documents: (programId: string) => [...governanceQueryKeys.program(programId), 'documents'] as const,
  documentEvents: (programId: string, documentId: string) => [...governanceQueryKeys.documents(programId), documentId, 'events'] as const,
  workspaceBindings: (programId: string) => [...governanceQueryKeys.program(programId), 'workspace-bindings'] as const,
  reconciliationRun: (programId: string, bindingId: string, runId: string) => [...governanceQueryKeys.workspaceBindings(programId), bindingId, 'reconciliation-runs', runId] as const,
  memberships: (programId: string) => [...governanceQueryKeys.program(programId), 'memberships'] as const,
  deployments: (programId: string) => [...governanceQueryKeys.program(programId), 'deployments'] as const,
  deployment: (deploymentId: string) => [...governanceQueryKeys.all, 'deployment', deploymentId] as const,
  revisions: (deploymentId: string) => [...governanceQueryKeys.deployment(deploymentId), 'revisions'] as const,
  readiness: (deploymentId: string) => [...governanceQueryKeys.deployment(deploymentId), 'readiness'] as const,
  dryRuns: (deploymentId: string) => [...governanceQueryKeys.deployment(deploymentId), 'dry-runs'] as const,
  metrics: (programId: string) => [...governanceQueryKeys.program(programId), 'metrics'] as const,
  knowledge: (programId: string, scopeId?: string) => [...governanceQueryKeys.program(programId), 'knowledge', scopeId ?? 'all'] as const,
  knowledgeHealth: (programId: string, scopeId?: string) => [...governanceQueryKeys.knowledge(programId, scopeId), 'health'] as const,
  knowledgeAlerts: (programId: string, scopeId?: string) => [...governanceQueryKeys.knowledge(programId, scopeId), 'alerts'] as const,
  knowledgeRecommendations: (programId: string, scopeId?: string) => [...governanceQueryKeys.knowledge(programId, scopeId), 'recommendations'] as const,
  metadataCandidates: (programId: string, scopeId?: string) => [...governanceQueryKeys.knowledge(programId, scopeId), 'metadata-candidates'] as const,
};
