/**
 * Admin Module Constants
 */

import {
  Users,
  Shield,
  FileText,
  CreditCard,
  BarChart3,
  Settings,
  ScrollText,
  Flag,
  Cpu,
  Wrench,
  Puzzle,
  Bot,
} from 'lucide-react';
import type { AdminMenuItem } from './types';

// Permissions that grant admin panel access
export const ADMIN_ACCESS_PERMISSIONS = [
  'admin.*',
  'admin.roles.read',
  'admin.roles.manage',
  'admin.audit.read',
  'admin.logs.read',
  '*',
] as const;

// Admin menu items with their required permissions
export const ADMIN_MENU_ITEMS: AdminMenuItem[] = [
  {
    id: 'users',
    label: 'Users',
    labelKey: 'menu.users.label',
    path: '/admin/users',
    icon: Users,
    permissions: ['users.read', 'users.*', '*'],
    description: 'Manage user accounts',
    descriptionKey: 'menu.users.description',
  },
  {
    id: 'roles',
    label: 'Roles',
    labelKey: 'menu.roles.label',
    path: '/admin/roles',
    icon: Shield,
    permissions: ['admin.roles.read', 'admin.*', '*'],
    description: 'Configure roles and permissions',
    descriptionKey: 'menu.roles.description',
  },
  {
    id: 'audit',
    label: 'Audit Logs',
    labelKey: 'menu.audit.label',
    path: '/admin/audit',
    icon: FileText,
    permissions: ['admin.audit.read', 'admin.*', '*'],
    description: 'View system audit logs',
    descriptionKey: 'menu.audit.description',
  },
  {
    id: 'logs',
    label: 'System Logs',
    labelKey: 'menu.logs.label',
    path: '/admin/logs',
    icon: ScrollText,
    permissions: ['admin.logs.read', 'admin.*', '*'],
    description: 'View application logs',
    descriptionKey: 'menu.logs.description',
  },
  {
    id: 'plans',
    label: 'Plans',
    labelKey: 'menu.plans.label',
    path: '/admin/plans',
    icon: CreditCard,
    permissions: ['plans.read_all', 'plans.*', '*'],
    description: 'Manage subscription plans',
    descriptionKey: 'menu.plans.description',
  },
  {
    id: 'reports',
    label: 'Reports',
    labelKey: 'menu.reports.label',
    path: '/admin/reports',
    icon: Flag,
    permissions: ['reports.read', 'reports.*', '*'],
    description: 'View and manage reported messages',
    descriptionKey: 'menu.reports.description',
  },
  {
    id: 'models',
    label: 'Models',
    labelKey: 'menu.models.label',
    path: '/admin/models',
    icon: Cpu,
    permissions: ['models.read_all', 'models.*', '*'],
    description: 'Manage AI models',
    descriptionKey: 'menu.models.description',
  },
  {
    id: 'agent-types',
    label: 'Agent Types',
    labelKey: 'menu.agentTypes.label',
    path: '/admin/agent-types',
    icon: Puzzle,
    permissions: ['agent_types.read', 'agent_types.*', '*'],
    description: 'Manage agent type configurations',
    descriptionKey: 'menu.agentTypes.description',
  },
  {
    id: 'agents',
    label: 'Default Agents',
    labelKey: 'menu.agents.label',
    path: '/admin/agents',
    icon: Bot,
    permissions: ['agents.read', 'agents.*', '*'],
    description: 'Manage default agents',
    descriptionKey: 'menu.agents.description',
  },
  {
    id: 'playbook-prompts',
    label: 'Playbook Prompts',
    labelKey: 'menu.playbookPrompts.label',
    path: '/admin/playbook-prompts',
    icon: FileText,
    permissions: ['admin.*', '*'],
    description: 'Manage playbook prompt templates',
    descriptionKey: 'menu.playbookPrompts.description',
  },
  {
    id: 'tools',
    label: 'Tools',
    labelKey: 'menu.tools.label',
    path: '/admin/tools',
    icon: Wrench,
    permissions: ['tools.read', 'tools.*', '*'],
    description: 'Manage agent tools',
    descriptionKey: 'menu.tools.description',
  },
  {
    id: 'analytics',
    label: 'Analytics',
    labelKey: 'menu.analytics.label',
    path: '/admin/analytics',
    icon: BarChart3,
    permissions: ['analytics.read', 'analytics.*', '*'],
    description: 'View platform analytics',
    descriptionKey: 'menu.analytics.description',
  },
  {
    id: 'system',
    label: 'System',
    labelKey: 'menu.system.label',
    path: '/admin/system',
    icon: Settings,
    permissions: ['system.maintenance', 'system.registration', 'system.*', '*'],
    description: 'System settings and maintenance',
    descriptionKey: 'menu.system.description',
  },
];
