/**
 * Renders drizzle/0025_cross_schema_fks.sql from the canonical FK_SPECS list
 * (remediation 5.1/5.2). Committed generator — run by hand when the spec list
 * changes, never at build time:
 *
 *   npx ts-node back/scripts/migrate/generate-0025.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import { FK_SPECS } from './fk-specs';

const ANALYZE_SCHEMAS = ['identity', 'authz', 'catalog', 'ops', 'integrations', 'teams', 'channels'];

const header = `-- Cross-schema foreign keys, hygiene and statistics (remediation plan 5.2).
-- GENERATED by scripts/migrate/generate-0025.ts — edit fk-specs.ts and regenerate,
-- never edit this file directly.
--
-- Idempotent: every constraint is created NOT VALID (if missing) and validated
-- in its own lock-safe block, so re-runs on a live database are no-ops.

SET LOCAL lock_timeout = '5s';

`;

const blocks: string[] = [];

blocks.push('-- widget_tokens.created_by had no leading index (remediation R-17).');
blocks.push(`CREATE INDEX IF NOT EXISTS idx_widget_tokens_created_by ON channels.widget_tokens (created_by);
`);

for (const spec of FK_SPECS) {
  blocks.push(`-- ${spec.name} on ${spec.table}
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${spec.name}' AND conrelid = '${spec.table}'::regclass) THEN
    ALTER TABLE ${spec.table} ADD CONSTRAINT ${spec.name} ${spec.definition} NOT VALID;
  END IF;
END $$;
ALTER TABLE ${spec.table} VALIDATE CONSTRAINT ${spec.name};
`);
}

blocks.push('-- Fresh statistics for the new tables (39 of 48 were never analyzed).');
for (const schema of ANALYZE_SCHEMAS) {
  blocks.push(`ANALYZE ${schema}.*;`);
}

const sql = header + blocks.join('\n') + '\n';
const out = path.resolve(__dirname, '..', '..', 'drizzle', '0025_cross_schema_fks.sql');
fs.writeFileSync(out, sql);
console.log(`wrote ${out} (${FK_SPECS.length} FK blocks)`);
