/**
 * Renders drizzle/0037_conversation_app_runtime_fks.sql from FK_SPECS_IN_0037. Committed generator —
 * run by hand when the spec list changes, never at build time:
 *
 *   npx ts-node scripts/migrate/generate-0037.ts
 *
 * Every constraint is added NOT VALID when missing and validated only when its orphan check is empty, so
 * the migration succeeds whatever the data looks like; scripts/migrate/2026-10-conversation-app-runtime-fk.ts
 * validates the rest after the orphans were exported and removed.
 */
import * as fs from 'fs';
import * as path from 'path';
import { FK_SPECS_IN_0037, INDEXES_IN_0037 } from './fk-specs';

const header = `-- Foreign keys of conversation-v2 and app-runtime (roadmap: cross-schema FKs once the data was complete).
-- GENERATED by scripts/migrate/generate-0037.ts — edit fk-specs.ts and regenerate,
-- never edit this file directly.
--
-- Idempotent and safe on dirty data: each constraint is added NOT VALID (enforced for every new write)
-- when missing, and validated in its own block only when no orphan row remains. A constraint that
-- still has orphans stays NOT VALID; scripts/migrate/2026-10-conversation-app-runtime-fk.ts validates
-- it after exporting and removing them (opt-in --delete-orphans). Numbered 0037 after 0036_logs.

SET LOCAL lock_timeout = '5s';

-- Leading indexes for the referencing columns that had none (db:verify check4).
${INDEXES_IN_0037.join('\n')}

`;

const blocks = FK_SPECS_IN_0037.map((spec) => `-- ${spec.name} on ${spec.table}
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '${spec.name}' AND conrelid = '${spec.table}'::regclass) THEN
    ALTER TABLE ${spec.table} ADD CONSTRAINT ${spec.name} ${spec.definition} NOT VALID;
  END IF;
  IF (SELECT c.n FROM (${spec.orphanCheck.replace(/\s+/g, ' ').trim()}) c) = 0 THEN
    ALTER TABLE ${spec.table} VALIDATE CONSTRAINT ${spec.name};
  END IF;
END $$;
`);

const sql = header + blocks.join('\n');
const out = path.resolve(__dirname, '..', '..', 'drizzle', '0037_conversation_app_runtime_fks.sql');
fs.writeFileSync(out, sql);
console.log(`wrote ${out} (${FK_SPECS_IN_0037.length} FK blocks)`);
