import { registerAs } from '@nestjs/config';

export default registerAs('playbook-flow', () => ({
  grpcUrl: process.env.PLAYBOOK_FLOW_GRPC_URL || 'localhost:50051',
  grpcTimeoutMs: parseInt(process.env.PLAYBOOK_FLOW_GRPC_TIMEOUT_MS || '300000', 10),
  maxConcurrentPerUser: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_PER_USER || '10', 10),
  executionQueueMaxDepth: parseInt(process.env.PLAYBOOK_EXECUTION_QUEUE_MAX_DEPTH || '50', 10),
  maxParallelismPerExecution: parseInt(process.env.PLAYBOOK_MAX_PARALLELISM_PER_EXECUTION || '5', 10),
  recursionLimitDefault: parseInt(process.env.PLAYBOOK_RECURSION_LIMIT_DEFAULT || '25', 10),
  recursionLimitMax: parseInt(process.env.PLAYBOOK_RECURSION_LIMIT_MAX || '50', 10),
  pythonWorkerPoolSize: parseInt(process.env.PLAYBOOK_PYTHON_WORKER_POOL_SIZE || '8', 10),
  pythonWorkerMaxInflight: parseInt(process.env.PLAYBOOK_PYTHON_WORKER_MAX_INFLIGHT || '4', 10),
  idempotencyTtlHours: parseInt(process.env.PLAYBOOK_IDEMPOTENCY_TTL_HOURS || '24', 10),
  deltaPatchEnabled: process.env.PLAYBOOK_DELTA_PATCH_ENABLED === 'true',
  baseReadSplitEnabled: process.env.PLAYBOOK_BASE_READ_SPLIT_ENABLED === 'true',
  smartHitlDefaultEnabled: process.env.PLAYBOOK_SMART_HITL_DEFAULT_ENABLED !== 'false',
  tokenBufferEnabled: process.env.PLAYBOOK_TOKEN_BUFFER_ENABLED === 'true',
  tokenBufferFlushIntervalMs: parseInt(process.env.PLAYBOOK_TOKEN_BUFFER_FLUSH_INTERVAL_MS || '750', 10),
  tokenBufferMaxBytes: parseInt(process.env.PLAYBOOK_TOKEN_BUFFER_MAX_BYTES || '4096', 10),
  tokenBufferMaxTaskBytes: parseInt(process.env.PLAYBOOK_TOKEN_BUFFER_MAX_TASK_BYTES || '65536', 10),
  tokenBufferMaxActiveBuffers: parseInt(process.env.PLAYBOOK_TOKEN_BUFFER_MAX_ACTIVE_BUFFERS || '1000', 10),
  executionLeaseEnabled: process.env.PLAYBOOK_EXECUTION_LEASE_ENABLED === 'true',
  executionLeaseTtlMs: parseInt(process.env.PLAYBOOK_EXECUTION_LEASE_TTL_MS || '120000', 10),
  executionLeaseHeartbeatMs: parseInt(process.env.PLAYBOOK_EXECUTION_LEASE_HEARTBEAT_MS || '30000', 10),
  executionStartupTimeoutMs: parseInt(process.env.PLAYBOOK_EXECUTION_STARTUP_TIMEOUT_MS || '180000', 10),
  executionDispatchIntervalMs: parseInt(process.env.PLAYBOOK_EXECUTION_DISPATCH_INTERVAL_MS || '1000', 10),
  queuePositionUpdateThrottleMs: parseInt(process.env.PLAYBOOK_QUEUE_POSITION_UPDATE_THROTTLE_MS || '500', 10),
  maxConcurrentGlobalExecutions: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_GLOBAL_EXECUTIONS || '50', 10),
  maxConcurrentPerFlow: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_PER_FLOW || '5', 10),
  maxConcurrentPerProvider: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_PER_PROVIDER || '25', 10),
  maxConcurrentPerModel: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_PER_MODEL || '10', 10),
  asyncDesignEnabled: process.env.PLAYBOOK_ASYNC_DESIGN_ENABLED === 'true',
  maxConcurrentGlobalDesignOperations: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_GLOBAL_DESIGN_OPERATIONS || '10', 10),
  maxConcurrentUserDesignOperations: parseInt(process.env.PLAYBOOK_MAX_CONCURRENT_USER_DESIGN_OPERATIONS || '3', 10),
}));
