import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Cron, CronExpression } from '@nestjs/schedule';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import { randomUUID } from 'crypto';
import { IntegrationEvent, IntegrationEventDocument } from '../schemas/integration-event.schema';
import { IntegrationEventHandlerRegistryService } from './integration-event-handler-registry.service';
@Injectable()
export class IntegrationEventDispatcherService {
  private readonly instanceId = randomUUID();
  constructor(@InjectModel(IntegrationEvent.name) private readonly eventModel: Model<IntegrationEventDocument>, private readonly registry: IntegrationEventHandlerRegistryService, private readonly config: ConfigService) {}
  @Cron(CronExpression.EVERY_5_SECONDS)
  async dispatch(): Promise<void> { if (!this.config.get<boolean>('dataRoom.outboxDispatchEnabled')) return; for (let i = 0; i < 50; i += 1) { const event = await this.lockNext(); if (!event) return; const handlers = this.registry.forType(event.eventType); const outcomes = await Promise.all(handlers.map((handler) => this.deliver(event, handler))); const registered = new Set(handlers.map((handler) => handler.handlerKey)); const unavailableDelivery = event.deliveries.some((delivery) => delivery.status !== 'completed' && !registered.has(delivery.handlerKey)); const failed = unavailableDelivery || outcomes.some((outcome) => !outcome); const retry = event.attempts < 10; await this.eventModel.updateOne({ _id: event._id, lockOwner: this.instanceId }, { $set: failed ? { status: retry ? 'failed' : 'dead_letter', lastError: unavailableDelivery ? 'A previously failing integration-event handler is unavailable' : 'One or more integration-event handlers failed', nextAttemptAt: new Date(Date.now() + Math.min(300000, 1000 * 2 ** event.attempts)), lockedAt: null, lockOwner: null } : { status: 'completed', processedAt: new Date(), lockedAt: null, lockOwner: null, lastError: null } }).exec(); } }
  private async deliver(event: IntegrationEventDocument, handler: import('../interfaces/integration-event.interface').IntegrationEventHandler): Promise<boolean> { const delivery = await this.eventModel.findOne({ _id: event._id, 'deliveries.handlerKey': handler.handlerKey }).select('deliveries').lean().exec(); if (delivery?.deliveries?.some((current) => current.handlerKey === handler.handlerKey && current.status === 'completed')) return true; await this.eventModel.updateOne({ _id: event._id, lockOwner: this.instanceId, 'deliveries.handlerKey': { $ne: handler.handlerKey } }, { $push: { deliveries: { handlerKey: handler.handlerKey, status: 'pending', attempts: 0 } } }).exec(); try { await handler.handle(event.toObject()); await this.eventModel.updateOne({ _id: event._id, lockOwner: this.instanceId, 'deliveries.handlerKey': handler.handlerKey }, { $set: { 'deliveries.$.status': 'completed', 'deliveries.$.completedAt': new Date(), 'deliveries.$.lastError': null }, $inc: { 'deliveries.$.attempts': 1 } }).exec(); return true; } catch (error) { await this.eventModel.updateOne({ _id: event._id, lockOwner: this.instanceId, 'deliveries.handlerKey': handler.handlerKey }, { $set: { 'deliveries.$.status': 'failed', 'deliveries.$.lastError': error instanceof Error ? error.message.slice(0, 2000) : 'Unknown error' }, $inc: { 'deliveries.$.attempts': 1 } }).exec(); return false; } }
  private async lockNext(): Promise<IntegrationEventDocument | null> { const now = new Date(); return this.eventModel.findOneAndUpdate({ status: { $in: ['pending', 'failed'] }, nextAttemptAt: { $lte: now }, $or: [{ lockedAt: { $exists: false } }, { lockedAt: null }, { lockedAt: { $lt: new Date(now.getTime() - 120000) } }] }, { $set: { status: 'processing', lockedAt: now, lockOwner: this.instanceId }, $inc: { attempts: 1 } }, { new: true }).exec(); }
}
