"""Auto-generated protobuf code from chatbot.proto.

This directory contains the auto-generated Python code from the protobuf schema.
Files are generated by running: python scripts/generate_proto.py
"""