# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import a2a_admin_pb2 as a2a__admin__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a_admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2AAdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishAgent = channel.unary_unary(
                '/a2a_admin.A2AAdminService/PublishAgent',
                request_serializer=a2a__admin__pb2.PublishAgentRequest.SerializeToString,
                response_deserializer=a2a__admin__pb2.PublishAgentResponse.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/a2a_admin.A2AAdminService/RotateKey',
                request_serializer=a2a__admin__pb2.RotateKeyRequest.SerializeToString,
                response_deserializer=a2a__admin__pb2.RotateKeyResponse.FromString,
                _registered_method=True)
        self.RevokeAgent = channel.unary_unary(
                '/a2a_admin.A2AAdminService/RevokeAgent',
                request_serializer=a2a__admin__pb2.RevokeAgentRequest.SerializeToString,
                response_deserializer=a2a__admin__pb2.RevokeAgentResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/a2a_admin.A2AAdminService/GetAgent',
                request_serializer=a2a__admin__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=a2a__admin__pb2.GetAgentResponse.FromString,
                _registered_method=True)


class A2AAdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2AAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAgent,
                    request_deserializer=a2a__admin__pb2.PublishAgentRequest.FromString,
                    response_serializer=a2a__admin__pb2.PublishAgentResponse.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=a2a__admin__pb2.RotateKeyRequest.FromString,
                    response_serializer=a2a__admin__pb2.RotateKeyResponse.SerializeToString,
            ),
            'RevokeAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAgent,
                    request_deserializer=a2a__admin__pb2.RevokeAgentRequest.FromString,
                    response_serializer=a2a__admin__pb2.RevokeAgentResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=a2a__admin__pb2.GetAgentRequest.FromString,
                    response_serializer=a2a__admin__pb2.GetAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a_admin.A2AAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a_admin.A2AAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2AAdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a_admin.A2AAdminService/PublishAgent',
            a2a__admin__pb2.PublishAgentRequest.SerializeToString,
            a2a__admin__pb2.PublishAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a_admin.A2AAdminService/RotateKey',
            a2a__admin__pb2.RotateKeyRequest.SerializeToString,
            a2a__admin__pb2.RotateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a_admin.A2AAdminService/RevokeAgent',
            a2a__admin__pb2.RevokeAgentRequest.SerializeToString,
            a2a__admin__pb2.RevokeAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a_admin.A2AAdminService/GetAgent',
            a2a__admin__pb2.GetAgentRequest.SerializeToString,
            a2a__admin__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
