# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a2a_admin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'a2a_admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from src.grpc_generated import chatbot_pb2 as chatbot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61\x32\x61_admin.proto\x12\ta2a_admin\x1a\rchatbot.proto\"E\n\x13PublishAgentRequest\x12\x1d\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x0e.chatbot.Agent\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"i\n\x14PublishAgentResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61gent_card_url\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\x12\x16\n\x0e\x61pi_key_header\x18\x04 \x01(\t\"$\n\x10RotateKeyRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"f\n\x11RotateKeyResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x16\n\x0e\x61gent_card_url\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\x12\x16\n\x0e\x61pi_key_header\x18\x04 \x01(\t\"&\n\x12RevokeAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"8\n\x13RevokeAgentResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07revoked\x18\x02 \x01(\x08\"#\n\x0fGetAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\x92\x01\n\x10GetAgentResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x04 \x01(\x08\x12\x16\n\x0e\x61pi_key_prefix\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t2\xbd\x02\n\x0f\x41\x32\x41\x41\x64minService\x12O\n\x0cPublishAgent\x12\x1e.a2a_admin.PublishAgentRequest\x1a\x1f.a2a_admin.PublishAgentResponse\x12\x46\n\tRotateKey\x12\x1b.a2a_admin.RotateKeyRequest\x1a\x1c.a2a_admin.RotateKeyResponse\x12L\n\x0bRevokeAgent\x12\x1d.a2a_admin.RevokeAgentRequest\x1a\x1e.a2a_admin.RevokeAgentResponse\x12\x43\n\x08GetAgent\x12\x1a.a2a_admin.GetAgentRequest\x1a\x1b.a2a_admin.GetAgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a_admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHAGENTREQUEST']._serialized_start=45
  _globals['_PUBLISHAGENTREQUEST']._serialized_end=114
  _globals['_PUBLISHAGENTRESPONSE']._serialized_start=116
  _globals['_PUBLISHAGENTRESPONSE']._serialized_end=221
  _globals['_ROTATEKEYREQUEST']._serialized_start=223
  _globals['_ROTATEKEYREQUEST']._serialized_end=259
  _globals['_ROTATEKEYRESPONSE']._serialized_start=261
  _globals['_ROTATEKEYRESPONSE']._serialized_end=363
  _globals['_REVOKEAGENTREQUEST']._serialized_start=365
  _globals['_REVOKEAGENTREQUEST']._serialized_end=403
  _globals['_REVOKEAGENTRESPONSE']._serialized_start=405
  _globals['_REVOKEAGENTRESPONSE']._serialized_end=461
  _globals['_GETAGENTREQUEST']._serialized_start=463
  _globals['_GETAGENTREQUEST']._serialized_end=498
  _globals['_GETAGENTRESPONSE']._serialized_start=501
  _globals['_GETAGENTRESPONSE']._serialized_end=647
  _globals['_A2AADMINSERVICE']._serialized_start=650
  _globals['_A2AADMINSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
