# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotServiceStub(object):
    """===== SERVICES =====

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAgentTeam = channel.unary_stream(
                '/chatbot.ChatbotService/RunAgentTeam',
                request_serializer=chatbot__pb2.RunAgentTeamRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.GenerateConversationName = channel.unary_unary(
                '/chatbot.ChatbotService/GenerateConversationName',
                request_serializer=chatbot__pb2.GenerateConversationNameRequest.SerializeToString,
                response_deserializer=chatbot__pb2.GenerateConversationNameResponse.FromString,
                _registered_method=True)
        self.RunPlaybookWorkflow = channel.unary_stream(
                '/chatbot.ChatbotService/RunPlaybookWorkflow',
                request_serializer=chatbot__pb2.RunPlaybookWorkflowRequest.SerializeToString,
                response_deserializer=chatbot__pb2.PlaybookStreamChunk.FromString,
                _registered_method=True)
        self.ResumePlaybookWorkflow = channel.unary_stream(
                '/chatbot.ChatbotService/ResumePlaybookWorkflow',
                request_serializer=chatbot__pb2.ResumePlaybookWorkflowRequest.SerializeToString,
                response_deserializer=chatbot__pb2.PlaybookStreamChunk.FromString,
                _registered_method=True)
        self.RunStep = channel.unary_unary(
                '/chatbot.ChatbotService/RunStep',
                request_serializer=chatbot__pb2.RunStepRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StepResponse.FromString,
                _registered_method=True)
        self.RunStepStream = channel.unary_stream(
                '/chatbot.ChatbotService/RunStepStream',
                request_serializer=chatbot__pb2.RunStepRequest.SerializeToString,
                response_deserializer=chatbot__pb2.PlaybookStreamChunk.FromString,
                _registered_method=True)
        self.ResumeStep = channel.unary_unary(
                '/chatbot.ChatbotService/ResumeStep',
                request_serializer=chatbot__pb2.ResumeStepRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StepResponse.FromString,
                _registered_method=True)
        self.EvaluateSemanticMatch = channel.unary_unary(
                '/chatbot.ChatbotService/EvaluateSemanticMatch',
                request_serializer=chatbot__pb2.EvaluateSemanticMatchRequest.SerializeToString,
                response_deserializer=chatbot__pb2.EvaluateSemanticMatchResponse.FromString,
                _registered_method=True)
        self.GeneratePlaybook = channel.unary_unary(
                '/chatbot.ChatbotService/GeneratePlaybook',
                request_serializer=chatbot__pb2.GeneratePlaybookRequest.SerializeToString,
                response_deserializer=chatbot__pb2.GeneratePlaybookResponse.FromString,
                _registered_method=True)
        self.StopPlaybookWorkflow = channel.unary_unary(
                '/chatbot.ChatbotService/StopPlaybookWorkflow',
                request_serializer=chatbot__pb2.StopPlaybookWorkflowRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StopPlaybookWorkflowResponse.FromString,
                _registered_method=True)


class ChatbotServiceServicer(object):
    """===== SERVICES =====

    """

    def RunAgentTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateConversationName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPlaybookWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumePlaybookWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStepStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateSemanticMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePlaybook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPlaybookWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAgentTeam': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAgentTeam,
                    request_deserializer=chatbot__pb2.RunAgentTeamRequest.FromString,
                    response_serializer=chatbot__pb2.StreamChunk.SerializeToString,
            ),
            'GenerateConversationName': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateConversationName,
                    request_deserializer=chatbot__pb2.GenerateConversationNameRequest.FromString,
                    response_serializer=chatbot__pb2.GenerateConversationNameResponse.SerializeToString,
            ),
            'RunPlaybookWorkflow': grpc.unary_stream_rpc_method_handler(
                    servicer.RunPlaybookWorkflow,
                    request_deserializer=chatbot__pb2.RunPlaybookWorkflowRequest.FromString,
                    response_serializer=chatbot__pb2.PlaybookStreamChunk.SerializeToString,
            ),
            'ResumePlaybookWorkflow': grpc.unary_stream_rpc_method_handler(
                    servicer.ResumePlaybookWorkflow,
                    request_deserializer=chatbot__pb2.ResumePlaybookWorkflowRequest.FromString,
                    response_serializer=chatbot__pb2.PlaybookStreamChunk.SerializeToString,
            ),
            'RunStep': grpc.unary_unary_rpc_method_handler(
                    servicer.RunStep,
                    request_deserializer=chatbot__pb2.RunStepRequest.FromString,
                    response_serializer=chatbot__pb2.StepResponse.SerializeToString,
            ),
            'RunStepStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunStepStream,
                    request_deserializer=chatbot__pb2.RunStepRequest.FromString,
                    response_serializer=chatbot__pb2.PlaybookStreamChunk.SerializeToString,
            ),
            'ResumeStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeStep,
                    request_deserializer=chatbot__pb2.ResumeStepRequest.FromString,
                    response_serializer=chatbot__pb2.StepResponse.SerializeToString,
            ),
            'EvaluateSemanticMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSemanticMatch,
                    request_deserializer=chatbot__pb2.EvaluateSemanticMatchRequest.FromString,
                    response_serializer=chatbot__pb2.EvaluateSemanticMatchResponse.SerializeToString,
            ),
            'GeneratePlaybook': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlaybook,
                    request_deserializer=chatbot__pb2.GeneratePlaybookRequest.FromString,
                    response_serializer=chatbot__pb2.GeneratePlaybookResponse.SerializeToString,
            ),
            'StopPlaybookWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPlaybookWorkflow,
                    request_deserializer=chatbot__pb2.StopPlaybookWorkflowRequest.FromString,
                    response_serializer=chatbot__pb2.StopPlaybookWorkflowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.ChatbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatbotService(object):
    """===== SERVICES =====

    """

    @staticmethod
    def RunAgentTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunAgentTeam',
            chatbot__pb2.RunAgentTeamRequest.SerializeToString,
            chatbot__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateConversationName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GenerateConversationName',
            chatbot__pb2.GenerateConversationNameRequest.SerializeToString,
            chatbot__pb2.GenerateConversationNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPlaybookWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunPlaybookWorkflow',
            chatbot__pb2.RunPlaybookWorkflowRequest.SerializeToString,
            chatbot__pb2.PlaybookStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumePlaybookWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/ResumePlaybookWorkflow',
            chatbot__pb2.ResumePlaybookWorkflowRequest.SerializeToString,
            chatbot__pb2.PlaybookStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/RunStep',
            chatbot__pb2.RunStepRequest.SerializeToString,
            chatbot__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStepStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunStepStream',
            chatbot__pb2.RunStepRequest.SerializeToString,
            chatbot__pb2.PlaybookStreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/ResumeStep',
            chatbot__pb2.ResumeStepRequest.SerializeToString,
            chatbot__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateSemanticMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/EvaluateSemanticMatch',
            chatbot__pb2.EvaluateSemanticMatchRequest.SerializeToString,
            chatbot__pb2.EvaluateSemanticMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePlaybook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GeneratePlaybook',
            chatbot__pb2.GeneratePlaybookRequest.SerializeToString,
            chatbot__pb2.GeneratePlaybookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPlaybookWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/StopPlaybookWorkflow',
            chatbot__pb2.StopPlaybookWorkflowRequest.SerializeToString,
            chatbot__pb2.StopPlaybookWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
