# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import chatbot_pb2 as chatbot__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chatbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatbotServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRootWorkCapabilities = channel.unary_unary(
                '/chatbot.ChatbotService/GetRootWorkCapabilities',
                request_serializer=chatbot__pb2.RootWorkCapabilitiesRequest.SerializeToString,
                response_deserializer=chatbot__pb2.RootWorkCapabilitiesResponse.FromString,
                _registered_method=True)
        self.RunBackgroundInvocation = channel.unary_stream(
                '/chatbot.ChatbotService/RunBackgroundInvocation',
                request_serializer=chatbot__pb2.RootBackgroundInvocationRequest.SerializeToString,
                response_deserializer=chatbot__pb2.RootBackgroundInvocationUpdate.FromString,
                _registered_method=True)
        self.RunAgentTeam = channel.unary_stream(
                '/chatbot.ChatbotService/RunAgentTeam',
                request_serializer=chatbot__pb2.RunAgentTeamRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.RunSingleAgent = channel.unary_stream(
                '/chatbot.ChatbotService/RunSingleAgent',
                request_serializer=chatbot__pb2.RunSingleAgentRequest.SerializeToString,
                response_deserializer=chatbot__pb2.StreamChunk.FromString,
                _registered_method=True)
        self.GenerateConversationName = channel.unary_unary(
                '/chatbot.ChatbotService/GenerateConversationName',
                request_serializer=chatbot__pb2.GenerateConversationNameRequest.SerializeToString,
                response_deserializer=chatbot__pb2.GenerateConversationNameResponse.FromString,
                _registered_method=True)
        self.EvaluateSemanticMatch = channel.unary_unary(
                '/chatbot.ChatbotService/EvaluateSemanticMatch',
                request_serializer=chatbot__pb2.EvaluateSemanticMatchRequest.SerializeToString,
                response_deserializer=chatbot__pb2.EvaluateSemanticMatchResponse.FromString,
                _registered_method=True)
        self.GeneratePlaybook = channel.unary_unary(
                '/chatbot.ChatbotService/GeneratePlaybook',
                request_serializer=chatbot__pb2.GeneratePlaybookRequest.SerializeToString,
                response_deserializer=chatbot__pb2.GeneratePlaybookResponse.FromString,
                _registered_method=True)
        self.EvaluateTask = channel.unary_unary(
                '/chatbot.ChatbotService/EvaluateTask',
                request_serializer=chatbot__pb2.TaskAdvisorRequest.SerializeToString,
                response_deserializer=chatbot__pb2.TaskAdvisorResult.FromString,
                _registered_method=True)
        self.AdvisePlaybookNode = channel.unary_unary(
                '/chatbot.ChatbotService/AdvisePlaybookNode',
                request_serializer=chatbot__pb2.AdvisePlaybookNodeRequest.SerializeToString,
                response_deserializer=chatbot__pb2.AdvisePlaybookNodeResponse.FromString,
                _registered_method=True)
        self.SeedConversationSession = channel.unary_unary(
                '/chatbot.ChatbotService/SeedConversationSession',
                request_serializer=chatbot__pb2.SeedConversationSessionRequest.SerializeToString,
                response_deserializer=chatbot__pb2.SeedConversationSessionResponse.FromString,
                _registered_method=True)
        self.DeleteConversationSession = channel.unary_unary(
                '/chatbot.ChatbotService/DeleteConversationSession',
                request_serializer=chatbot__pb2.DeleteConversationSessionRequest.SerializeToString,
                response_deserializer=chatbot__pb2.DeleteConversationSessionResponse.FromString,
                _registered_method=True)


class ChatbotServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetRootWorkCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBackgroundInvocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunAgentTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunSingleAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateConversationName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateSemanticMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GeneratePlaybook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdvisePlaybookNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeedConversationSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteConversationSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRootWorkCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRootWorkCapabilities,
                    request_deserializer=chatbot__pb2.RootWorkCapabilitiesRequest.FromString,
                    response_serializer=chatbot__pb2.RootWorkCapabilitiesResponse.SerializeToString,
            ),
            'RunBackgroundInvocation': grpc.unary_stream_rpc_method_handler(
                    servicer.RunBackgroundInvocation,
                    request_deserializer=chatbot__pb2.RootBackgroundInvocationRequest.FromString,
                    response_serializer=chatbot__pb2.RootBackgroundInvocationUpdate.SerializeToString,
            ),
            'RunAgentTeam': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAgentTeam,
                    request_deserializer=chatbot__pb2.RunAgentTeamRequest.FromString,
                    response_serializer=chatbot__pb2.StreamChunk.SerializeToString,
            ),
            'RunSingleAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.RunSingleAgent,
                    request_deserializer=chatbot__pb2.RunSingleAgentRequest.FromString,
                    response_serializer=chatbot__pb2.StreamChunk.SerializeToString,
            ),
            'GenerateConversationName': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateConversationName,
                    request_deserializer=chatbot__pb2.GenerateConversationNameRequest.FromString,
                    response_serializer=chatbot__pb2.GenerateConversationNameResponse.SerializeToString,
            ),
            'EvaluateSemanticMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateSemanticMatch,
                    request_deserializer=chatbot__pb2.EvaluateSemanticMatchRequest.FromString,
                    response_serializer=chatbot__pb2.EvaluateSemanticMatchResponse.SerializeToString,
            ),
            'GeneratePlaybook': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlaybook,
                    request_deserializer=chatbot__pb2.GeneratePlaybookRequest.FromString,
                    response_serializer=chatbot__pb2.GeneratePlaybookResponse.SerializeToString,
            ),
            'EvaluateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateTask,
                    request_deserializer=chatbot__pb2.TaskAdvisorRequest.FromString,
                    response_serializer=chatbot__pb2.TaskAdvisorResult.SerializeToString,
            ),
            'AdvisePlaybookNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AdvisePlaybookNode,
                    request_deserializer=chatbot__pb2.AdvisePlaybookNodeRequest.FromString,
                    response_serializer=chatbot__pb2.AdvisePlaybookNodeResponse.SerializeToString,
            ),
            'SeedConversationSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SeedConversationSession,
                    request_deserializer=chatbot__pb2.SeedConversationSessionRequest.FromString,
                    response_serializer=chatbot__pb2.SeedConversationSessionResponse.SerializeToString,
            ),
            'DeleteConversationSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteConversationSession,
                    request_deserializer=chatbot__pb2.DeleteConversationSessionRequest.FromString,
                    response_serializer=chatbot__pb2.DeleteConversationSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatbot.ChatbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatbot.ChatbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatbotService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRootWorkCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GetRootWorkCapabilities',
            chatbot__pb2.RootWorkCapabilitiesRequest.SerializeToString,
            chatbot__pb2.RootWorkCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBackgroundInvocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunBackgroundInvocation',
            chatbot__pb2.RootBackgroundInvocationRequest.SerializeToString,
            chatbot__pb2.RootBackgroundInvocationUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunAgentTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunAgentTeam',
            chatbot__pb2.RunAgentTeamRequest.SerializeToString,
            chatbot__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunSingleAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatbot.ChatbotService/RunSingleAgent',
            chatbot__pb2.RunSingleAgentRequest.SerializeToString,
            chatbot__pb2.StreamChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateConversationName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GenerateConversationName',
            chatbot__pb2.GenerateConversationNameRequest.SerializeToString,
            chatbot__pb2.GenerateConversationNameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateSemanticMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/EvaluateSemanticMatch',
            chatbot__pb2.EvaluateSemanticMatchRequest.SerializeToString,
            chatbot__pb2.EvaluateSemanticMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GeneratePlaybook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/GeneratePlaybook',
            chatbot__pb2.GeneratePlaybookRequest.SerializeToString,
            chatbot__pb2.GeneratePlaybookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/EvaluateTask',
            chatbot__pb2.TaskAdvisorRequest.SerializeToString,
            chatbot__pb2.TaskAdvisorResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdvisePlaybookNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/AdvisePlaybookNode',
            chatbot__pb2.AdvisePlaybookNodeRequest.SerializeToString,
            chatbot__pb2.AdvisePlaybookNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeedConversationSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/SeedConversationSession',
            chatbot__pb2.SeedConversationSessionRequest.SerializeToString,
            chatbot__pb2.SeedConversationSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteConversationSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatbot.ChatbotService/DeleteConversationSession',
            chatbot__pb2.DeleteConversationSessionRequest.SerializeToString,
            chatbot__pb2.DeleteConversationSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
