# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import companion_ai_pb2 as companion__ai__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in companion_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompanionAiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/CreateSession',
                request_serializer=companion__ai__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.RunTask = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/RunTask',
                request_serializer=companion__ai__pb2.RunRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.RunResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/GetSession',
                request_serializer=companion__ai__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.StopSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/StopSession',
                request_serializer=companion__ai__pb2.StopSessionRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.StopSessionResponse.FromString,
                _registered_method=True)
        self.PauseSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/PauseSession',
                request_serializer=companion__ai__pb2.PauseSessionRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.PauseSessionResponse.FromString,
                _registered_method=True)
        self.DeliverMailReply = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/DeliverMailReply',
                request_serializer=companion__ai__pb2.DeliverMailReplyRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.DeliverMailReplyResponse.FromString,
                _registered_method=True)
        self.ListOpenChatWaits = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.CompanionAi/ListOpenChatWaits',
                request_serializer=companion__ai__pb2.ListOpenChatWaitsRequest.SerializeToString,
                response_deserializer=companion__ai__pb2.ListOpenChatWaitsResponse.FromString,
                _registered_method=True)


class CompanionAiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Create an empty session for a user. Returns its id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTask(self, request, context):
        """Submit a message (new turn OR a reply that resumes a blocked plan).
        Runs in the background and acks immediately; progress is read via Electric.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """One-shot snapshot (title, status, current plan) for initial load / catch-up.
        Steady-state progress comes from Electric, not this call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """Cancel a running/blocked session (terminal — cannot be continued).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseSession(self, request, context):
        """Pause a running session: cancel the in-flight turn and keep the plan so it
        can be continued later. Continue by sending RunTask on the same session_id
        (worky re-drives the remaining steps). Unlike Stop, this is not terminal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverMailReply(self, request, context):
        """Hand a reply (email OR Teams) to the step waiting for it. Mail carries a
        routing token that travelled in the outbound message; Teams carries none —
        Graph correlates the reply structurally, so the caller passes the chat id
        instead. Either way only worky can turn the identifier into a
        session/step/interrupt: the caller passes token OR chat_id and worky
        resolves and resumes internally, delegating to the same resume the RunTask
        path uses rather than reimplementing continuation.

        Claim-once: an identifier resolves for exactly one delivery. A duplicate
        (Graph retries anything it thinks failed) returns delivered=false rather
        than resuming the step a second time. Acks immediately like RunTask, so the
        caller's webhook can answer Graph inside its timeout.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOpenChatWaits(self, request, context):
        """The Teams chats worky is currently waiting on a reply in. Teams carries no
        routing token and worky cannot subscribe to a chat it does not know, so the
        backend polls: it asks which chats are open, reads each for a human reply,
        and hands any back via DeliverMailReply(chat_id=...). Only waits that are
        deliverable (message sent -> chat known, and step parked -> interrupt bound)
        are listed; a claimed wait drops off the list, which is what stops the poll.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompanionAiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=companion__ai__pb2.CreateSessionRequest.FromString,
                    response_serializer=companion__ai__pb2.CreateSessionResponse.SerializeToString,
            ),
            'RunTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=companion__ai__pb2.RunRequest.FromString,
                    response_serializer=companion__ai__pb2.RunResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=companion__ai__pb2.GetSessionRequest.FromString,
                    response_serializer=companion__ai__pb2.GetSessionResponse.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=companion__ai__pb2.StopSessionRequest.FromString,
                    response_serializer=companion__ai__pb2.StopSessionResponse.SerializeToString,
            ),
            'PauseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseSession,
                    request_deserializer=companion__ai__pb2.PauseSessionRequest.FromString,
                    response_serializer=companion__ai__pb2.PauseSessionResponse.SerializeToString,
            ),
            'DeliverMailReply': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverMailReply,
                    request_deserializer=companion__ai__pb2.DeliverMailReplyRequest.FromString,
                    response_serializer=companion__ai__pb2.DeliverMailReplyResponse.SerializeToString,
            ),
            'ListOpenChatWaits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOpenChatWaits,
                    request_deserializer=companion__ai__pb2.ListOpenChatWaitsRequest.FromString,
                    response_serializer=companion__ai__pb2.ListOpenChatWaitsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yellowstorm.orchestrator.v1.CompanionAi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yellowstorm.orchestrator.v1.CompanionAi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompanionAi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/CreateSession',
            companion__ai__pb2.CreateSessionRequest.SerializeToString,
            companion__ai__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/RunTask',
            companion__ai__pb2.RunRequest.SerializeToString,
            companion__ai__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/GetSession',
            companion__ai__pb2.GetSessionRequest.SerializeToString,
            companion__ai__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/StopSession',
            companion__ai__pb2.StopSessionRequest.SerializeToString,
            companion__ai__pb2.StopSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/PauseSession',
            companion__ai__pb2.PauseSessionRequest.SerializeToString,
            companion__ai__pb2.PauseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverMailReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/DeliverMailReply',
            companion__ai__pb2.DeliverMailReplyRequest.SerializeToString,
            companion__ai__pb2.DeliverMailReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOpenChatWaits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.CompanionAi/ListOpenChatWaits',
            companion__ai__pb2.ListOpenChatWaitsRequest.SerializeToString,
            companion__ai__pb2.ListOpenChatWaitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
