# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import orchestrator_pb2 as orchestrator__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentOrchestratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.AgentOrchestrator/CreateSession',
                request_serializer=orchestrator__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.CreateSessionResponse.FromString,
                _registered_method=True)
        self.RunTask = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.AgentOrchestrator/RunTask',
                request_serializer=orchestrator__pb2.RunRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.RunResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.AgentOrchestrator/GetSession',
                request_serializer=orchestrator__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.StopSession = channel.unary_unary(
                '/yellowstorm.orchestrator.v1.AgentOrchestrator/StopSession',
                request_serializer=orchestrator__pb2.StopSessionRequest.SerializeToString,
                response_deserializer=orchestrator__pb2.StopSessionResponse.FromString,
                _registered_method=True)


class AgentOrchestratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Create an empty session for a user. Returns its id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTask(self, request, context):
        """Submit a message (new turn OR a reply that resumes a blocked plan).
        Runs in the background and acks immediately; progress is read via Electric.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """One-shot snapshot (title, status, current plan) for initial load / catch-up.
        Steady-state progress comes from Electric, not this call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """Cancel a running/blocked session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=orchestrator__pb2.CreateSessionRequest.FromString,
                    response_serializer=orchestrator__pb2.CreateSessionResponse.SerializeToString,
            ),
            'RunTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=orchestrator__pb2.RunRequest.FromString,
                    response_serializer=orchestrator__pb2.RunResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=orchestrator__pb2.GetSessionRequest.FromString,
                    response_serializer=orchestrator__pb2.GetSessionResponse.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=orchestrator__pb2.StopSessionRequest.FromString,
                    response_serializer=orchestrator__pb2.StopSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yellowstorm.orchestrator.v1.AgentOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yellowstorm.orchestrator.v1.AgentOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentOrchestrator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.AgentOrchestrator/CreateSession',
            orchestrator__pb2.CreateSessionRequest.SerializeToString,
            orchestrator__pb2.CreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.AgentOrchestrator/RunTask',
            orchestrator__pb2.RunRequest.SerializeToString,
            orchestrator__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.AgentOrchestrator/GetSession',
            orchestrator__pb2.GetSessionRequest.SerializeToString,
            orchestrator__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yellowstorm.orchestrator.v1.AgentOrchestrator/StopSession',
            orchestrator__pb2.StopSessionRequest.SerializeToString,
            orchestrator__pb2.StopSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
