# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.grpc_generated import playbook_flow_pb2 as playbook__flow__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in playbook_flow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlaybookFlowRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_stream(
                '/playbook_flow.PlaybookFlowRuntime/Run',
                request_serializer=playbook__flow__pb2.RunRequest.SerializeToString,
                response_deserializer=playbook__flow__pb2.RunEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/playbook_flow.PlaybookFlowRuntime/Cancel',
                request_serializer=playbook__flow__pb2.CancelRequest.SerializeToString,
                response_deserializer=playbook__flow__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.ResumeApproval = channel.unary_unary(
                '/playbook_flow.PlaybookFlowRuntime/ResumeApproval',
                request_serializer=playbook__flow__pb2.ResumeApprovalRequest.SerializeToString,
                response_deserializer=playbook__flow__pb2.ResumeApprovalResponse.FromString,
                _registered_method=True)
        self.ResumeFromStep = channel.unary_unary(
                '/playbook_flow.PlaybookFlowRuntime/ResumeFromStep',
                request_serializer=playbook__flow__pb2.ResumeFromStepRequest.SerializeToString,
                response_deserializer=playbook__flow__pb2.ResumeFromStepResponse.FromString,
                _registered_method=True)


class PlaybookFlowRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeFromStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlaybookFlowRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=playbook__flow__pb2.RunRequest.FromString,
                    response_serializer=playbook__flow__pb2.RunEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=playbook__flow__pb2.CancelRequest.FromString,
                    response_serializer=playbook__flow__pb2.CancelResponse.SerializeToString,
            ),
            'ResumeApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeApproval,
                    request_deserializer=playbook__flow__pb2.ResumeApprovalRequest.FromString,
                    response_serializer=playbook__flow__pb2.ResumeApprovalResponse.SerializeToString,
            ),
            'ResumeFromStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeFromStep,
                    request_deserializer=playbook__flow__pb2.ResumeFromStepRequest.FromString,
                    response_serializer=playbook__flow__pb2.ResumeFromStepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'playbook_flow.PlaybookFlowRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('playbook_flow.PlaybookFlowRuntime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlaybookFlowRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/playbook_flow.PlaybookFlowRuntime/Run',
            playbook__flow__pb2.RunRequest.SerializeToString,
            playbook__flow__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playbook_flow.PlaybookFlowRuntime/Cancel',
            playbook__flow__pb2.CancelRequest.SerializeToString,
            playbook__flow__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playbook_flow.PlaybookFlowRuntime/ResumeApproval',
            playbook__flow__pb2.ResumeApprovalRequest.SerializeToString,
            playbook__flow__pb2.ResumeApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeFromStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/playbook_flow.PlaybookFlowRuntime/ResumeFromStep',
            playbook__flow__pb2.ResumeFromStepRequest.SerializeToString,
            playbook__flow__pb2.ResumeFromStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
