/**
 * Upload a starter directory to Ceph and emit embedded constants for the backend.
 *
 * Usage (from YellowStorm/back):
 *   npx ts-node scripts/publish-starter-to-ceph.ts --dir ../starters/starter-react-vite-v3 --revision starter_react_vite_v3
 *
 * Env (APImanus/YellowStorm .env or shell):
 *   CEPH_S3_ENDPOINT / CEPH_ENDPOINT
 *   CEPH_S3_ACCESS_KEY_ID / CEPH_ACCESS_KEY_ID
 *   CEPH_S3_SECRET_ACCESS_KEY / CEPH_SECRET_ACCESS_KEY
 *   CEPH_S3_BUCKET (default: yellowstorm)
 */
import * as crypto from 'crypto';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import {
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3';

dotenv.config({ path: path.resolve(__dirname, '..', '.env') });
dotenv.config({ path: path.resolve(__dirname, '..', '..', '..', 'APImanus', 'backend', '.env') });

interface StarterFileEntry {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

function parseArgs(): { dir: string; revision: string; dryRun: boolean } {
  const args = process.argv.slice(2);
  let dir = '';
  let revision = '';
  let dryRun = false;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--dir') dir = args[++i] ?? '';
    else if (args[i] === '--revision') revision = args[++i] ?? '';
    else if (args[i] === '--dry-run') dryRun = true;
  }
  if (!dir || !revision) {
    throw new Error('Usage: --dir <starter-path> --revision <revision-id> [--dry-run]');
  }
  return { dir: path.resolve(dir), revision, dryRun };
}

function env(name: string, fallback?: string): string {
  const v = process.env[name]?.trim();
  if (v) return v;
  if (fallback !== undefined) return fallback;
  throw new Error(`Missing env: ${name}`);
}

function blobObjectKey(sha256: string): string {
  return `appbuilder/blobs/sha256/${sha256.slice(0, 2)}/${sha256}`;
}

function walkFiles(root: string, relative = ''): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(path.join(root, relative), { withFileTypes: true })) {
    const rel = relative ? `${relative}/${entry.name}` : entry.name;
    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      out.push(...walkFiles(root, rel));
    } else if (
      entry.name !== 'manifest.json' &&
      entry.name !== 'README.md' &&
      entry.name !== 'package-lock.json' &&
      !entry.name.endsWith('.map')
    ) {
      out.push(rel.replace(/\\/g, '/'));
    }
  }
  return out.sort((a, b) => a.localeCompare(b));
}

function writeConstants(revision: string, files: StarterFileEntry[]): void {
  const slug = revision.replace(/^starter_/, '').replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
  const revisionIdExport = `STARTER_${slug}_REVISION_ID`;
  const manifestKeyExport = `STARTER_${slug}_MANIFEST_KEY`;
  const filesExport = `STARTER_${slug}_FILES`;
  const manifestKey = `appbuilder/manifests/_system/${revision}.json`;
  const fileLines = files
    .map(
      (f) => `  {
    path: '${f.path}',
    sha256: '${f.sha256}',
    objectKey: '${f.objectKey}',
    size: ${f.size},
  }`,
    )
    .join(',\n');

  const outFile =
    revision === 'starter_react_vite_v3'
      ? path.resolve(__dirname, '..', 'src', 'modules', 'app-runtime', 'constants', 'starter-react-vite-v3.ts')
      : path.resolve(__dirname, '..', 'src', 'modules', 'app-runtime', 'constants', `${revision}.ts`);

  const content = `/**
 * Canonical React/Vite starter revision seeded in Ceph.
 * Manifest: ${manifestKey}
 * Blobs:    appbuilder/blobs/sha256/<aa>/<fullsha>
 *
 * Auto-generated by scripts/publish-starter-to-ceph.ts — do not edit manually.
 */
export const ${revisionIdExport} = '${revision}';

export const ${manifestKeyExport} =
  '${manifestKey}';

export interface StarterManifestFile {
  path: string;
  sha256: string;
  objectKey: string;
  size: number;
}

export const ${filesExport}: readonly StarterManifestFile[] = [
${fileLines},
] as const;
`;

  fs.writeFileSync(outFile, content, 'utf8');
  console.log('Wrote constants:', outFile);
}

async function main(): Promise<void> {
  const { dir, revision, dryRun } = parseArgs();
  if (!fs.existsSync(dir)) {
    throw new Error(`Starter directory not found: ${dir}`);
  }

  const endpoint = env('CEPH_S3_ENDPOINT', env('CEPH_ENDPOINT', 'https://s3-v2.yellowsys.org'));
  const accessKeyId = env('CEPH_S3_ACCESS_KEY_ID', env('CEPH_ACCESS_KEY_ID', ''));
  const secretAccessKey = env('CEPH_S3_SECRET_ACCESS_KEY', env('CEPH_SECRET_ACCESS_KEY', ''));
  const bucket = env('CEPH_S3_BUCKET', env('CEPH_BUCKET_NAME', 'yellowstorm'));

  if (!accessKeyId || !secretAccessKey) {
    throw new Error('Missing Ceph credentials (CEPH_ACCESS_KEY_ID / CEPH_SECRET_ACCESS_KEY)');
  }

  const client = new S3Client({
    endpoint,
    region: process.env.CEPH_S3_REGION || process.env.CEPH_REGION || 'us-east-1',
    credentials: { accessKeyId, secretAccessKey },
    forcePathStyle: process.env.CEPH_S3_FORCE_PATH_STYLE !== 'false',
  });

  const relativePaths = walkFiles(dir);
  const manifestFiles: StarterFileEntry[] = [];

  for (const rel of relativePaths) {
    const body = fs.readFileSync(path.join(dir, rel));
    const sha256 = crypto.createHash('sha256').update(body).digest('hex');
    const objectKey = blobObjectKey(sha256);
    manifestFiles.push({ path: rel, sha256, objectKey, size: body.length });

    if (dryRun) {
      console.log('[dry-run] blob', rel, sha256.slice(0, 12), body.length);
      continue;
    }

    let exists = false;
    try {
      await client.send(new HeadObjectCommand({ Bucket: bucket, Key: objectKey }));
      exists = true;
    } catch {
      exists = false;
    }

    if (!exists) {
      await client.send(
        new PutObjectCommand({
          Bucket: bucket,
          Key: objectKey,
          Body: body,
          ContentType: 'text/plain',
        }),
      );
      console.log('uploaded', rel, '->', objectKey);
    } else {
      console.log('reused blob', rel, objectKey);
    }
  }

  const manifestPayload = JSON.stringify(
    { revisionId: revision, parentRevisionId: null, files: manifestFiles },
    null,
    2,
  );
  const manifestKey = `appbuilder/manifests/_system/${revision}.json`;
  fs.writeFileSync(path.join(dir, 'manifest.json'), manifestPayload, 'utf8');

  if (!dryRun) {
    await client.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: manifestKey,
        Body: Buffer.from(manifestPayload, 'utf8'),
        ContentType: 'application/json',
      }),
    );
    console.log('uploaded manifest ->', manifestKey);
  } else {
    console.log('[dry-run] manifest', manifestKey, 'files', manifestFiles.length);
  }

  writeConstants(revision, manifestFiles);
  console.log(`Done. ${manifestFiles.length} files in revision ${revision}.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
